language: cpp
dist: bionic
compiler:
  - gcc
os:
  - linux
before_install:
  - sudo apt-get update
  - sudo apt-get -y install locales
  - sudo locale-gen $LANG
  - sudo apt-get -y install gcc g++ clang cppcheck cmake
  - sudo apt-get -y install zlib1g-dev libbz2-dev libgmp-dev
  - sudo apt-get -y install libboost-all-dev libxapian-dev graphviz
  - sudo apt-get -y install libreadline-dev libncurses5-dev
  - sudo apt-get -y install libzmqpp-dev libssl-dev libffi-dev
  - sudo apt-get -y install sqlite3 libsqlite3-dev libmysql++-dev
  - sudo apt-get -y install postgresql-server-dev-all
  - sudo apt-get -y install libicu-dev libprotobuf-dev protobuf-compiler
  - sudo apt-get -y install python libpython-dev python3 libpython3-dev
  - sudo apt-get -y install doxygen ghostscript texlive-latex-recommended
  - sudo apt-get -y install apt-transport-https ca-certificates gnupg software-properties-common wget
  - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
  - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
  - sudo apt-get update
  - sudo apt-get -y install cmake
  - sudo mkdir -p /opt
  - sudo git clone https://github.com/SOCI/soci.git /opt/soci
  - sudo cp ci-scripts/soci-debian-cmake.patch /opt/soci
  - sudo ./ci-scripts/soci-install-debian.sh
script:
  - mkdir build
  - pushd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE:STRING=Debug -DINSTALL_DOC:BOOL=ON -DRUN_GCOV:BOOL=OFF -DLIB_SUFFIX= ..
  - make && make check
  - sudo make install
  - /usr/bin/stdair
branches:
  only:
  - master
  - "/^stdair-\\d+\\./"
env:
 - LANG="en_US.UTF-8" LC_ALL="en_US.UTF-8"

