language: cpp
compiler:
 - gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libboost-all-dev
 - sudo apt-get install libreadline-dev libncurses5-dev python-dev gettext doxygen-latex ghostscript 
 - sudo add-apt-repository ppa:jtaylor/jtaylor -y
 - sudo apt-get install libsoci-dev
script: |
    rm -rf build
    mkdir build
    pushd build
    # LIBSUFFIX_4_CMAKE="-DLIB_SUFFIX=64"
    cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DENABLE_TEST:BOOL=ON -DINSTALL_DOC:BOOL=OFF -DRUN_GCOV:BOOL=OFF $LIBSUFFIX_4_CMAKE ..
    make check
    popd
notifications:
  irc:
  - "irc.freenode.net#airsim"

