stdair::BasLogParams Struct Reference
stdair::BasLogParams Struct Reference
Structure holding parameters for logging.
#include <stdair/basic/BasLogParams.hpp>
Public Member Functions
const LOG::EN_LogLevel & getLogLevel () const
std::ostream & getLogStream () const
const bool getForcedInitialisationFlag () const
void setForcedInitialisationFlag (const bool iForceMultipleInstance)
bool check () const
const std::string describe () const
std::string toShortString () const
std::string toString () const
BasLogParams (const LOG::EN_LogLevel iLogLevel, std::ostream &ioLogOutputStream, const bool iForceMultipleInstance=false)
BasLogParams (const BasLogParams &)
~BasLogParams ()
void toStream (std::ostream &ioOut) const
virtual void fromStream (std::istream &ioIn)
Friends
class Logger
Detailed Description
Structure holding parameters for logging.
Definition at line 19 of file BasLogParams.hpp.
Constructor & Destructor Documentation
stdair::BasLogParams::BasLogParams (const LOG::EN_LogLevel iLogLevel, std::ostream & ioLogOutputStream, const bool iForceMultipleInstance = false)
Main Constructor.
Parameters
[in] const LOG::EN_LogLevel Level of the log (e.g., DEBUG)
[in,out] std::ostream& (STL) Stream to log into.
[in] const bool Whether or not multiple initialisation should be forced.
Definition at line 27 of file BasLogParams.cpp.
stdair::BasLogParams::BasLogParams (const BasLogParams & iLogParams)
Copy constructor.
Definition at line 21 of file BasLogParams.cpp.
stdair::BasLogParams::~BasLogParams ()
Destructor.
Definition at line 35 of file BasLogParams.cpp.
Member Function Documentation
const LOG::EN_LogLevel& stdair::BasLogParams::getLogLevel () const inline
Get the log level.
Definition at line 26 of file BasLogParams.hpp.
std::ostream& stdair::BasLogParams::getLogStream () const inline
Get the log output stream.
Definition at line 33 of file BasLogParams.hpp.
const bool stdair::BasLogParams::getForcedInitialisationFlag () const inline
State whether or not multiple initialisations are to be forced.
Definition at line 40 of file BasLogParams.hpp.
void stdair::BasLogParams::setForcedInitialisationFlag (const bool iForceMultipleInstance) inline
State whether or not multiple initialisations are to be forced.
Definition at line 49 of file BasLogParams.hpp.
bool stdair::BasLogParams::check () const
Check that all the parameters are fine.
const std::string stdair::BasLogParams::describe () const virtual
Get the serialised version of the DBParams structure.
Implements stdair::StructAbstract.
Definition at line 39 of file BasLogParams.cpp.
References toString().
std::string stdair::BasLogParams::toShortString () const
Get a short display of the LOGParams structure.
Definition at line 44 of file BasLogParams.cpp.
References stdair::LOG::_logLevels.
std::string stdair::BasLogParams::toString () const
Get the serialised version of the LOGParams structure.
Definition at line 52 of file BasLogParams.cpp.
References stdair::LOG::_logLevels.
Referenced by describe().
void stdair::StructAbstract::toStream (std::ostream & ioOut) const inline inherited
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 29 of file StructAbstract.hpp.
References stdair::StructAbstract::describe().
virtual void stdair::StructAbstract::fromStream (std::istream & ioIn) inline virtual inherited
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented in stdair::BookingRequestStruct, stdair::EventStruct, stdair::TravelSolutionStruct, stdair::VirtualClassStruct, stdair::ConfigHolderStruct, stdair::FareOptionStruct, stdair::OptimisationNotificationStruct, stdair::ProgressStatusSet, stdair::YieldRange, stdair::CancellationStruct, stdair::AirlineStruct, stdair::RMEventStruct, stdair::SnapshotStruct, stdair::FFDisutilityCurveHolderStruct, stdair::FRAT5CurveHolderStruct, and stdair::BreakPointStruct.
Definition at line 38 of file StructAbstract.hpp.
Referenced by operator>>().
Friends And Related Function Documentation
friend class Logger friend
Definition at line 20 of file BasLogParams.hpp.
The documentation for this struct was generated from the following files:
stdair/basic/BasLogParams.hpp
stdair/basic/BasLogParams.cpp