stdair::DatePeriod Class Reference
stdair::DatePeriod Class Reference
Class representing the actual attributes for a fare date-period.
#include <stdair/bom/DatePeriod.hpp>
Public Types
typedef DatePeriodKey Key_T
Public Member Functions
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
std::string toString () const
const std::string describeKey () const
const Key_T & getKey () const
BomAbstract *const getParent () const
const HolderMap_T & getHolderMap () const
const DatePeriod_T & getDatePeriod () const
bool isDepartureDateValid (const Date_T &) const
Protected Member Functions
DatePeriod (const Key_T &)
virtual ~DatePeriod ()
Protected Attributes
Key_T _key
BomAbstract * _parent
HolderMap_T _holderMap
Friends
template<typename BOM >
class FacBom
template<typename BOM >
class FacCloneBom
class FacBomManager
Detailed Description
Class representing the actual attributes for a fare date-period.
Definition at line 18 of file DatePeriod.hpp.
Member Typedef Documentation
typedef DatePeriodKey stdair::DatePeriod::Key_T
Definition allowing to retrieve the associated BOM key type.
Definition at line 28 of file DatePeriod.hpp.
Constructor & Destructor Documentation
stdair::DatePeriod::DatePeriod (const Key_T & iKey) protected
Main constructor.
Definition at line 27 of file DatePeriod.cpp.
stdair::DatePeriod::~DatePeriod () protected virtual
Destructor.
Definition at line 32 of file DatePeriod.cpp.
Member Function Documentation
void stdair::DatePeriod::toStream (std::ostream & ioOut) const inline virtual
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Implements stdair::BomAbstract.
Definition at line 37 of file DatePeriod.hpp.
References toString().
void stdair::DatePeriod::fromStream (std::istream & ioIn) inline virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Implements stdair::BomAbstract.
Definition at line 46 of file DatePeriod.hpp.
std::string stdair::DatePeriod::toString () const virtual
Get the serialised version of the Business Object.
Implements stdair::BomAbstract.
Definition at line 36 of file DatePeriod.cpp.
References describeKey().
Referenced by toStream().
const std::string stdair::DatePeriod::describeKey () const inline
Get a string describing the key.
Definition at line 57 of file DatePeriod.hpp.
References _key, and stdair::DatePeriodKey::toString().
Referenced by toString().
const Key_T& stdair::DatePeriod::getKey () const inline
Get the primary key (date period).
Definition at line 66 of file DatePeriod.hpp.
References _key.
BomAbstract* const stdair::DatePeriod::getParent () const inline
Get a reference on the parent object instance.
Definition at line 73 of file DatePeriod.hpp.
References _parent.
const HolderMap_T& stdair::DatePeriod::getHolderMap () const inline
Get a reference on the children holder.
Definition at line 80 of file DatePeriod.hpp.
References _holderMap.
const DatePeriod_T& stdair::DatePeriod::getDatePeriod () const inline
Get the date period.
Definition at line 87 of file DatePeriod.hpp.
References _key, and stdair::DatePeriodKey::getDatePeriod().
Referenced by isDepartureDateValid().
bool stdair::DatePeriod::isDepartureDateValid (const Date_T & iFlightDate) const
Check if the given departure date is included in the departure period of the segment path.
Definition at line 44 of file DatePeriod.cpp.
References getDatePeriod().
Referenced by stdair::BomRetriever::retrieveDatePeriodListFromKey().
Friends And Related Function Documentation
template<typename BOM > friend class FacBom friend
Definition at line 19 of file DatePeriod.hpp.
template<typename BOM > friend class FacCloneBom friend
Definition at line 20 of file DatePeriod.hpp.
friend class FacBomManager friend
Definition at line 21 of file DatePeriod.hpp.
Member Data Documentation
Key_T stdair::DatePeriod::_key protected
Primary key (date period).
Definition at line 126 of file DatePeriod.hpp.
Referenced by describeKey(), getDatePeriod(), and getKey().
BomAbstract* stdair::DatePeriod::_parent protected
Pointer on the parent class.
Definition at line 131 of file DatePeriod.hpp.
Referenced by getParent().
HolderMap_T stdair::DatePeriod::_holderMap protected
Map holding the children.
Definition at line 136 of file DatePeriod.hpp.
Referenced by getHolderMap().
The documentation for this class was generated from the following files:
stdair/bom/DatePeriod.hpp
stdair/bom/DatePeriod.cpp