stdair::AirportPair Class Reference
stdair::AirportPair Class Reference
Class representing the actual attributes for an airport-pair.
#include <stdair/bom/AirportPair.hpp>
Public Types
typedef AirportPairKey Key_T
Public Member Functions
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
std::string toString () const
const std::string describeKey () const
const Key_T & getKey () const
const AirportCode_T & getBoardingPoint () const
const AirportCode_T & getOffPoint () const
BomAbstract *const getParent () const
const HolderMap_T & getHolderMap () const
Protected Member Functions
AirportPair (const Key_T &)
virtual ~AirportPair ()
Protected Attributes
Key_T _key
BomAbstract * _parent
HolderMap_T _holderMap
Friends
template<typename BOM >
class FacBom
template<typename BOM >
class FacCloneBom
class FacBomManager
Detailed Description
Class representing the actual attributes for an airport-pair.
Definition at line 18 of file AirportPair.hpp.
Member Typedef Documentation
typedef AirportPairKey stdair::AirportPair::Key_T
Definition allowing to retrieve the associated BOM key type.
Definition at line 28 of file AirportPair.hpp.
Constructor & Destructor Documentation
stdair::AirportPair::AirportPair (const Key_T & iKey) protected
Main constructor.
Definition at line 27 of file AirportPair.cpp.
stdair::AirportPair::~AirportPair () protected virtual
Destructor.
Definition at line 32 of file AirportPair.cpp.
Member Function Documentation
void stdair::AirportPair::toStream (std::ostream & ioOut) const inline virtual
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Implements stdair::BomAbstract.
Definition at line 37 of file AirportPair.hpp.
References toString().
void stdair::AirportPair::fromStream (std::istream & ioIn) inline virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Implements stdair::BomAbstract.
Definition at line 46 of file AirportPair.hpp.
std::string stdair::AirportPair::toString () const virtual
Get the serialised version of the Business Object.
Implements stdair::BomAbstract.
Definition at line 36 of file AirportPair.cpp.
References describeKey().
Referenced by toStream().
const std::string stdair::AirportPair::describeKey () const inline
Get a string describing the key.
Definition at line 57 of file AirportPair.hpp.
References _key, and stdair::AirportPairKey::toString().
Referenced by toString().
const Key_T& stdair::AirportPair::getKey () const inline
Get the primary key (origin airport, destination airport).
Definition at line 66 of file AirportPair.hpp.
References _key.
const AirportCode_T& stdair::AirportPair::getBoardingPoint () const inline
Get the origin airport.
Definition at line 73 of file AirportPair.hpp.
References _key, and stdair::AirportPairKey::getBoardingPoint().
const AirportCode_T& stdair::AirportPair::getOffPoint () const inline
Get the destination airport.
Definition at line 80 of file AirportPair.hpp.
References _key, and stdair::AirportPairKey::getOffPoint().
BomAbstract* const stdair::AirportPair::getParent () const inline
Get a reference on the parent object instance.
Definition at line 87 of file AirportPair.hpp.
References _parent.
const HolderMap_T& stdair::AirportPair::getHolderMap () const inline
Get a reference on the children holder.
Definition at line 94 of file AirportPair.hpp.
References _holderMap.
Friends And Related Function Documentation
template<typename BOM > friend class FacBom friend
Definition at line 19 of file AirportPair.hpp.
template<typename BOM > friend class FacCloneBom friend
Definition at line 20 of file AirportPair.hpp.
friend class FacBomManager friend
Definition at line 21 of file AirportPair.hpp.
Member Data Documentation
Key_T stdair::AirportPair::_key protected
Primary key (flight number and departure date).
Definition at line 124 of file AirportPair.hpp.
Referenced by describeKey(), getBoardingPoint(), getKey(), and getOffPoint().
BomAbstract* stdair::AirportPair::_parent protected
Pointer on the parent class (Inventory).
Definition at line 129 of file AirportPair.hpp.
Referenced by getParent().
HolderMap_T stdair::AirportPair::_holderMap protected
Map holding the children.
Definition at line 134 of file AirportPair.hpp.
Referenced by getHolderMap().
The documentation for this class was generated from the following files:
stdair/bom/AirportPair.hpp
stdair/bom/AirportPair.cpp