stdair::AirlineClassListKey Struct Reference
stdair::AirlineClassListKey Struct Reference
Key of airport-pair.
#include <stdair/bom/AirlineClassListKey.hpp>
Public Member Functions
AirlineClassListKey (const AirlineCodeList_T &, const ClassList_StringList_T &)
AirlineClassListKey (const AirlineClassListKey &)
~AirlineClassListKey ()
const AirlineCodeList_T & getAirlineCodeList () const
const ClassList_StringList_T & getClassCodeList () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
template<class Archive >
void serialize (Archive &ar, const unsigned int iFileVersion)
Friends
class boost::serialization::access
Detailed Description
Key of airport-pair.
Definition at line 25 of file AirlineClassListKey.hpp.
Constructor & Destructor Documentation
stdair::AirlineClassListKey::AirlineClassListKey (const AirlineCodeList_T & iAirlineCodeList, const ClassList_StringList_T & iClassCodeList)
Constructor.
Definition at line 24 of file AirlineClassListKey.cpp.
stdair::AirlineClassListKey::AirlineClassListKey (const AirlineClassListKey & iKey)
Copy constructor.
Definition at line 30 of file AirlineClassListKey.cpp.
stdair::AirlineClassListKey::~AirlineClassListKey ()
Destructor.
Definition at line 36 of file AirlineClassListKey.cpp.
Member Function Documentation
const AirlineCodeList_T& stdair::AirlineClassListKey::getAirlineCodeList () const inline
Get the airline code list.
Definition at line 56 of file AirlineClassListKey.hpp.
Referenced by stdair::AirlineClassList::getAirlineCodeList().
const ClassList_StringList_T& stdair::AirlineClassListKey::getClassCodeList () const inline
Get the class code list.
Definition at line 61 of file AirlineClassListKey.hpp.
Referenced by stdair::AirlineClassList::getClassCodeList().
void stdair::AirlineClassListKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 40 of file AirlineClassListKey.cpp.
References toString().
void stdair::AirlineClassListKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 45 of file AirlineClassListKey.cpp.
const std::string stdair::AirlineClassListKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-date.
Reimplemented from stdair::KeyAbstract.
Definition at line 49 of file AirlineClassListKey.cpp.
References stdair::DEFAULT_KEY_SUB_FLD_DELIMITER.
Referenced by stdair::AirlineClassList::describeKey(), and toStream().
template<class Archive > void stdair::AirlineClassListKey::serialize (Archive & ar, const unsigned int iFileVersion)
Serialisation.
Definition at line 86 of file AirlineClassListKey.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 26 of file AirlineClassListKey.hpp.
The documentation for this struct was generated from the following files:
stdair/bom/AirlineClassListKey.hpp
stdair/bom/AirlineClassListKey.cpp