stdair::BomJSONExport Class Reference
stdair::BomJSONExport Class Reference
Utility class to export StdAir objects in a JSON format.
#include <stdair/bom/BomJSONExport.hpp>
Static Public Member Functions
static void jsonExportFlightDateList (std::ostream &, const BomRoot &, const AirlineCode_T &iAirlineCode="all", const FlightNumber_T &iFlightNumber=0)
static void jsonExportFlightDateObjects (std::ostream &, const FlightDate &)
static void jsonExportBookingRequestObject (std::ostream &, const EventStruct &)
static void jsonExportBreakPointObject (std::ostream &, const EventStruct &)
Detailed Description
Utility class to export StdAir objects in a JSON format.
Definition at line 42 of file BomJSONExport.hpp.
Member Function Documentation
void stdair::BomJSONExport::jsonExportFlightDateList (std::ostream & oStream, const BomRoot & iBomRoot, const AirlineCode_T & iAirlineCode = "all", const FlightNumber_T & iFlightNumber = 0) static
Export (dump in the underlying output log stream and in JSON format) a list of flight date objects.
Parameters
std::ostream& Output stream in which the flight date objects should be logged/dumped.
const BomRoot& Root of the BOM tree containing flight-dates to be exported.
const AirlineCode& Airline for which the flight-dates should be displayed. If set to "all" (default), all the inventories will be displayed.
const FlightNumber_T& Flight number for which all the departure dates should be displayed. If set to 0 (the default), all the flight numbers will be displayed.
Definition at line 35 of file BomJSONExport.cpp.
References stdair::Inventory::getAirlineCode(), stdair::FlightDate::getDepartureDate(), and stdair::FlightDate::getFlightNumber().
Referenced by stdair::STDAIR_Service::jsonExportFlightDateList().
void stdair::BomJSONExport::jsonExportFlightDateObjects (std::ostream & oStream, const FlightDate & iFlightDate) static
Recursively export (dump in the underlying output log stream and in JSON format) the objects of the BOM tree using the given FlightDate as root.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const FlightDate& Root of the BOM tree to be exported.
Definition at line 163 of file BomJSONExport.cpp.
References stdair::FlightDate::getAirlineCode(), stdair::FlightDate::getDepartureDate(), and stdair::FlightDate::getFlightNumber().
Referenced by stdair::STDAIR_Service::jsonExportFlightDateObjects().
void stdair::BomJSONExport::jsonExportBookingRequestObject (std::ostream & oStream, const EventStruct & iEventStruct) static
Export (dump in the underlying output log stream and in JSON format) the booking request object contained in the event structure.
Parameters
std::ostream& Output stream in which the events should be logged/dumped.
const EventStruct& Booking request to be stored in JSON-ified format.
Definition at line 660 of file BomJSONExport.cpp.
References stdair::EventType::BKG_REQ, stdair::BookingRequestStruct::getBookingChannel(), stdair::EventStruct::getBookingRequest(), stdair::BookingRequestStruct::getDestination(), stdair::EventStruct::getEventType(), stdair::EventType::getLabel(), stdair::BookingRequestStruct::getOrigin(), stdair::BookingRequestStruct::getPartySize(), stdair::BookingRequestStruct::getPOS(), stdair::BookingRequestStruct::getPreferedDepartureDate(), stdair::BookingRequestStruct::getPreferredCabin(), stdair::BookingRequestStruct::getPreferredDepartureTime(), stdair::BookingRequestStruct::getRequestDateTime(), stdair::BookingRequestStruct::getStayDuration(), and stdair::BookingRequestStruct::getWTP().
Referenced by stdair::STDAIR_Service::jsonExportEventObject().
void stdair::BomJSONExport::jsonExportBreakPointObject (std::ostream & oStream, const EventStruct & iEventStruct) static
Export (dump in the underlying output log stream and in JSON format) the break point object contained in the event structure.
Parameters
std::ostream& Output stream in which the events should be logged/dumped.
const EventStruct& Break point to be stored in JSON-ified format.
Definition at line 749 of file BomJSONExport.cpp.
References stdair::EventType::BRK_PT, stdair::EventStruct::getBreakPoint(), stdair::BreakPointStruct::getBreakPointTime(), stdair::EventStruct::getEventType(), and stdair::EventType::getLabel().
Referenced by stdair::STDAIR_Service::jsonExportEventObject().
The documentation for this class was generated from the following files:
stdair/bom/BomJSONExport.hpp
stdair/bom/BomJSONExport.cpp