stdair::AirlineFeature Class Reference
stdair::AirlineFeature Class Reference
Class representing various configuration parameters (e.g., revenue management methods such EMSRb or Monte-Carlo) for a given airline for the simulation.
#include <stdair/bom/AirlineFeature.hpp>
Public Types
typedef AirlineFeatureKey Key_T
Public Member Functions
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
std::string toString () const
const std::string describeKey () const
const Key_T & getKey () const
BomAbstract *const getParent () const
const HolderMap_T & getHolderMap () const
ForecastingMethod::EN_ForecastingMethod getForecastingMethod () const
UnconstrainingMethod::EN_UnconstrainingMethod getUnconstrainingMethod () const
PartnershipTechnique::EN_PartnershipTechnique getPartnershipTechnique () const
PreOptimisationMethod::EN_PreOptimisationMethod getPreOptimisationMethod () const
OptimisationMethod::EN_OptimisationMethod getOptimisationMethod () const
void init (const ForecastingMethod &, const UnconstrainingMethod &, const PreOptimisationMethod &, const OptimisationMethod &, const HistoricalDataLimit_T &, const ControlMode_T &, const PartnershipTechnique &)
void setForecastingMethod (const ForecastingMethod &iForecastingMethod)
void setUnconstrainingMethod (const UnconstrainingMethod &iUnconstrainingMethod)
void setPartnershipTechnique (const PartnershipTechnique &iPartnershipTechnique)
void setPreOptimisationMethod (const PreOptimisationMethod &iPreOptimisationMethod)
void setOptimisationMethod (const OptimisationMethod &iOptimisationMethod)
Protected Member Functions
AirlineFeature (const Key_T &)
virtual ~AirlineFeature ()
Protected Attributes
Key_T _key
BomAbstract * _parent
HolderMap_T _holderMap
ForecastingMethod _forecastingMethod
HistoricalDataLimit_T _historicalDataLimit
ControlMode_T _controlMode
UnconstrainingMethod _unconstrainingMethod
PreOptimisationMethod _preOptimisationMethod
OptimisationMethod _optimisationMethod
PartnershipTechnique _partnershipTechnique
Friends
template<typename BOM >
class FacBom
template<typename BOM >
class FacCloneBom
class FacBomManager
Detailed Description
Class representing various configuration parameters (e.g., revenue management methods such EMSRb or Monte-Carlo) for a given airline for the simulation.
Definition at line 25 of file AirlineFeature.hpp.
Member Typedef Documentation
typedef AirlineFeatureKey stdair::AirlineFeature::Key_T
Definition allowing to retrieve the associated BOM key type.
Definition at line 35 of file AirlineFeature.hpp.
Constructor & Destructor Documentation
stdair::AirlineFeature::AirlineFeature (const Key_T & iKey) protected
Main constructor.
Definition at line 14 of file AirlineFeature.cpp.
stdair::AirlineFeature::~AirlineFeature () protected virtual
Destructor.
Definition at line 34 of file AirlineFeature.cpp.
Member Function Documentation
void stdair::AirlineFeature::toStream (std::ostream & ioOut) const inline virtual
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Implements stdair::BomAbstract.
Definition at line 44 of file AirlineFeature.hpp.
References toString().
void stdair::AirlineFeature::fromStream (std::istream & ioIn) inline virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Implements stdair::BomAbstract.
Definition at line 53 of file AirlineFeature.hpp.
std::string stdair::AirlineFeature::toString () const virtual
Get the serialised version of the Business Object.
Implements stdair::BomAbstract.
Definition at line 55 of file AirlineFeature.cpp.
References _forecastingMethod, _historicalDataLimit, _optimisationMethod, _partnershipTechnique, _preOptimisationMethod, _unconstrainingMethod, and describeKey().
Referenced by toStream().
const std::string stdair::AirlineFeature::describeKey () const inline
Get a string describing the key.
Definition at line 64 of file AirlineFeature.hpp.
References _key, and stdair::AirlineFeatureKey::toString().
Referenced by toString().
const Key_T& stdair::AirlineFeature::getKey () const inline
Get the airline feature primary key (airline code).
Definition at line 73 of file AirlineFeature.hpp.
References _key.
BomAbstract* const stdair::AirlineFeature::getParent () const inline
Get a reference on the parent object instance.
Definition at line 80 of file AirlineFeature.hpp.
References _parent.
const HolderMap_T& stdair::AirlineFeature::getHolderMap () const inline
Get a reference on the children holder.
Definition at line 87 of file AirlineFeature.hpp.
References _holderMap.
ForecastingMethod::EN_ForecastingMethod stdair::AirlineFeature::getForecastingMethod () const inline
Get the forecasting method.
Definition at line 94 of file AirlineFeature.hpp.
References _forecastingMethod, and stdair::ForecastingMethod::getMethod().
Referenced by stdair::Inventory::getForecastingMethod().
UnconstrainingMethod::EN_UnconstrainingMethod stdair::AirlineFeature::getUnconstrainingMethod () const inline
Get the unconstraining method.
Definition at line 101 of file AirlineFeature.hpp.
References _unconstrainingMethod, and stdair::UnconstrainingMethod::getMethod().
Referenced by stdair::Inventory::getUnconstrainingMethod().
PartnershipTechnique::EN_PartnershipTechnique stdair::AirlineFeature::getPartnershipTechnique () const inline
Get the partnership technique.
Definition at line 108 of file AirlineFeature.hpp.
References _partnershipTechnique, and stdair::PartnershipTechnique::getTechnique().
Referenced by stdair::Inventory::getPartnershipTechnique().
PreOptimisationMethod::EN_PreOptimisationMethod stdair::AirlineFeature::getPreOptimisationMethod () const inline
Get the pre-optimisation method.
Definition at line 115 of file AirlineFeature.hpp.
References _preOptimisationMethod, and stdair::PreOptimisationMethod::getMethod().
Referenced by stdair::Inventory::getPreOptimisationMethod().
OptimisationMethod::EN_OptimisationMethod stdair::AirlineFeature::getOptimisationMethod () const inline
Get the optimisation method.
Definition at line 122 of file AirlineFeature.hpp.
References _optimisationMethod, and stdair::OptimisationMethod::getMethod().
Referenced by stdair::Inventory::getOptimisationMethod().
void stdair::AirlineFeature::init (const ForecastingMethod & iForecastingMethod, const UnconstrainingMethod & iUnconstrainingMethod, const PreOptimisationMethod & iPreOptimisationMethod, const OptimisationMethod & iOptimisationMethod, const HistoricalDataLimit_T & iHistoricalDataLimit, const ControlMode_T & iControlMode, const PartnershipTechnique & iPartnershipTechnique)
Initialization method.
Parameters
const ForecastingMethod& Forecasting method.
const UnconstrainingMethod& Unconstraining method.
const PreOptimisationMethod& Pre-optimisation method.
const OptimisationMethodGet& Optimisation method.
const HistoricalDataLimit_T& Historical Data Limit
const ControlMode_T& Control Mode
const PartnershipTechnique& Partnership method.
Definition at line 38 of file AirlineFeature.cpp.
References _controlMode, _forecastingMethod, _historicalDataLimit, _optimisationMethod, _partnershipTechnique, _preOptimisationMethod, and _unconstrainingMethod.
void stdair::AirlineFeature::setForecastingMethod (const ForecastingMethod & iForecastingMethod) inline
Set the forecasting method.
Definition at line 150 of file AirlineFeature.hpp.
References _forecastingMethod.
Referenced by stdair::ConfigHolderStruct::updateAirlineFeatures().
void stdair::AirlineFeature::setUnconstrainingMethod (const UnconstrainingMethod & iUnconstrainingMethod) inline
Set the unconstraining method.
Definition at line 157 of file AirlineFeature.hpp.
References _unconstrainingMethod.
Referenced by stdair::ConfigHolderStruct::updateAirlineFeatures().
void stdair::AirlineFeature::setPartnershipTechnique (const PartnershipTechnique & iPartnershipTechnique) inline
Set the partnership technique.
Definition at line 164 of file AirlineFeature.hpp.
References _partnershipTechnique.
Referenced by stdair::ConfigHolderStruct::updateAirlineFeatures().
void stdair::AirlineFeature::setPreOptimisationMethod (const PreOptimisationMethod & iPreOptimisationMethod) inline
Set the pre-optimisation method.
Definition at line 171 of file AirlineFeature.hpp.
References _preOptimisationMethod.
Referenced by stdair::ConfigHolderStruct::updateAirlineFeatures().
void stdair::AirlineFeature::setOptimisationMethod (const OptimisationMethod & iOptimisationMethod) inline
Set the optimisation method.
Definition at line 178 of file AirlineFeature.hpp.
References _optimisationMethod.
Referenced by stdair::ConfigHolderStruct::updateAirlineFeatures().
Friends And Related Function Documentation
template<typename BOM > friend class FacBom friend
Definition at line 26 of file AirlineFeature.hpp.
template<typename BOM > friend class FacCloneBom friend
Definition at line 27 of file AirlineFeature.hpp.
friend class FacBomManager friend
Definition at line 28 of file AirlineFeature.hpp.
Member Data Documentation
Key_T stdair::AirlineFeature::_key protected
Primary key (date period).
Definition at line 209 of file AirlineFeature.hpp.
Referenced by describeKey(), and getKey().
BomAbstract* stdair::AirlineFeature::_parent protected
Pointer on the parent class.
Definition at line 214 of file AirlineFeature.hpp.
Referenced by getParent().
HolderMap_T stdair::AirlineFeature::_holderMap protected
Map holding the children.
Definition at line 219 of file AirlineFeature.hpp.
Referenced by getHolderMap().
ForecastingMethod stdair::AirlineFeature::_forecastingMethod protected
The type of forecaster.
Definition at line 224 of file AirlineFeature.hpp.
Referenced by getForecastingMethod(), init(), setForecastingMethod(), and toString().
HistoricalDataLimit_T stdair::AirlineFeature::_historicalDataLimit protected
The size of the moving average window.
Definition at line 229 of file AirlineFeature.hpp.
Referenced by init(), and toString().
ControlMode_T stdair::AirlineFeature::_controlMode protected
The type of inventory control.
Definition at line 234 of file AirlineFeature.hpp.
Referenced by init().
UnconstrainingMethod stdair::AirlineFeature::_unconstrainingMethod protected
The type of unconstraining method.
Definition at line 239 of file AirlineFeature.hpp.
Referenced by getUnconstrainingMethod(), init(), setUnconstrainingMethod(), and toString().
PreOptimisationMethod stdair::AirlineFeature::_preOptimisationMethod protected
The type of pre-optimisation method.
Definition at line 244 of file AirlineFeature.hpp.
Referenced by getPreOptimisationMethod(), init(), setPreOptimisationMethod(), and toString().
OptimisationMethod stdair::AirlineFeature::_optimisationMethod protected
The type of optimisation method.
Definition at line 249 of file AirlineFeature.hpp.
Referenced by getOptimisationMethod(), init(), setOptimisationMethod(), and toString().
PartnershipTechnique stdair::AirlineFeature::_partnershipTechnique protected
The type of partnership technique.
Definition at line 254 of file AirlineFeature.hpp.
Referenced by getPartnershipTechnique(), init(), setPartnershipTechnique(), and toString().
The documentation for this class was generated from the following files:
stdair/bom/AirlineFeature.hpp
stdair/bom/AirlineFeature.cpp