stdair::BomKeyManager Class Reference
stdair::BomKeyManager Class Reference
Utility class to extract key structures from strings.
#include <stdair/bom/BomKeyManager.hpp>
Static Public Member Functions
static ParsedKey extractKeys (const std::string &iFullKeyStr)
static InventoryKey extractInventoryKey (const std::string &iFullKeyStr)
static FlightDateKey extractFlightDateKey (const std::string &iFullKeyStr)
static SegmentDateKey extractSegmentDateKey (const std::string &iFullKeyStr)
static LegDateKey extractLegDateKey (const std::string &iFullKeyStr)
Detailed Description
Utility class to extract key structures from strings.
Definition at line 29 of file BomKeyManager.hpp.
Member Function Documentation
ParsedKey stdair::BomKeyManager::extractKeys (const std::string & iFullKeyStr) static
Build a ParsedKey structure from a full key string which includes an inventory key, flight-date key elements, segment-date key elements.
Definition at line 31 of file BomKeyManager.cpp.
References stdair::ParsedKey::_airlineCode, stdair::ParsedKey::_boardingPoint, stdair::ParsedKey::_boardingTime, stdair::ParsedKey::_departureDate, stdair::ParsedKey::_flightNumber, stdair::ParsedKey::_fullKey, stdair::ParsedKey::_offPoint, and stdair::DEFAULT_KEY_TOKEN_DELIMITER.
Referenced by stdair::TravelSolutionStruct::describe(), stdair::TravelSolutionStruct::describeSegmentPath(), stdair::TravelSolutionStruct::display(), extractFlightDateKey(), extractInventoryKey(), extractLegDateKey(), extractSegmentDateKey(), and stdair::BomRetriever::retrieveSegmentDateFromLongKey().
InventoryKey stdair::BomKeyManager::extractInventoryKey (const std::string & iFullKeyStr) static
Build a InventoryKey structure from a (full) key string.
The full key string gathers airline code, flight number, origin and destination, cabin and booking class. It corresponds to the output generated by the toString() methods of the XxxKey structures.
Parameters
const std::string& The full key string.
Returns
InventoryKey The just built InventoryKey structure.
Definition at line 79 of file BomKeyManager.cpp.
References extractKeys(), and stdair::ParsedKey::getInventoryKey().
Referenced by stdair::BomRetriever::retrieveInventoryFromLongKey(), and stdair::BomRetriever::retrievePartnerSegmentDateFromLongKey().
FlightDateKey stdair::BomKeyManager::extractFlightDateKey (const std::string & iFullKeyStr) static
Build a FlightDateKey structure from a (full) key string.
The full key string gathers airline code, flight number, origin and destination, cabin and booking class. It corresponds to the output generated by the toString() methods of the XxxKey structures.
Parameters
const std::string& The full key string.
Returns
FlightDateKey The just built FlightDateKey structure.
Definition at line 87 of file BomKeyManager.cpp.
References extractKeys(), and stdair::ParsedKey::getFlightDateKey().
Referenced by stdair::OnDDateKey::getDate(), and stdair::BomRetriever::retrieveFlightDateFromLongKey().
SegmentDateKey stdair::BomKeyManager::extractSegmentDateKey (const std::string & iFullKeyStr) static
Build a SegmentDateKey structure from a (full) key string.
The full key string gathers airline code, flight number, origin and destination, cabin and booking class. It corresponds to the output generated by the toString() methods of the XxxKey structures.
Parameters
const std::string& The full key string.
Returns
SegmentDateKey The just built SegmentDateKey structure.
Definition at line 95 of file BomKeyManager.cpp.
References extractKeys(), and stdair::ParsedKey::getSegmentKey().
Referenced by stdair::OnDDateKey::getDestination(), stdair::OnDDateKey::getOrigin(), and stdair::BomRetriever::retrieveSegmentDateFromLongKey().
LegDateKey stdair::BomKeyManager::extractLegDateKey (const std::string & iFullKeyStr) static
Build a LegDateKey structure from a (full) key string.
The full key string gathers airline code, flight number, origin and destination, cabin and booking class. It corresponds to the output generated by the toString() methods of the XxxKey structures.
Parameters
const std::string& The full key string.
Returns
LegDateKey The just built LegDateKey structure.
Definition at line 103 of file BomKeyManager.cpp.
References extractKeys(), and stdair::ParsedKey::getLegKey().
Referenced by stdair::BomRetriever::retrieveOperatingLegDateFromLongKey().
The documentation for this class was generated from the following files:
stdair/bom/BomKeyManager.hpp
stdair/bom/BomKeyManager.cpp