stdair::AirlineStruct Struct Reference
stdair::AirlineStruct Struct Reference
#include <stdair/bom/AirlineStruct.hpp>
Public Member Functions
const AirlineCode_T & getAirlineCode () const
const std::string & getAirlineName () const
void setAirlineCode (const AirlineCode_T &iAirlineCode)
void setAirlineName (const std::string &iAirlineName)
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string describe () const
AirlineStruct (const AirlineCode_T &, const std::string &iAirlineName)
AirlineStruct ()
AirlineStruct (const AirlineStruct &)
~AirlineStruct ()
Detailed Description
Structure holding parameters describing an airline.
Definition at line 18 of file AirlineStruct.hpp.
Constructor & Destructor Documentation
stdair::AirlineStruct::AirlineStruct (const AirlineCode_T & iAirlineCode, const std::string & iAirlineName)
Main constructor.
Definition at line 24 of file AirlineStruct.cpp.
stdair::AirlineStruct::AirlineStruct ()
Default constructor.
Definition at line 15 of file AirlineStruct.cpp.
stdair::AirlineStruct::AirlineStruct (const AirlineStruct & iAirlineStruct)
Default copy constructor.
Definition at line 19 of file AirlineStruct.cpp.
stdair::AirlineStruct::~AirlineStruct ()
Destructor.
Definition at line 30 of file AirlineStruct.cpp.
Member Function Documentation
const AirlineCode_T& stdair::AirlineStruct::getAirlineCode () const inline
Get the airline code.
Definition at line 22 of file AirlineStruct.hpp.
Referenced by soci::type_conversion< stdair::AirlineStruct >::to_base(), and stdair::DBManagerForAirlines::updateAirlineInDB().
const std::string& stdair::AirlineStruct::getAirlineName () const inline
Get the airline name.
Definition at line 27 of file AirlineStruct.hpp.
Referenced by soci::type_conversion< stdair::AirlineStruct >::to_base(), and stdair::DBManagerForAirlines::updateAirlineInDB().
void stdair::AirlineStruct::setAirlineCode (const AirlineCode_T & iAirlineCode) inline
Set the airline code.
Definition at line 33 of file AirlineStruct.hpp.
Referenced by soci::type_conversion< stdair::AirlineStruct >::from_base().
void stdair::AirlineStruct::setAirlineName (const std::string & iAirlineName) inline
Set the airline name.
Definition at line 38 of file AirlineStruct.hpp.
Referenced by soci::type_conversion< stdair::AirlineStruct >::from_base().
void stdair::AirlineStruct::toStream (std::ostream & ioOut) const
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 34 of file AirlineStruct.cpp.
References describe().
void stdair::AirlineStruct::fromStream (std::istream & ioIn) virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::StructAbstract.
Definition at line 39 of file AirlineStruct.cpp.
const std::string stdair::AirlineStruct::describe () const virtual
Display of the structure.
Implements stdair::StructAbstract.
Definition at line 43 of file AirlineStruct.cpp.
Referenced by toStream().
The documentation for this struct was generated from the following files:
stdair/bom/AirlineStruct.hpp
stdair/bom/AirlineStruct.cpp