stdair::BucketKey Struct Reference
stdair::BucketKey Struct Reference
Key of booking-class.
#include <stdair/bom/BucketKey.hpp>
Public Member Functions
BucketKey (const SeatIndex_T &)
BucketKey (const BucketKey &)
~BucketKey ()
const SeatIndex_T & getSeatIndex () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
template<class Archive >
void serialize (Archive &ar, const unsigned int iFileVersion)
Friends
class boost::serialization::access
Detailed Description
Key of booking-class.
Definition at line 26 of file BucketKey.hpp.
Constructor & Destructor Documentation
stdair::BucketKey::BucketKey (const SeatIndex_T & iSeatIndex)
Main constructor.
Definition at line 22 of file BucketKey.cpp.
stdair::BucketKey::BucketKey (const BucketKey & iBucketKey)
Copy constructor.
Definition at line 27 of file BucketKey.cpp.
stdair::BucketKey::~BucketKey ()
Destructor.
Definition at line 32 of file BucketKey.cpp.
Member Function Documentation
const SeatIndex_T& stdair::BucketKey::getSeatIndex () const inline
Get the seat index.
Definition at line 54 of file BucketKey.hpp.
Referenced by stdair::Bucket::getSeatIndex().
void stdair::BucketKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 36 of file BucketKey.cpp.
References toString().
void stdair::BucketKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 41 of file BucketKey.cpp.
const std::string stdair::BucketKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-cabin.
Reimplemented from stdair::KeyAbstract.
Definition at line 45 of file BucketKey.cpp.
Referenced by stdair::Bucket::describeKey(), and toStream().
template<class Archive > void stdair::BucketKey::serialize (Archive & ar, const unsigned int iFileVersion)
Serialisation.
Definition at line 67 of file BucketKey.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 27 of file BucketKey.hpp.
The documentation for this struct was generated from the following files:
stdair/bom/BucketKey.hpp
stdair/bom/BucketKey.cpp