stdair::AirlineFeatureKey Struct Reference
stdair::AirlineFeatureKey Struct Reference
#include <stdair/bom/AirlineFeatureKey.hpp>
Public Member Functions
AirlineFeatureKey (const AirlineCode_T &iAirlineCode)
~AirlineFeatureKey ()
const AirlineCode_T & getAirlineCode () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
Detailed Description
Key of AirlineFeature.
Definition at line 15 of file AirlineFeatureKey.hpp.
Constructor & Destructor Documentation
stdair::AirlineFeatureKey::AirlineFeatureKey (const AirlineCode_T & iAirlineCode)
Constructor.
Definition at line 12 of file AirlineFeatureKey.cpp.
stdair::AirlineFeatureKey::~AirlineFeatureKey ()
Destructor.
Definition at line 17 of file AirlineFeatureKey.cpp.
Member Function Documentation
const AirlineCode_T& stdair::AirlineFeatureKey::getAirlineCode () const inline
Get the airline code.
Definition at line 27 of file AirlineFeatureKey.hpp.
void stdair::AirlineFeatureKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 21 of file AirlineFeatureKey.cpp.
References toString().
void stdair::AirlineFeatureKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 26 of file AirlineFeatureKey.cpp.
const std::string stdair::AirlineFeatureKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-date.
Reimplemented from stdair::KeyAbstract.
Definition at line 30 of file AirlineFeatureKey.cpp.
Referenced by stdair::AirlineFeature::describeKey(), and toStream().
The documentation for this struct was generated from the following files:
stdair/bom/AirlineFeatureKey.hpp
stdair/bom/AirlineFeatureKey.cpp