stdair::CancellationStruct Struct Reference
stdair::CancellationStruct Struct Reference
Structure holding the elements of a travel solution.
#include <stdair/bom/CancellationStruct.hpp>
Public Member Functions
const SegmentPath_T & getSegmentPath () const
const ClassList_String_T & getClassList () const
const BookingClassIDList_T & getClassIDList () const
const PartySize_T & getPartySize () const
const DateTime_T & getCancellationDateTime () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string describe () const
const std::string display () const
CancellationStruct (const SegmentPath_T &, const ClassList_String_T &, const PartySize_T &, const DateTime_T &)
CancellationStruct (const SegmentPath_T &, const BookingClassIDList_T &, const PartySize_T &, const DateTime_T &)
~CancellationStruct ()
Detailed Description
Structure holding the elements of a travel solution.
Definition at line 23 of file CancellationStruct.hpp.
Constructor & Destructor Documentation
stdair::CancellationStruct::CancellationStruct (const SegmentPath_T & iSegPath, const ClassList_String_T & iList, const PartySize_T & iSize, const DateTime_T & iDateTime)
Default constructor without class ID list.
Definition at line 14 of file CancellationStruct.cpp.
stdair::CancellationStruct::CancellationStruct (const SegmentPath_T & iSegPath, const BookingClassIDList_T & iIDList, const PartySize_T & iSize, const DateTime_T & iDateTime)
Default constructor with class ID list.
Definition at line 23 of file CancellationStruct.cpp.
stdair::CancellationStruct::~CancellationStruct ()
Destructor.
Definition at line 32 of file CancellationStruct.cpp.
Member Function Documentation
const SegmentPath_T& stdair::CancellationStruct::getSegmentPath () const inline
Get the segment path.
Definition at line 27 of file CancellationStruct.hpp.
const ClassList_String_T& stdair::CancellationStruct::getClassList () const inline
Get the class list.
Definition at line 32 of file CancellationStruct.hpp.
const BookingClassIDList_T& stdair::CancellationStruct::getClassIDList () const inline
Get the class ID list.
Definition at line 37 of file CancellationStruct.hpp.
const PartySize_T& stdair::CancellationStruct::getPartySize () const inline
Get the party size.
Definition at line 42 of file CancellationStruct.hpp.
const DateTime_T& stdair::CancellationStruct::getCancellationDateTime () const inline
Get the datetime.
Definition at line 47 of file CancellationStruct.hpp.
void stdair::CancellationStruct::toStream (std::ostream & ioOut) const
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 36 of file CancellationStruct.cpp.
References describe().
void stdair::CancellationStruct::fromStream (std::istream & ioIn) virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::StructAbstract.
Definition at line 41 of file CancellationStruct.cpp.
const std::string stdair::CancellationStruct::describe () const virtual
Display of the structure.
Implements stdair::StructAbstract.
Definition at line 45 of file CancellationStruct.cpp.
References stdair::BookingClass::getClassCode(), and stdair::BomID< BOM >::getObject().
Referenced by toStream().
const std::string stdair::CancellationStruct::display () const
Display of the structure.
Definition at line 81 of file CancellationStruct.cpp.
References stdair::BookingClass::getClassCode(), and stdair::BomID< BOM >::getObject().
The documentation for this struct was generated from the following files:
stdair/bom/CancellationStruct.hpp
stdair/bom/CancellationStruct.cpp