stdair::BomDisplay Class Reference
stdair::BomDisplay Class Reference
Utility class to display StdAir objects with a pretty format.
#include <stdair/bom/BomDisplay.hpp>
Static Public Member Functions
static void list (std::ostream &, const BomRoot &, const AirlineCode_T &iAirlineCode="all", const FlightNumber_T &iFlightNumber=0)
static void list (std::ostream &, const Inventory &, const unsigned short iInventoryIndex=0, const FlightNumber_T &iFlightNumber=0)
static void listAirportPairDateRange (std::ostream &, const BomRoot &)
static void csvDisplay (std::ostream &, const BomRoot &)
static void csvDisplay (std::ostream &, const Inventory &)
static void csvDisplay (std::ostream &, const OnDDate &)
static void csvDisplay (std::ostream &, const FlightDate &)
static void csvLegDateDisplay (std::ostream &, const FlightDate &)
static void csvSegmentDateDisplay (std::ostream &, const FlightDate &)
static void csvLegCabinDisplay (std::ostream &, const FlightDate &)
static void csvSegmentCabinDisplay (std::ostream &, const FlightDate &)
static void csvFareFamilyDisplay (std::ostream &, const FlightDate &)
static void csvBucketDisplay (std::ostream &, const FlightDate &)
static void csvBookingClassDisplay (std::ostream &, const BookingClass &, const std::string &iLeadingString)
static void csvBookingClassDisplay (std::ostream &, const FlightDate &)
static void csvDisplay (std::ostream &, const TravelSolutionList_T &)
static void csvDisplay (std::ostream &, const DatePeriodList_T &)
static void csvSimFQTAirRACDisplay (std::ostream &, const BomRoot &)
static void csvAirportPairDisplay (std::ostream &, const AirportPair &)
static void csvDateDisplay (std::ostream &, const DatePeriod &)
static void csvPosChannelDisplay (std::ostream &, const PosChannel &)
static void csvTimeDisplay (std::ostream &, const TimePeriod &)
template<typename FEATURE_TYPE >
static void csvFeatureListDisplay (std::ostream &oStream, const TimePeriod &)
template<typename FEATURE_TYPE >
static void csvFeaturesDisplay (std::ostream &oStream, const FEATURE_TYPE &)
static void csvAirlineClassDisplay (std::ostream &, const AirlineClassList &)
Detailed Description
Utility class to display StdAir objects with a pretty format.
Definition at line 38 of file BomDisplay.hpp.
Member Function Documentation
static void stdair::BomDisplay::list (std::ostream & , const BomRoot & , const AirlineCode_T & iAirlineCode = "all", const FlightNumber_T & iFlightNumber = 0) static
Display (dump in the underlying output log stream) the list of flight-dates contained within the given BOM tree.
Parameters
std::ostream& Output stream in which the flight-date keys should be logged/dumped.
const BomRoot& Root of the BOM tree to be displayed.
const AirlineCode& Airline for which the flight-dates should be displayed. If set to "all" (default), all the inventories will be displayed.
const FlightNumber_T& Flight number for which all the departure dates should be displayed. If set to 0 (the default), all the flight numbers will be displayed.
Referenced by stdair::STDAIR_Service::list().
static void stdair::BomDisplay::list (std::ostream & , const Inventory & , const unsigned short iInventoryIndex = 0, const FlightNumber_T & iFlightNumber = 0) static
Display (dump in the underlying output log stream) the list of flight-dates contained within the given BOM tree.
Parameters
std::ostream& Output stream in which the flight-date keys should be logged/dumped.
const Inventory& Root of the BOM tree to be displayed.
const unsigned short Index, within the list, of the inventory. It is 0 when that inventory is displayed alone.
const FlightNumber_T& Flight number for which all the departure dates should be displayed. If set to 0 (the default), all the flight numbers will be displayed.
static void stdair::BomDisplay::listAirportPairDateRange (std::ostream & , const BomRoot &) static
Display the list of aiports pairs and date ranges (contained within the BOM tree)
Parameters
std::ostream& Output stream in which the airport pairs and date ranges are logged/dumped.
const BomRoot& Root of the BOM tree to be displayed.
Referenced by stdair::STDAIR_Service::listAirportPairDateRange().
static void stdair::BomDisplay::csvDisplay (std::ostream & , const BomRoot &) static
Recursively display (dump in the underlying output log stream) the objects of the BOM tree.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const BomRoot& Root of the BOM tree to be displayed.
Referenced by stdair::STDAIR_Service::csvDisplay().
static void stdair::BomDisplay::csvDisplay (std::ostream & , const Inventory &) static
Recursively display (dump in the underlying output log stream) the objects of the BOM tree from the level of the given Inventory.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const Inventory& Root of the BOM tree to be displayed.
static void stdair::BomDisplay::csvDisplay (std::ostream & , const OnDDate &) static
Display the O&D date object information.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const OnDDate& the BOM to be displayed.
static void stdair::BomDisplay::csvDisplay (std::ostream & , const FlightDate &) static
Recursively display (dump in the underlying output log stream) the objects of the BOM tree from the level of the given FlightDate.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const FlightDate& Root of the BOM tree to be displayed.
static void stdair::BomDisplay::csvLegDateDisplay (std::ostream & , const FlightDate &) static
Recursively display (dump in the underlying output log stream) the leg-date level objects of the BOM tree.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const FlightDate& Root of the BOM tree to be displayed.
static void stdair::BomDisplay::csvSegmentDateDisplay (std::ostream & , const FlightDate &) static
Recursively display (dump in the underlying output log stream) the segment-date level objects of the BOM tree.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const FlightDate& Root of the BOM tree to be displayed.
static void stdair::BomDisplay::csvLegCabinDisplay (std::ostream & , const FlightDate &) static
Recursively display (dump in the underlying output log stream) the leg-cabin level objects of the BOM tree.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const FlightDate& Root of the BOM tree to be displayed.
static void stdair::BomDisplay::csvSegmentCabinDisplay (std::ostream & , const FlightDate &) static
Recursively display (dump in the underlying output log stream) the segment-cabin level objects of the BOM tree.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const FlightDate& Root of the BOM tree to be displayed.
static void stdair::BomDisplay::csvFareFamilyDisplay (std::ostream & , const FlightDate &) static
Recursively display (dump in the underlying output log stream) the fare families level objects of the BOM tree.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const FlightDate& Root of the BOM tree to be displayed.
static void stdair::BomDisplay::csvBucketDisplay (std::ostream & , const FlightDate &) static
Recursively display (dump in the underlying output log stream) the bucket holder level objects of the BOM tree.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const FlightDate& Root of the BOM tree to be displayed.
static void stdair::BomDisplay::csvBookingClassDisplay (std::ostream & , const BookingClass & , const std::string & iLeadingString) static
Display (dump in the underlying output log stream) the segment-class, without going recursively deeper in the BOM tree.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const BookingClass& Root of the BOM tree to be displayed.
const std::string& Leading string to be displayed.
static void stdair::BomDisplay::csvBookingClassDisplay (std::ostream & , const FlightDate &) static
Recursively display (dump in the underlying output log stream) the segment-class level objects of the BOM tree.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const FlightDate& Root of the BOM tree to be displayed.
static void stdair::BomDisplay::csvDisplay (std::ostream & , const TravelSolutionList_T &) static
Display (dump in the underlying output log stream) the full list of travel solution structures.
Parameters
std::ostream& Output stream in which the list of travel solutions is logged/dumped.
TravelSolutionList_T& List of travel solutions to display.
static void stdair::BomDisplay::csvDisplay (std::ostream & , const DatePeriodList_T &) static
Display (dump in the underlying output log stream) the full list of date period fare rule sub bom tree.
Parameters
std::ostream& Output stream in which the list of travel solutions is logged/dumped.
DatePeriodList_T& List of date period to display.
static void stdair::BomDisplay::csvSimFQTAirRACDisplay (std::ostream & , const BomRoot &) static
Recursively display (dump in the underlying output log stream) the objects of the BOM tree.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const BomRoot& Root of the BOM tree to be displayed.
static void stdair::BomDisplay::csvAirportPairDisplay (std::ostream & , const AirportPair &) static
Recursively display (dump in the underlying output log stream) the objects of the BOM tree from the level of the given airport pair.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const AirportPair& Root of the BOM tree to be displayed.
static void stdair::BomDisplay::csvDateDisplay (std::ostream & , const DatePeriod &) static
Recursively display (dump in the underlying output log stream) the objects of the BOM tree from the level of the given date range.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const DatePeriod& Root of the BOM tree to be displayed.
static void stdair::BomDisplay::csvPosChannelDisplay (std::ostream & , const PosChannel &) static
Recursively display (dump in the underlying output log stream) the objects of the BOM tree from the level of the given point of sale channel.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const PosChannel& Root of the BOM tree to be displayed.
static void stdair::BomDisplay::csvTimeDisplay (std::ostream & , const TimePeriod &) static
Recursively display (dump in the underlying output log stream) the objects of the BOM tree from the level of the given time range.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const TimePeriod& Root of the BOM tree to be displayed.
template<typename FEATURE_TYPE > static void stdair::BomDisplay::csvFeatureListDisplay (std::ostream & oStream, const TimePeriod &) static
Recursively display (dump in the underlying output log stream) the list of fare/yield features objects of the BOM tree.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const TimePeriod& Root of the BOM tree to be displayed.
template<typename FEATURE_TYPE > static void stdair::BomDisplay::csvFeaturesDisplay (std::ostream & oStream, const FEATURE_TYPE &) static
Recursively display (dump in the underlying output log stream) the fare/yield features objects of the BOM tree.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const FEATURE_TYPE& Root of the BOM tree to be displayed.
static void stdair::BomDisplay::csvAirlineClassDisplay (std::ostream & , const AirlineClassList &) static
Recursively display (dump in the underlying output log stream) the airline class objects of the BOM tree.
Parameters
std::ostream& Output stream in which the BOM tree should be logged/dumped.
const AirlineClassList& Root of the BOM tree to be displayed.
The documentation for this class was generated from the following file:
stdair/bom/BomDisplay.hpp