stdair::ContinuousAttributeLite< T > Struct Template Reference
stdair::ContinuousAttributeLite< T > Struct Template Reference
Class modeling the distribution of values that can be taken by a continuous attribute.
#include <stdair/basic/ContinuousAttributeLite.hpp>
Public Types
typedef std::map< T, stdair::Probability_T > ContinuousDistribution_T
Public Member Functions
const T getValue (const stdair::Probability_T &iCumulativeProbability) const
const stdair::Probability_T getRemainingProportion (const T &iValue) const
const double getDerivativeValue (const T iKey) const
const T getUpperBound (const T iKey) const
const std::string displayCumulativeDistribution () const
ContinuousAttributeLite (const ContinuousDistribution_T &iValueMap)
ContinuousAttributeLite (const ContinuousAttributeLite &iCAL)
ContinuousAttributeLite & operator= (const ContinuousAttributeLite &iCAL)
virtual ~ContinuousAttributeLite ()
Detailed Description
template<typename T>
struct stdair::ContinuousAttributeLite< T >
Class modeling the distribution of values that can be taken by a continuous attribute.
Definition at line 26 of file ContinuousAttributeLite.hpp.
Member Typedef Documentation
template<typename T > typedef std::map<T, stdair::Probability_T> stdair::ContinuousAttributeLite< T >::ContinuousDistribution_T
Type for the probability mass function.
Definition at line 32 of file ContinuousAttributeLite.hpp.
Constructor & Destructor Documentation
template<typename T > stdair::ContinuousAttributeLite< T >::ContinuousAttributeLite (const ContinuousDistribution_T & iValueMap) inline
Constructor.
Definition at line 204 of file ContinuousAttributeLite.hpp.
template<typename T > stdair::ContinuousAttributeLite< T >::ContinuousAttributeLite (const ContinuousAttributeLite< T > & iCAL) inline
Copy constructor.
Definition at line 212 of file ContinuousAttributeLite.hpp.
template<typename T > virtual stdair::ContinuousAttributeLite< T >::~ContinuousAttributeLite () inline virtual
Destructor.
Definition at line 231 of file ContinuousAttributeLite.hpp.
Member Function Documentation
template<typename T > const T stdair::ContinuousAttributeLite< T >::getValue (const stdair::Probability_T & iCumulativeProbability) const inline
Get value from inverse cumulative distribution.
Definition at line 39 of file ContinuousAttributeLite.hpp.
References stdair::DictionaryManager::keyToValue(), and stdair::DictionaryManager::valueToKey().
template<typename T > const stdair::Probability_T stdair::ContinuousAttributeLite< T >::getRemainingProportion (const T & iValue) const inline
Get remaining proportion from cumulative distribution.
Definition at line 84 of file ContinuousAttributeLite.hpp.
References stdair::DictionaryManager::keyToValue().
template<typename T > const double stdair::ContinuousAttributeLite< T >::getDerivativeValue (const T iKey) const inline
Get the value of the derivative function in a key point.
Definition at line 131 of file ContinuousAttributeLite.hpp.
References stdair::DictionaryManager::keyToValue().
template<typename T > const T stdair::ContinuousAttributeLite< T >::getUpperBound (const T iKey) const inline
Get the upper bound.
Definition at line 163 of file ContinuousAttributeLite.hpp.
template<typename T > const std::string stdair::ContinuousAttributeLite< T >::displayCumulativeDistribution () const inline
Display cumulative distribution.
Definition at line 182 of file ContinuousAttributeLite.hpp.
References stdair::DictionaryManager::keyToValue().
template<typename T > ContinuousAttributeLite& stdair::ContinuousAttributeLite< T >::operator= (const ContinuousAttributeLite< T > & iCAL) inline
Copy operator.
Definition at line 221 of file ContinuousAttributeLite.hpp.
The documentation for this struct was generated from the following file:
stdair/basic/ContinuousAttributeLite.hpp