stdair::BookingRequestStruct Struct Reference
stdair::BookingRequestStruct Struct Reference
Structure holding the elements of a booking request.
#include <stdair/bom/BookingRequestStruct.hpp>
Public Member Functions
const DemandGeneratorKey_T & getDemandGeneratorKey () const
const AirportCode_T & getOrigin () const
const AirportCode_T & getDestination () const
const CityCode_T & getPOS () const
const Date_T & getPreferedDepartureDate () const
const Duration_T & getPreferredDepartureTime () const
const DateTime_T & getRequestDateTime () const
const CabinCode_T & getPreferredCabin () const
const NbOfSeats_T & getPartySize () const
const ChannelLabel_T & getBookingChannel () const
const TripType_T & getTripType () const
const DayDuration_T & getStayDuration () const
const FrequentFlyer_T & getFrequentFlyerType () const
const WTP_T & getWTP () const
const PriceValue_T & getValueOfTime () const
const ChangeFees_T & getChangeFees () const
const Disutility_T & getChangeFeeDisutility () const
const NonRefundable_T & getNonRefundable () const
const Disutility_T & getNonRefundableDisutility () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string describe () const
const std::string display () const
BookingRequestStruct (const DemandGeneratorKey_T &iGeneratorKey, const AirportCode_T &iOrigin, const AirportCode_T &iDestination, const CityCode_T &iPOS, const Date_T &iDepartureDate, const DateTime_T &iRequestDateTime, const CabinCode_T &iPreferredCabin, const NbOfSeats_T &iPartySize, const ChannelLabel_T &iChannel, const TripType_T &iTripType, const DayDuration_T &iStayDuration, const FrequentFlyer_T &iFrequentFlyerType, const Duration_T &iPreferredDepartureTime, const WTP_T &iWTP, const PriceValue_T &iValueOfTime, const ChangeFees_T &iChangeFees, const Disutility_T &iChangeFeeDisutility, const NonRefundable_T &iNonRefundable, const Disutility_T &iNonRefundableDisutility)
BookingRequestStruct (const AirportCode_T &iOrigin, const AirportCode_T &iDestination, const CityCode_T &iPOS, const Date_T &iDepartureDate, const DateTime_T &iRequestDateTime, const CabinCode_T &iPreferredCabin, const NbOfSeats_T &iPartySize, const ChannelLabel_T &iChannel, const TripType_T &iTripType, const DayDuration_T &iStayDuration, const FrequentFlyer_T &iFrequentFlyerType, const Duration_T &iPreferredDepartureTime, const WTP_T &iWTP, const PriceValue_T &iValueOfTime, const ChangeFees_T &iChangeFees, const Disutility_T &iChangeFeeDisutility, const NonRefundable_T &iNonRefundable, const Disutility_T &iNonRefundableDisutility)
BookingRequestStruct (const BookingRequestStruct &)
~BookingRequestStruct ()
Detailed Description
Structure holding the elements of a booking request.
Definition at line 21 of file BookingRequestStruct.hpp.
Constructor & Destructor Documentation
stdair::BookingRequestStruct::BookingRequestStruct (const DemandGeneratorKey_T & iGeneratorKey, const AirportCode_T & iOrigin, const AirportCode_T & iDestination, const CityCode_T & iPOS, const Date_T & iDepartureDate, const DateTime_T & iRequestDateTime, const CabinCode_T & iPreferredCabin, const NbOfSeats_T & iPartySize, const ChannelLabel_T & iChannel, const TripType_T & iTripType, const DayDuration_T & iStayDuration, const FrequentFlyer_T & iFrequentFlyerType, const Duration_T & iPreferredDepartureTime, const WTP_T & iWTP, const PriceValue_T & iValueOfTime, const ChangeFees_T & iChangeFees, const Disutility_T & iChangeFeeDisutility, const NonRefundable_T & iNonRefundable, const Disutility_T & iNonRefundableDisutility)
Default constructor.
Definition at line 63 of file BookingRequestStruct.cpp.
stdair::BookingRequestStruct::BookingRequestStruct (const AirportCode_T & iOrigin, const AirportCode_T & iDestination, const CityCode_T & iPOS, const Date_T & iDepartureDate, const DateTime_T & iRequestDateTime, const CabinCode_T & iPreferredCabin, const NbOfSeats_T & iPartySize, const ChannelLabel_T & iChannel, const TripType_T & iTripType, const DayDuration_T & iStayDuration, const FrequentFlyer_T & iFrequentFlyerType, const Duration_T & iPreferredDepartureTime, const WTP_T & iWTP, const PriceValue_T & iValueOfTime, const ChangeFees_T & iChangeFees, const Disutility_T & iChangeFeeDisutility, const NonRefundable_T & iNonRefundable, const Disutility_T & iNonRefundableDisutility)
Constructor without the demand generator key, used for batches.
Definition at line 98 of file BookingRequestStruct.cpp.
stdair::BookingRequestStruct::BookingRequestStruct (const BookingRequestStruct & iBookingRequest)
Copy constructor.
Definition at line 39 of file BookingRequestStruct.cpp.
stdair::BookingRequestStruct::~BookingRequestStruct ()
Destructor.
Definition at line 131 of file BookingRequestStruct.cpp.
Member Function Documentation
const DemandGeneratorKey_T& stdair::BookingRequestStruct::getDemandGeneratorKey () const inline
Get the demand generator key.
Definition at line 25 of file BookingRequestStruct.hpp.
const AirportCode_T& stdair::BookingRequestStruct::getOrigin () const inline
Get the requested origin.
Definition at line 30 of file BookingRequestStruct.hpp.
Referenced by stdair::BomJSONExport::jsonExportBookingRequestObject().
const AirportCode_T& stdair::BookingRequestStruct::getDestination () const inline
Get the requested destination.
Definition at line 35 of file BookingRequestStruct.hpp.
Referenced by stdair::BomJSONExport::jsonExportBookingRequestObject().
const CityCode_T& stdair::BookingRequestStruct::getPOS () const inline
Get the point-of-sale.
Definition at line 40 of file BookingRequestStruct.hpp.
Referenced by stdair::BomJSONExport::jsonExportBookingRequestObject().
const Date_T& stdair::BookingRequestStruct::getPreferedDepartureDate () const inline
Get the requested departure date.
Definition at line 45 of file BookingRequestStruct.hpp.
Referenced by stdair::BomJSONExport::jsonExportBookingRequestObject().
const Duration_T& stdair::BookingRequestStruct::getPreferredDepartureTime () const inline
Get the preferred departure time.
Definition at line 50 of file BookingRequestStruct.hpp.
Referenced by stdair::BomJSONExport::jsonExportBookingRequestObject().
const DateTime_T& stdair::BookingRequestStruct::getRequestDateTime () const inline
Get the request datetime.
Definition at line 55 of file BookingRequestStruct.hpp.
Referenced by stdair::BomJSONExport::jsonExportBookingRequestObject().
const CabinCode_T& stdair::BookingRequestStruct::getPreferredCabin () const inline
Get the preferred cabin.
Definition at line 60 of file BookingRequestStruct.hpp.
Referenced by stdair::BomJSONExport::jsonExportBookingRequestObject().
const NbOfSeats_T& stdair::BookingRequestStruct::getPartySize () const inline
Get the party size.
Definition at line 65 of file BookingRequestStruct.hpp.
Referenced by stdair::BomJSONExport::jsonExportBookingRequestObject().
const ChannelLabel_T& stdair::BookingRequestStruct::getBookingChannel () const inline
Get the reservation channel.
Definition at line 70 of file BookingRequestStruct.hpp.
Referenced by stdair::BomJSONExport::jsonExportBookingRequestObject().
const TripType_T& stdair::BookingRequestStruct::getTripType () const inline
Get the trip type.
Definition at line 75 of file BookingRequestStruct.hpp.
const DayDuration_T& stdair::BookingRequestStruct::getStayDuration () const inline
Get the duration of stay.
Definition at line 80 of file BookingRequestStruct.hpp.
Referenced by stdair::BomJSONExport::jsonExportBookingRequestObject().
const FrequentFlyer_T& stdair::BookingRequestStruct::getFrequentFlyerType () const inline
Get the frequent flyer type.
Definition at line 85 of file BookingRequestStruct.hpp.
const WTP_T& stdair::BookingRequestStruct::getWTP () const inline
Get the willingness-to-pay.
Definition at line 90 of file BookingRequestStruct.hpp.
Referenced by stdair::BomJSONExport::jsonExportBookingRequestObject().
const PriceValue_T& stdair::BookingRequestStruct::getValueOfTime () const inline
Get the value of time.
Definition at line 95 of file BookingRequestStruct.hpp.
const ChangeFees_T& stdair::BookingRequestStruct::getChangeFees () const inline
Get the change fee acceptation.
Definition at line 100 of file BookingRequestStruct.hpp.
const Disutility_T& stdair::BookingRequestStruct::getChangeFeeDisutility () const inline
Get the change disutility.
Definition at line 105 of file BookingRequestStruct.hpp.
const NonRefundable_T& stdair::BookingRequestStruct::getNonRefundable () const inline
Get the non refundable acceptation.
Definition at line 110 of file BookingRequestStruct.hpp.
const Disutility_T& stdair::BookingRequestStruct::getNonRefundableDisutility () const inline
Get the non refundable disutility.
Definition at line 115 of file BookingRequestStruct.hpp.
void stdair::BookingRequestStruct::toStream (std::ostream & ioOut) const
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 135 of file BookingRequestStruct.cpp.
References describe().
void stdair::BookingRequestStruct::fromStream (std::istream & ioIn) virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::StructAbstract.
Definition at line 140 of file BookingRequestStruct.cpp.
const std::string stdair::BookingRequestStruct::describe () const virtual
Display of the structure.
Implements stdair::StructAbstract.
Definition at line 144 of file BookingRequestStruct.cpp.
Referenced by toStream().
const std::string stdair::BookingRequestStruct::display () const
Display of the structure.
#id,
request_date (YYMMDD),
request_time (HHMMSS),
POS (three-letter code),
Channel (two-letter code):
'D' for direct or 'I' for indirect,
'N' for oNline or 'F' for oFfline,
Origin (three-letter code),
Destination (three-letter code),
Preferred departure date (YYMMDD),
Preferred departure time (HHMM),
Min departure time (HHMM),
Max departure time (HHMM),
Preferred arrival date (YYMMDD),
Preferred arrival time (HHMM),
Preferred cabin:
'F' for first,
'C' for club/business,
'W' for economy plus,
'M' for economy,
Trip type:
'OW' for a one-way trip,
'RO' for the outbound part of a rount-trip,
'RI' for the inbound part of a rount-trip,
Duration of stay (expressed as a number of days),
Frequent flyer tier:
'G' for gold,
'S' for silver,
'K' for basic,
'N' for none,
Willingness-to-pay (WTP, expressed as a monetary unit, e.g., EUR),
Disutility per stop (expressed as a monetary unit, e.g., EUR),
Value of time (EUR per hour),
Returns
const std::string The output of the booking request structure.
Definition at line 169 of file BookingRequestStruct.cpp.
References stdair::TRIP_TYPE_ONE_WAY.
The documentation for this struct was generated from the following files:
stdair/bom/BookingRequestStruct.hpp
stdair/bom/BookingRequestStruct.cpp