stdair::Bucket Class Reference
stdair::Bucket Class Reference
Class representing the actual attributes for an airline booking class.
#include <stdair/bom/Bucket.hpp>
Public Types
typedef BucketKey Key_T
Public Member Functions
const Key_T & getKey () const
BomAbstract *const getParent () const
const HolderMap_T & getHolderMap () const
const SeatIndex_T & getSeatIndex () const
const Yield_T & getYieldRangeUpperValue () const
const CabinCapacity_T & getAvailability () const
const NbOfSeats_T & getSoldSeats () const
void setYieldRangeUpperValue (const Yield_T &iYield)
void setAvailability (const CabinCapacity_T &iAvl)
void setSoldSeats (const NbOfSeats_T &iSoldSeats)
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
std::string toString () const
const std::string describeKey () const
template<class Archive >
void serialize (Archive &ar, const unsigned int iFileVersion)
Protected Member Functions
Bucket (const Key_T &)
virtual ~Bucket ()
Protected Attributes
Key_T _key
BomAbstract * _parent
HolderMap_T _holderMap
Yield_T _yieldRangeUpperValue
CabinCapacity_T _availability
NbOfSeats_T _soldSeats
Friends
template<typename BOM >
class FacBom
template<typename BOM >
class FacCloneBom
class FacBomManager
class boost::serialization::access
Detailed Description
Class representing the actual attributes for an airline booking class.
Definition at line 29 of file Bucket.hpp.
Member Typedef Documentation
typedef BucketKey stdair::Bucket::Key_T
Definition allowing to retrieve the associated BOM key type.
Definition at line 40 of file Bucket.hpp.
Constructor & Destructor Documentation
stdair::Bucket::Bucket (const Key_T & iKey) protected
Default constructor.
Definition at line 34 of file Bucket.cpp.
stdair::Bucket::~Bucket () protected virtual
Destructor.
Definition at line 38 of file Bucket.cpp.
Member Function Documentation
const Key_T& stdair::Bucket::getKey () const inline
Get the primary key of the bucket.
Definition at line 47 of file Bucket.hpp.
References _key.
BomAbstract* const stdair::Bucket::getParent () const inline
Get the parent object.
Definition at line 54 of file Bucket.hpp.
References _parent.
const HolderMap_T& stdair::Bucket::getHolderMap () const inline
Get the map of children holders.
Definition at line 59 of file Bucket.hpp.
References _holderMap.
const SeatIndex_T& stdair::Bucket::getSeatIndex () const inline
Get the seat index (part of the primary key).
Definition at line 64 of file Bucket.hpp.
References _key, and stdair::BucketKey::getSeatIndex().
const Yield_T& stdair::Bucket::getYieldRangeUpperValue () const inline
Get the upper yield range.
Definition at line 69 of file Bucket.hpp.
References _yieldRangeUpperValue.
const CabinCapacity_T& stdair::Bucket::getAvailability () const inline
Get the availability.
Definition at line 74 of file Bucket.hpp.
References _availability.
const NbOfSeats_T& stdair::Bucket::getSoldSeats () const inline
Get the number of seats already sold.
Definition at line 79 of file Bucket.hpp.
References _soldSeats.
void stdair::Bucket::setYieldRangeUpperValue (const Yield_T & iYield) inline
Set the upper yield range.
Definition at line 86 of file Bucket.hpp.
References _yieldRangeUpperValue.
void stdair::Bucket::setAvailability (const CabinCapacity_T & iAvl) inline
Set the availability.
Definition at line 91 of file Bucket.hpp.
References _availability.
void stdair::Bucket::setSoldSeats (const NbOfSeats_T & iSoldSeats) inline
Set the number of seats already sold.
Definition at line 96 of file Bucket.hpp.
References _soldSeats.
void stdair::Bucket::toStream (std::ostream & ioOut) const inline virtual
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Implements stdair::BomAbstract.
Definition at line 108 of file Bucket.hpp.
References toString().
void stdair::Bucket::fromStream (std::istream & ioIn) inline virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Implements stdair::BomAbstract.
Definition at line 117 of file Bucket.hpp.
std::string stdair::Bucket::toString () const virtual
Get the serialised version of the Business Object.
Implements stdair::BomAbstract.
Definition at line 42 of file Bucket.cpp.
References describeKey().
Referenced by toStream().
const std::string stdair::Bucket::describeKey () const inline
Get a string describing the key.
Definition at line 128 of file Bucket.hpp.
References _key, and stdair::BucketKey::toString().
Referenced by toString().
template<class Archive > void stdair::Bucket::serialize (Archive & ar, const unsigned int iFileVersion)
Serialisation.
Definition at line 64 of file Bucket.cpp.
References _key.
Friends And Related Function Documentation
template<typename BOM > friend class FacBom friend
Definition at line 30 of file Bucket.hpp.
template<typename BOM > friend class FacCloneBom friend
Definition at line 31 of file Bucket.hpp.
friend class FacBomManager friend
Definition at line 32 of file Bucket.hpp.
friend class boost::serialization::access friend
Definition at line 33 of file Bucket.hpp.
Member Data Documentation
Key_T stdair::Bucket::_key protected
Primary key (upper yield range).
Definition at line 179 of file Bucket.hpp.
Referenced by describeKey(), getKey(), getSeatIndex(), and serialize().
BomAbstract* stdair::Bucket::_parent protected
Pointer on the parent class (LegCabin).
Definition at line 184 of file Bucket.hpp.
Referenced by getParent().
HolderMap_T stdair::Bucket::_holderMap protected
Map holding the children (empty for now).
Definition at line 189 of file Bucket.hpp.
Referenced by getHolderMap().
Yield_T stdair::Bucket::_yieldRangeUpperValue protected
Upper yield range.
Definition at line 197 of file Bucket.hpp.
Referenced by getYieldRangeUpperValue(), and setYieldRangeUpperValue().
CabinCapacity_T stdair::Bucket::_availability protected
Availability.
Definition at line 202 of file Bucket.hpp.
Referenced by getAvailability(), and setAvailability().
NbOfSeats_T stdair::Bucket::_soldSeats protected
Number of seats already sold.
Definition at line 207 of file Bucket.hpp.
Referenced by getSoldSeats(), and setSoldSeats().
The documentation for this class was generated from the following files:
stdair/bom/Bucket.hpp
stdair/bom/Bucket.cpp