stdair::BookingClassKey Struct Reference
stdair::BookingClassKey Struct Reference
#include <stdair/bom/BookingClassKey.hpp>
Public Member Functions
BookingClassKey (const ClassCode_T &iClassCode)
BookingClassKey (const BookingClassKey &)
~BookingClassKey ()
const ClassCode_T & getClassCode () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
Detailed Description
Key of a given leg-cabin, made of a cabin code.
Definition at line 16 of file BookingClassKey.hpp.
Constructor & Destructor Documentation
stdair::BookingClassKey::BookingClassKey (const ClassCode_T & iClassCode)
Constructor.
Definition at line 24 of file BookingClassKey.cpp.
stdair::BookingClassKey::BookingClassKey (const BookingClassKey & iKey)
Default copy constructor.
Definition at line 19 of file BookingClassKey.cpp.
stdair::BookingClassKey::~BookingClassKey ()
Destructor.
Definition at line 29 of file BookingClassKey.cpp.
Member Function Documentation
const ClassCode_T& stdair::BookingClassKey::getClassCode () const inline
Get the class code.
Definition at line 34 of file BookingClassKey.hpp.
Referenced by stdair::BookingClass::getClassCode().
void stdair::BookingClassKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 33 of file BookingClassKey.cpp.
References toString().
void stdair::BookingClassKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 38 of file BookingClassKey.cpp.
const std::string stdair::BookingClassKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-cabin.
Reimplemented from stdair::KeyAbstract.
Definition at line 42 of file BookingClassKey.cpp.
Referenced by stdair::BookingClass::describeKey(), and toStream().
The documentation for this struct was generated from the following files:
stdair/bom/BookingClassKey.hpp
stdair/bom/BookingClassKey.cpp