stdair::BreakPointStruct Struct Reference
stdair::BreakPointStruct Struct Reference
#include <stdair/bom/BreakPointStruct.hpp>
Public Member Functions
const DateTime_T & getBreakPointTime () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string describe () const
BreakPointStruct (const DateTime_T &)
BreakPointStruct (const Date_T &)
BreakPointStruct (const BreakPointStruct &)
~BreakPointStruct ()
Detailed Description
Structure holding the elements of a break point.
Definition at line 18 of file BreakPointStruct.hpp.
Constructor & Destructor Documentation
stdair::BreakPointStruct::BreakPointStruct (const DateTime_T & iBreakPointTime)
Constructor.
Definition at line 26 of file BreakPointStruct.cpp.
stdair::BreakPointStruct::BreakPointStruct (const Date_T & iBreakPointDate)
Constructor.
Definition at line 32 of file BreakPointStruct.cpp.
stdair::BreakPointStruct::BreakPointStruct (const BreakPointStruct & iBreakPoint)
Copy constructor.
Definition at line 20 of file BreakPointStruct.cpp.
stdair::BreakPointStruct::~BreakPointStruct ()
Destructor.
Definition at line 37 of file BreakPointStruct.cpp.
Member Function Documentation
const DateTime_T& stdair::BreakPointStruct::getBreakPointTime () const inline
Get the break point action time.
Definition at line 22 of file BreakPointStruct.hpp.
Referenced by stdair::BomJSONExport::jsonExportBreakPointObject().
void stdair::BreakPointStruct::toStream (std::ostream & ioOut) const
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 41 of file BreakPointStruct.cpp.
References describe().
void stdair::BreakPointStruct::fromStream (std::istream & ioIn) virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::StructAbstract.
Definition at line 46 of file BreakPointStruct.cpp.
const std::string stdair::BreakPointStruct::describe () const virtual
Display of the structure.
Implements stdair::StructAbstract.
Definition at line 50 of file BreakPointStruct.cpp.
Referenced by toStream().
The documentation for this struct was generated from the following files:
stdair/bom/BreakPointStruct.hpp
stdair/bom/BreakPointStruct.cpp