stdair::BasDBParams Struct Reference
stdair::BasDBParams Struct Reference
Structure holding the parameters for connection to a database.
#include <stdair/basic/BasDBParams.hpp>
Public Member Functions
const std::string & getUser () const
const std::string & getPassword () const
const std::string & getHost () const
const std::string & getPort () const
const std::string & getDBName () const
void setUser (const std::string &iUser)
void setPassword (const std::string &iPasswd)
void setHost (const std::string &iHost)
void setPort (const std::string &iPort)
void setDBName (const std::string &iDBName)
bool check () const
const std::string describe () const
std::string toShortString () const
std::string toString () const
BasDBParams (const std::string &iDBUser, const std::string &iDBPasswd, const std::string &iDBHost, const std::string &iDBPort, const std::string &iDBName)
BasDBParams ()
BasDBParams (const BasDBParams &)
~BasDBParams ()
void toStream (std::ostream &ioOut) const
virtual void fromStream (std::istream &ioIn)
Detailed Description
Structure holding the parameters for connection to a database.
Definition at line 19 of file BasDBParams.hpp.
Constructor & Destructor Documentation
stdair::BasDBParams::BasDBParams (const std::string & iDBUser, const std::string & iDBPasswd, const std::string & iDBHost, const std::string & iDBPort, const std::string & iDBName)
Main Constructor.
Definition at line 24 of file BasDBParams.cpp.
stdair::BasDBParams::BasDBParams ()
Default Constructor.
Definition at line 13 of file BasDBParams.cpp.
stdair::BasDBParams::BasDBParams (const BasDBParams & iDBParams)
Default copy constructor.
Definition at line 17 of file BasDBParams.cpp.
stdair::BasDBParams::~BasDBParams ()
Destructor.
Definition at line 34 of file BasDBParams.cpp.
Member Function Documentation
const std::string& stdair::BasDBParams::getUser () const inline
Get the database user name.
Definition at line 23 of file BasDBParams.hpp.
const std::string& stdair::BasDBParams::getPassword () const inline
Get the database user password.
Definition at line 28 of file BasDBParams.hpp.
const std::string& stdair::BasDBParams::getHost () const inline
Get the database host name.
Definition at line 33 of file BasDBParams.hpp.
const std::string& stdair::BasDBParams::getPort () const inline
Get the database port number.
Definition at line 38 of file BasDBParams.hpp.
const std::string& stdair::BasDBParams::getDBName () const inline
Get the database name.
Definition at line 43 of file BasDBParams.hpp.
void stdair::BasDBParams::setUser (const std::string & iUser) inline
Set the database user name.
Definition at line 50 of file BasDBParams.hpp.
void stdair::BasDBParams::setPassword (const std::string & iPasswd) inline
Set the database password.
Definition at line 55 of file BasDBParams.hpp.
void stdair::BasDBParams::setHost (const std::string & iHost) inline
Set the database host name.
Definition at line 60 of file BasDBParams.hpp.
void stdair::BasDBParams::setPort (const std::string & iPort) inline
Set the database port number.
Definition at line 65 of file BasDBParams.hpp.
void stdair::BasDBParams::setDBName (const std::string & iDBName) inline
Set the database name.
Definition at line 70 of file BasDBParams.hpp.
bool stdair::BasDBParams::check () const
Check that all the parameters are fine.
Definition at line 57 of file BasDBParams.cpp.
const std::string stdair::BasDBParams::describe () const virtual
Get the serialised version of the DBParams structure.
Implements stdair::StructAbstract.
Definition at line 38 of file BasDBParams.cpp.
References toString().
std::string stdair::BasDBParams::toShortString () const
Get a short display of the DBParams structure.
Definition at line 43 of file BasDBParams.cpp.
std::string stdair::BasDBParams::toString () const
Get the serialised version of the DBParams structure.
Definition at line 50 of file BasDBParams.cpp.
Referenced by describe().
void stdair::StructAbstract::toStream (std::ostream & ioOut) const inline inherited
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 29 of file StructAbstract.hpp.
References stdair::StructAbstract::describe().
virtual void stdair::StructAbstract::fromStream (std::istream & ioIn) inline virtual inherited
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented in stdair::BookingRequestStruct, stdair::EventStruct, stdair::TravelSolutionStruct, stdair::VirtualClassStruct, stdair::ConfigHolderStruct, stdair::FareOptionStruct, stdair::OptimisationNotificationStruct, stdair::ProgressStatusSet, stdair::YieldRange, stdair::CancellationStruct, stdair::AirlineStruct, stdair::RMEventStruct, stdair::SnapshotStruct, stdair::FFDisutilityCurveHolderStruct, stdair::FRAT5CurveHolderStruct, and stdair::BreakPointStruct.
Definition at line 38 of file StructAbstract.hpp.
Referenced by operator>>().
The documentation for this struct was generated from the following files:
stdair/basic/BasDBParams.hpp
stdair/basic/BasDBParams.cpp