stdair::AirportPairKey Struct Reference
stdair::AirportPairKey Struct Reference
Key of airport-pair.
#include <stdair/bom/AirportPairKey.hpp>
Public Member Functions
AirportPairKey (const stdair::AirportCode_T &, const stdair::AirportCode_T &)
AirportPairKey (const AirportPairKey &)
~AirportPairKey ()
const stdair::AirportCode_T & getBoardingPoint () const
const stdair::AirportCode_T & getOffPoint () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
Detailed Description
Key of airport-pair.
Definition at line 16 of file AirportPairKey.hpp.
Constructor & Destructor Documentation
stdair::AirportPairKey::AirportPairKey (const stdair::AirportCode_T & iBoardingPoint, const stdair::AirportCode_T & iOffPoint)
Main constructor.
Definition at line 22 of file AirportPairKey.cpp.
stdair::AirportPairKey::AirportPairKey (const AirportPairKey & iKey)
Copy constructor.
Definition at line 28 of file AirportPairKey.cpp.
stdair::AirportPairKey::~AirportPairKey ()
Destructor.
Definition at line 34 of file AirportPairKey.cpp.
Member Function Documentation
const stdair::AirportCode_T& stdair::AirportPairKey::getBoardingPoint () const inline
Get the boarding point.
Definition at line 36 of file AirportPairKey.hpp.
Referenced by stdair::AirportPair::getBoardingPoint().
const stdair::AirportCode_T& stdair::AirportPairKey::getOffPoint () const inline
Get the arrival point.
Definition at line 43 of file AirportPairKey.hpp.
Referenced by stdair::AirportPair::getOffPoint().
void stdair::AirportPairKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 38 of file AirportPairKey.cpp.
References toString().
void stdair::AirportPairKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 43 of file AirportPairKey.cpp.
const std::string stdair::AirportPairKey::toString () const virtual
Get the serialised version of the Business Object Key. That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
Reimplemented from stdair::KeyAbstract.
Definition at line 47 of file AirportPairKey.cpp.
References stdair::DEFAULT_KEY_SUB_FLD_DELIMITER.
Referenced by stdair::AirportPair::describeKey(), stdair::BomRetriever::retrieveAirportPairFromKeySet(), and toStream().
The documentation for this struct was generated from the following files:
stdair/bom/AirportPairKey.hpp
stdair/bom/AirportPairKey.cpp