stdair::DatePeriodKey Struct Reference
stdair::DatePeriodKey Struct Reference
Key of date-period.
#include <stdair/bom/DatePeriodKey.hpp>
Public Member Functions
DatePeriodKey (const DatePeriod_T &)
DatePeriodKey (const DatePeriodKey &)
~DatePeriodKey ()
const DatePeriod_T & getDatePeriod () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
Detailed Description
Key of date-period.
Definition at line 14 of file DatePeriodKey.hpp.
Constructor & Destructor Documentation
stdair::DatePeriodKey::DatePeriodKey (const DatePeriod_T & iDatePeriod)
Main Constructor.
Definition at line 22 of file DatePeriodKey.cpp.
stdair::DatePeriodKey::DatePeriodKey (const DatePeriodKey & iKey)
Copy constructor.
Definition at line 27 of file DatePeriodKey.cpp.
stdair::DatePeriodKey::~DatePeriodKey ()
Destructor.
Definition at line 32 of file DatePeriodKey.cpp.
Member Function Documentation
const DatePeriod_T& stdair::DatePeriodKey::getDatePeriod () const inline
Get the date period.
Definition at line 32 of file DatePeriodKey.hpp.
Referenced by stdair::DatePeriod::getDatePeriod().
void stdair::DatePeriodKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 36 of file DatePeriodKey.cpp.
References toString().
void stdair::DatePeriodKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 41 of file DatePeriodKey.cpp.
const std::string stdair::DatePeriodKey::toString () const virtual
Get the serialised version of the Business Object Key. That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
Reimplemented from stdair::KeyAbstract.
Definition at line 45 of file DatePeriodKey.cpp.
Referenced by stdair::DatePeriod::describeKey(), and toStream().
The documentation for this struct was generated from the following files:
stdair/bom/DatePeriodKey.hpp
stdair/bom/DatePeriodKey.cpp