stdair::FareFeaturesKey Struct Reference
stdair::FareFeaturesKey Struct Reference
Key of date-period.
#include <stdair/bom/FareFeaturesKey.hpp>
Public Member Functions
FareFeaturesKey (const TripType_T &, const DayDuration_T &, const SaturdayStay_T &, const ChangeFees_T &, const NonRefundable_T &, const DayDuration_T &)
FareFeaturesKey (const FareFeaturesKey &)
~FareFeaturesKey ()
const TripType_T & getTripType () const
const DayDuration_T & getAdvancePurchase () const
const SaturdayStay_T & getSaturdayStay () const
const ChangeFees_T & getChangeFees () const
const NonRefundable_T & getRefundableOption () const
const DayDuration_T & getMinimumStay () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
Detailed Description
Key of date-period.
Definition at line 18 of file FareFeaturesKey.hpp.
Constructor & Destructor Documentation
stdair::FareFeaturesKey::FareFeaturesKey (const TripType_T & iTripType, const DayDuration_T & iAdvancePurchase, const SaturdayStay_T & iSaturdayStay, const ChangeFees_T & iChangeFees, const NonRefundable_T & iNonRefundable, const DayDuration_T & iMinimumStay)
Main constructor.
Definition at line 26 of file FareFeaturesKey.cpp.
stdair::FareFeaturesKey::FareFeaturesKey (const FareFeaturesKey & iKey)
Copy constructor.
Definition at line 38 of file FareFeaturesKey.cpp.
stdair::FareFeaturesKey::~FareFeaturesKey ()
Destructor.
Definition at line 48 of file FareFeaturesKey.cpp.
Member Function Documentation
const TripType_T& stdair::FareFeaturesKey::getTripType () const inline
Get the fare trip type.
Definition at line 39 of file FareFeaturesKey.hpp.
Referenced by stdair::FareFeatures::getTripType().
const DayDuration_T& stdair::FareFeaturesKey::getAdvancePurchase () const inline
Get the fare day duration.
Definition at line 46 of file FareFeaturesKey.hpp.
Referenced by stdair::FareFeatures::getAdvancePurchase().
const SaturdayStay_T& stdair::FareFeaturesKey::getSaturdayStay () const inline
Get the fare saturday stay option.
Definition at line 53 of file FareFeaturesKey.hpp.
Referenced by stdair::FareFeatures::getSaturdayStay().
const ChangeFees_T& stdair::FareFeaturesKey::getChangeFees () const inline
Get the change fees criterion.
Definition at line 60 of file FareFeaturesKey.hpp.
Referenced by stdair::FareFeatures::getChangeFees().
const NonRefundable_T& stdair::FareFeaturesKey::getRefundableOption () const inline
Get the refundable option.
Definition at line 67 of file FareFeaturesKey.hpp.
Referenced by stdair::FareFeatures::getRefundableOption().
const DayDuration_T& stdair::FareFeaturesKey::getMinimumStay () const inline
Get the minimum stay.
Definition at line 74 of file FareFeaturesKey.hpp.
Referenced by stdair::FareFeatures::getMinimumStay().
void stdair::FareFeaturesKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 52 of file FareFeaturesKey.cpp.
References toString().
void stdair::FareFeaturesKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 57 of file FareFeaturesKey.cpp.
const std::string stdair::FareFeaturesKey::toString () const virtual
Get the serialised version of the Business Object Key. That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
Reimplemented from stdair::KeyAbstract.
Definition at line 61 of file FareFeaturesKey.cpp.
Referenced by stdair::FareFeatures::describeKey(), and toStream().
The documentation for this struct was generated from the following files:
stdair/bom/FareFeaturesKey.hpp
stdair/bom/FareFeaturesKey.cpp