stdair::FacSTDAIRServiceContext Class Reference
stdair::FacSTDAIRServiceContext Class Reference
Factory for Bucket.
#include <stdair/service/FacSTDAIRServiceContext.hpp>
Public Types
typedef std::vector< ServiceAbstract * > ServicePool_T
Public Member Functions
~FacSTDAIRServiceContext ()
STDAIR_ServiceContext & create ()
void clean ()
Static Public Member Functions
static FacSTDAIRServiceContext & instance ()
Protected Member Functions
FacSTDAIRServiceContext ()
Protected Attributes
ServicePool_T _pool
Detailed Description
Factory for Bucket.
Definition at line 18 of file FacSTDAIRServiceContext.hpp.
Member Typedef Documentation
typedef std::vector<ServiceAbstract*> stdair::FacServiceAbstract::ServicePool_T inherited
Define the list (pool) of Service objects.
Definition at line 20 of file FacServiceAbstract.hpp.
Constructor & Destructor Documentation
stdair::FacSTDAIRServiceContext::~FacSTDAIRServiceContext ()
Destructor.
The Destruction put the _instance to NULL in order to be clean for the next FacSTDAIRServiceContext::instance().
Definition at line 16 of file FacSTDAIRServiceContext.cpp.
stdair::FacSTDAIRServiceContext::FacSTDAIRServiceContext () inline protected
Default Constructor.
This constructor is protected in order to ensure the singleton pattern.
Definition at line 54 of file FacSTDAIRServiceContext.hpp.
Referenced by instance().
Member Function Documentation
FacSTDAIRServiceContext & stdair::FacSTDAIRServiceContext::instance () static
Provide the unique instance.
The singleton is instantiated when first used.
Returns
FacSTDAIRServiceContext&
Definition at line 21 of file FacSTDAIRServiceContext.cpp.
References FacSTDAIRServiceContext(), stdair::FacSupervisor::instance(), and stdair::FacSupervisor::registerServiceFactory().
STDAIR_ServiceContext & stdair::FacSTDAIRServiceContext::create ()
Create a new STDAIR_ServiceContext object.
This new object is added to the list of instantiated objects.
Returns
STDAIR_ServiceContext& The newly created object.
Definition at line 33 of file FacSTDAIRServiceContext.cpp.
References stdair::FacServiceAbstract::_pool.
void stdair::FacServiceAbstract::clean () inherited
Destroyed all the object instantiated by this factory.
Definition at line 18 of file FacServiceAbstract.cpp.
References stdair::FacServiceAbstract::_pool.
Referenced by stdair::FacServiceAbstract::~FacServiceAbstract().
Member Data Documentation
ServicePool_T stdair::FacServiceAbstract::_pool protected inherited
List of instantiated Business Objects
Definition at line 34 of file FacServiceAbstract.hpp.
Referenced by stdair::FacServiceAbstract::clean(), and create().
The documentation for this class was generated from the following files:
stdair/service/FacSTDAIRServiceContext.hpp
stdair/service/FacSTDAIRServiceContext.cpp