stdair::FFDisutilityCurveHolderStruct Struct Reference
stdair::FFDisutilityCurveHolderStruct Struct Reference
#include <stdair/bom/FFDisutilityCurveHolderStruct.hpp>
Public Member Functions
const FFDisutilityCurve_T & getFFDisutilityCurve (const std::string &) const
void addCurve (const std::string &, const FFDisutilityCurve_T &)
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string describe () const
FFDisutilityCurveHolderStruct ()
FFDisutilityCurveHolderStruct (const FFDisutilityCurveHolderStruct &)
~FFDisutilityCurveHolderStruct ()
Detailed Description
Structure holding the elements of a snapshot .
Definition at line 19 of file FFDisutilityCurveHolderStruct.hpp.
Constructor & Destructor Documentation
stdair::FFDisutilityCurveHolderStruct::FFDisutilityCurveHolderStruct ()
Constructor.
Definition at line 14 of file FFDisutilityCurveHolderStruct.cpp.
stdair::FFDisutilityCurveHolderStruct::FFDisutilityCurveHolderStruct (const FFDisutilityCurveHolderStruct & iHolder)
Copy constructor.
Definition at line 19 of file FFDisutilityCurveHolderStruct.cpp.
stdair::FFDisutilityCurveHolderStruct::~FFDisutilityCurveHolderStruct ()
Destructor.
Definition at line 24 of file FFDisutilityCurveHolderStruct.cpp.
Member Function Documentation
const FFDisutilityCurve_T & stdair::FFDisutilityCurveHolderStruct::getFFDisutilityCurve (const std::string & iKey) const
Get the FFDisutility curve corresponding to the given key.
Definition at line 29 of file FFDisutilityCurveHolderStruct.cpp.
References STDAIR_LOG_DEBUG.
Referenced by stdair::BomRoot::getFFDisutilityCurve().
void stdair::FFDisutilityCurveHolderStruct::addCurve (const std::string & iKey, const FFDisutilityCurve_T & iCurve)
Add a new curve to the holder.
Definition at line 42 of file FFDisutilityCurveHolderStruct.cpp.
References STDAIR_LOG_DEBUG.
Referenced by stdair::BomRoot::addFFDisutilityCurve().
void stdair::FFDisutilityCurveHolderStruct::toStream (std::ostream & ioOut) const
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 53 of file FFDisutilityCurveHolderStruct.cpp.
References describe().
void stdair::FFDisutilityCurveHolderStruct::fromStream (std::istream & ioIn) virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::StructAbstract.
Definition at line 58 of file FFDisutilityCurveHolderStruct.cpp.
const std::string stdair::FFDisutilityCurveHolderStruct::describe () const virtual
Display of the structure.
Implements stdair::StructAbstract.
Definition at line 62 of file FFDisutilityCurveHolderStruct.cpp.
Referenced by toStream().
The documentation for this struct was generated from the following files:
stdair/bom/FFDisutilityCurveHolderStruct.hpp
stdair/bom/FFDisutilityCurveHolderStruct.cpp