stdair::ServiceInitialisationType Struct Reference
stdair::ServiceInitialisationType Struct Reference
Enumeration of service initialisation types.
#include <stdair/basic/ServiceInitialisationType.hpp>
Public Types
enum EN_ServiceInitialisationType { NOT_YET_INITIALISED = 0, FILE_PARSING, BUILTIN_SAMPLE, LAST_VALUE }
Public Member Functions
EN_ServiceInitialisationType getType () const
char getTypeAsChar () const
std::string getTypeAsString () const
const std::string describe () const
bool operator== (const EN_ServiceInitialisationType &) const
ServiceInitialisationType (const EN_ServiceInitialisationType &)
ServiceInitialisationType (const char iType)
ServiceInitialisationType (const std::string &iType)
ServiceInitialisationType (const ServiceInitialisationType &)
void toStream (std::ostream &ioOut) const
virtual void fromStream (std::istream &ioIn)
Static Public Member Functions
static const std::string & getLabel (const EN_ServiceInitialisationType &)
static EN_ServiceInitialisationType getType (const char)
static char getTypeLabel (const EN_ServiceInitialisationType &)
static std::string getTypeLabelAsString (const EN_ServiceInitialisationType &)
static std::string describeLabels ()
Detailed Description
Enumeration of service initialisation types.
Definition at line 17 of file ServiceInitialisationType.hpp.
Member Enumeration Documentation
enum stdair::ServiceInitialisationType::EN_ServiceInitialisationType
Enumerator
NOT_YET_INITIALISED
FILE_PARSING
BUILTIN_SAMPLE
LAST_VALUE
Definition at line 19 of file ServiceInitialisationType.hpp.
Constructor & Destructor Documentation
stdair::ServiceInitialisationType::ServiceInitialisationType (const EN_ServiceInitialisationType & iServiceInitialisationType)
Main constructor.
Definition at line 36 of file ServiceInitialisationType.cpp.
stdair::ServiceInitialisationType::ServiceInitialisationType (const char iType)
Alternative constructor.
Definition at line 65 of file ServiceInitialisationType.cpp.
stdair::ServiceInitialisationType::ServiceInitialisationType (const std::string & iType)
Alternative constructor.
Definition at line 71 of file ServiceInitialisationType.cpp.
References getType().
stdair::ServiceInitialisationType::ServiceInitialisationType (const ServiceInitialisationType & iServiceInitialisationType)
Default copy constructor.
Definition at line 30 of file ServiceInitialisationType.cpp.
Member Function Documentation
const std::string & stdair::ServiceInitialisationType::getLabel (const EN_ServiceInitialisationType & iType) static
Get the label as a string (e.g., "Not yet initialised", "File parsing" or "Built-in sample BOM").
Definition at line 81 of file ServiceInitialisationType.cpp.
ServiceInitialisationType::EN_ServiceInitialisationType stdair::ServiceInitialisationType::getType (const char iTypeChar) static
Get the type value from parsing a single char (e.g., 'N', 'F', 'B').
Definition at line 42 of file ServiceInitialisationType.cpp.
References BUILTIN_SAMPLE, describeLabels(), FILE_PARSING, LAST_VALUE, and NOT_YET_INITIALISED.
char stdair::ServiceInitialisationType::getTypeLabel (const EN_ServiceInitialisationType & iType) static
Get the label as a single char (e.g., 'N', 'F', 'B').
Definition at line 87 of file ServiceInitialisationType.cpp.
std::string stdair::ServiceInitialisationType::getTypeLabelAsString (const EN_ServiceInitialisationType & iType) static
Get the label as a string of a single char (e.g., "N", "F", "B").
Definition at line 93 of file ServiceInitialisationType.cpp.
std::string stdair::ServiceInitialisationType::describeLabels () static
List the labels.
Definition at line 100 of file ServiceInitialisationType.cpp.
References LAST_VALUE.
Referenced by getType().
ServiceInitialisationType::EN_ServiceInitialisationType stdair::ServiceInitialisationType::getType () const
Get the enumerated value.
Definition at line 113 of file ServiceInitialisationType.cpp.
Referenced by ServiceInitialisationType().
char stdair::ServiceInitialisationType::getTypeAsChar () const
Get the enumerated value as a short string (e.g., 'N', 'F', 'B').
Definition at line 118 of file ServiceInitialisationType.cpp.
std::string stdair::ServiceInitialisationType::getTypeAsString () const
Get the enumerated value as a short string (e.g., "N", "F", "B").
Definition at line 124 of file ServiceInitialisationType.cpp.
const std::string stdair::ServiceInitialisationType::describe () const virtual
Give a description of the structure (e.g., "Not yet initialised", "File parsing" or "Built-in sample BOM").
Implements stdair::StructAbstract.
Definition at line 131 of file ServiceInitialisationType.cpp.
bool stdair::ServiceInitialisationType::operator== (const EN_ServiceInitialisationType & iType) const
Comparison operator.
Definition at line 139 of file ServiceInitialisationType.cpp.
void stdair::StructAbstract::toStream (std::ostream & ioOut) const inline inherited
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 29 of file StructAbstract.hpp.
References stdair::StructAbstract::describe().
virtual void stdair::StructAbstract::fromStream (std::istream & ioIn) inline virtual inherited
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented in stdair::BookingRequestStruct, stdair::EventStruct, stdair::TravelSolutionStruct, stdair::VirtualClassStruct, stdair::ConfigHolderStruct, stdair::FareOptionStruct, stdair::OptimisationNotificationStruct, stdair::ProgressStatusSet, stdair::YieldRange, stdair::CancellationStruct, stdair::AirlineStruct, stdair::RMEventStruct, stdair::SnapshotStruct, stdair::FFDisutilityCurveHolderStruct, stdair::FRAT5CurveHolderStruct, and stdair::BreakPointStruct.
Definition at line 38 of file StructAbstract.hpp.
Referenced by operator>>().
The documentation for this struct was generated from the following files:
stdair/basic/ServiceInitialisationType.hpp
stdair/basic/ServiceInitialisationType.cpp