stdair::FareFamilyKey Struct Reference
stdair::FareFamilyKey Struct Reference
Key of a given fare family, made of a fare family code.
#include <stdair/bom/FareFamilyKey.hpp>
Public Member Functions
FareFamilyKey (const FamilyCode_T &iFamilyCode)
FareFamilyKey (const FareFamilyKey &)
~FareFamilyKey ()
const FamilyCode_T & getFamilyCode () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
template<class Archive >
void serialize (Archive &ar, const unsigned int iFileVersion)
Friends
class boost::serialization::access
Detailed Description
Key of a given fare family, made of a fare family code.
Definition at line 26 of file FareFamilyKey.hpp.
Constructor & Destructor Documentation
stdair::FareFamilyKey::FareFamilyKey (const FamilyCode_T & iFamilyCode)
Constructor.
Definition at line 28 of file FareFamilyKey.cpp.
stdair::FareFamilyKey::FareFamilyKey (const FareFamilyKey & iFareFamilyKey)
Copy constructor.
Definition at line 23 of file FareFamilyKey.cpp.
stdair::FareFamilyKey::~FareFamilyKey ()
Destructor.
Definition at line 33 of file FareFamilyKey.cpp.
Member Function Documentation
const FamilyCode_T& stdair::FareFamilyKey::getFamilyCode () const inline
Get the family code.
Definition at line 56 of file FareFamilyKey.hpp.
Referenced by stdair::FareFamily::getFamilyCode().
void stdair::FareFamilyKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 37 of file FareFamilyKey.cpp.
References toString().
void stdair::FareFamilyKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 42 of file FareFamilyKey.cpp.
const std::string stdair::FareFamilyKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-date.
Reimplemented from stdair::KeyAbstract.
Definition at line 46 of file FareFamilyKey.cpp.
Referenced by stdair::FareFamily::describeKey(), and toStream().
template<class Archive > void stdair::FareFamilyKey::serialize (Archive & ar, const unsigned int iFileVersion)
Serialisation.
Definition at line 68 of file FareFamilyKey.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 27 of file FareFamilyKey.hpp.
The documentation for this struct was generated from the following files:
stdair/bom/FareFamilyKey.hpp
stdair/bom/FareFamilyKey.cpp