stdair::EventType Struct Reference
stdair::EventType Struct Reference
#include <stdair/basic/EventType.hpp>
Public Types
enum EN_EventType {
BKG_REQ = 0, CX, OPT_NOT_4_FD, OPT_NOT_4_NET,
SKD_CHG, SNAPSHOT, RM, BRK_PT,
LAST_VALUE
}
Public Member Functions
EN_EventType getType () const
std::string getTypeAsString () const
const std::string describe () const
bool operator== (const EN_EventType &) const
EventType (const EN_EventType &)
EventType (const char iType)
EventType (const std::string &iTypeStr)
EventType (const EventType &)
void toStream (std::ostream &ioOut) const
virtual void fromStream (std::istream &ioIn)
Static Public Member Functions
static const std::string & getLabel (const EN_EventType &)
static char getTypeLabel (const EN_EventType &)
static std::string getTypeLabelAsString (const EN_EventType &)
static std::string describeLabels ()
Detailed Description
Enumeration of event types.
Definition at line 15 of file EventType.hpp.
Member Enumeration Documentation
enum stdair::EventType::EN_EventType
Enumerator
BKG_REQ
CX
OPT_NOT_4_FD
OPT_NOT_4_NET
SKD_CHG
SNAPSHOT
RM
BRK_PT
LAST_VALUE
Definition at line 17 of file EventType.hpp.
Constructor & Destructor Documentation
stdair::EventType::EventType (const EN_EventType & iEventType)
Constructor.
Definition at line 36 of file EventType.cpp.
stdair::EventType::EventType (const char iType)
Constructor using a char.
Definition at line 41 of file EventType.cpp.
References BKG_REQ, BRK_PT, CX, describeLabels(), LAST_VALUE, OPT_NOT_4_FD, OPT_NOT_4_NET, RM, SKD_CHG, and SNAPSHOT.
stdair::EventType::EventType (const std::string & iTypeStr)
Constructor using a string.
Definition at line 64 of file EventType.cpp.
References describeLabels(), and LAST_VALUE.
stdair::EventType::EventType (const EventType & iEventType)
Default copy constructor.
Definition at line 31 of file EventType.cpp.
Member Function Documentation
const std::string & stdair::EventType::getLabel (const EN_EventType & iType) static
Get the label as a string (e.g., "BookingRequest", "Cancellation", "OptimisationNotificationForFlightDate", "OptimisationNotificationForNetwork", "ScheduleChange", "Snapshot", "RevenueManagement", "BreakPoint" or "BookingRequest").
Definition at line 83 of file EventType.cpp.
Referenced by stdair::EventStruct::describe(), stdair::BomJSONExport::jsonExportBookingRequestObject(), and stdair::BomJSONExport::jsonExportBreakPointObject().
char stdair::EventType::getTypeLabel (const EN_EventType & iType) static
Get the label as a single char (e.g., 'B', 'X', 'F', 'N', 'C', 'S', 'R' or 'P').
Definition at line 88 of file EventType.cpp.
std::string stdair::EventType::getTypeLabelAsString (const EN_EventType & iType) static
Get the label as a string of a single char (e.g., "B", "X", "F", "N", "C", "S", "R" or "P").
Definition at line 93 of file EventType.cpp.
std::string stdair::EventType::describeLabels () static
List the labels.
Definition at line 100 of file EventType.cpp.
References LAST_VALUE.
Referenced by EventType().
EventType::EN_EventType stdair::EventType::getType () const
Get the enumerated value.
Definition at line 112 of file EventType.cpp.
std::string stdair::EventType::getTypeAsString () const
Get the enumerated value as a short string (e.g., "B", "X", "F", "N", "C", "S", "R" or "P").
Definition at line 117 of file EventType.cpp.
const std::string stdair::EventType::describe () const virtual
Give a description of the structure (e.g., "BookingRequest", "Cancellation", "OptimisationNotificationForFlightDate", "OptimisationNotificationForNetwork", "ScheduleChange", "Snapshot", "RevenueManagement", "BreakPoint" or "BookingRequest").
Implements stdair::StructAbstract.
Definition at line 124 of file EventType.cpp.
bool stdair::EventType::operator== (const EN_EventType & iType) const
Comparison operator.
Definition at line 131 of file EventType.cpp.
void stdair::StructAbstract::toStream (std::ostream & ioOut) const inline inherited
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 29 of file StructAbstract.hpp.
References stdair::StructAbstract::describe().
virtual void stdair::StructAbstract::fromStream (std::istream & ioIn) inline virtual inherited
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented in stdair::BookingRequestStruct, stdair::EventStruct, stdair::TravelSolutionStruct, stdair::VirtualClassStruct, stdair::ConfigHolderStruct, stdair::FareOptionStruct, stdair::OptimisationNotificationStruct, stdair::ProgressStatusSet, stdair::YieldRange, stdair::CancellationStruct, stdair::AirlineStruct, stdair::RMEventStruct, stdair::SnapshotStruct, stdair::FFDisutilityCurveHolderStruct, stdair::FRAT5CurveHolderStruct, and stdair::BreakPointStruct.
Definition at line 38 of file StructAbstract.hpp.
Referenced by operator>>().
The documentation for this struct was generated from the following files:
stdair/basic/EventType.hpp
stdair/basic/EventType.cpp