stdair::DemandGenerationMethod Struct Reference
stdair::DemandGenerationMethod Struct Reference
Enumeration of demand (booking request) generation methods.
#include <stdair/basic/DemandGenerationMethod.hpp>
Public Types
enum EN_DemandGenerationMethod { POI_PRO = 0, STA_ORD, LAST_VALUE }
Public Member Functions
EN_DemandGenerationMethod getMethod () const
char getMethodAsChar () const
std::string getMethodAsString () const
const std::string describe () const
bool operator== (const EN_DemandGenerationMethod &) const
DemandGenerationMethod (const EN_DemandGenerationMethod &)
DemandGenerationMethod (const char iMethod)
DemandGenerationMethod (const std::string &iMethod)
DemandGenerationMethod (const DemandGenerationMethod &)
void toStream (std::ostream &ioOut) const
virtual void fromStream (std::istream &ioIn)
Static Public Member Functions
static const std::string & getLabel (const EN_DemandGenerationMethod &)
static EN_DemandGenerationMethod getMethod (const char)
static char getMethodLabel (const EN_DemandGenerationMethod &)
static std::string getMethodLabelAsString (const EN_DemandGenerationMethod &)
static std::string describeLabels ()
Detailed Description
Enumeration of demand (booking request) generation methods.
Definition at line 17 of file DemandGenerationMethod.hpp.
Member Enumeration Documentation
enum stdair::DemandGenerationMethod::EN_DemandGenerationMethod
Enumerator
POI_PRO
STA_ORD
LAST_VALUE
Definition at line 19 of file DemandGenerationMethod.hpp.
Constructor & Destructor Documentation
stdair::DemandGenerationMethod::DemandGenerationMethod (const EN_DemandGenerationMethod & iDemandGenerationMethod)
Main constructor.
Definition at line 34 of file DemandGenerationMethod.cpp.
stdair::DemandGenerationMethod::DemandGenerationMethod (const char iMethod)
Alternative constructor.
Definition at line 62 of file DemandGenerationMethod.cpp.
stdair::DemandGenerationMethod::DemandGenerationMethod (const std::string & iMethod)
Alternative constructor.
Definition at line 68 of file DemandGenerationMethod.cpp.
References getMethod().
stdair::DemandGenerationMethod::DemandGenerationMethod (const DemandGenerationMethod & iDemandGenerationMethod)
Default copy constructor.
Definition at line 28 of file DemandGenerationMethod.cpp.
Member Function Documentation
const std::string & stdair::DemandGenerationMethod::getLabel (const EN_DemandGenerationMethod & iMethod) static
Get the label as a string (e.g., "PoissonProcess" or "StatisticsOrder").
Definition at line 78 of file DemandGenerationMethod.cpp.
DemandGenerationMethod::EN_DemandGenerationMethod stdair::DemandGenerationMethod::getMethod (const char iMethodChar) static
Get the method value from parsing a single char (e.g., 'P' or 'S').
Definition at line 40 of file DemandGenerationMethod.cpp.
References describeLabels(), LAST_VALUE, POI_PRO, and STA_ORD.
char stdair::DemandGenerationMethod::getMethodLabel (const EN_DemandGenerationMethod & iMethod) static
Get the label as a single char (e.g., 'P' or 'S').
Definition at line 84 of file DemandGenerationMethod.cpp.
std::string stdair::DemandGenerationMethod::getMethodLabelAsString (const EN_DemandGenerationMethod & iMethod) static
Get the label as a string of a single char (e.g., "P" or "S").
Definition at line 90 of file DemandGenerationMethod.cpp.
std::string stdair::DemandGenerationMethod::describeLabels () static
List the labels.
Definition at line 97 of file DemandGenerationMethod.cpp.
References LAST_VALUE.
Referenced by getMethod().
DemandGenerationMethod::EN_DemandGenerationMethod stdair::DemandGenerationMethod::getMethod () const
Get the enumerated value.
Definition at line 110 of file DemandGenerationMethod.cpp.
Referenced by DemandGenerationMethod().
char stdair::DemandGenerationMethod::getMethodAsChar () const
Get the enumerated value as a short string (e.g., 'P' or 'S').
Definition at line 115 of file DemandGenerationMethod.cpp.
std::string stdair::DemandGenerationMethod::getMethodAsString () const
Get the enumerated value as a short string (e.g., "P" or "S").
Definition at line 121 of file DemandGenerationMethod.cpp.
const std::string stdair::DemandGenerationMethod::describe () const virtual
Give a description of the structure (e.g., "PoissonProcess" or "SatisticsOrder").
Implements stdair::StructAbstract.
Definition at line 128 of file DemandGenerationMethod.cpp.
bool stdair::DemandGenerationMethod::operator== (const EN_DemandGenerationMethod & iMethod) const
Comparison operator.
Definition at line 136 of file DemandGenerationMethod.cpp.
void stdair::StructAbstract::toStream (std::ostream & ioOut) const inline inherited
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 29 of file StructAbstract.hpp.
References stdair::StructAbstract::describe().
virtual void stdair::StructAbstract::fromStream (std::istream & ioIn) inline virtual inherited
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented in stdair::BookingRequestStruct, stdair::EventStruct, stdair::TravelSolutionStruct, stdair::VirtualClassStruct, stdair::ConfigHolderStruct, stdair::FareOptionStruct, stdair::OptimisationNotificationStruct, stdair::ProgressStatusSet, stdair::YieldRange, stdair::CancellationStruct, stdair::AirlineStruct, stdair::RMEventStruct, stdair::SnapshotStruct, stdair::FFDisutilityCurveHolderStruct, stdair::FRAT5CurveHolderStruct, and stdair::BreakPointStruct.
Definition at line 38 of file StructAbstract.hpp.
Referenced by operator>>().
The documentation for this struct was generated from the following files:
stdair/basic/DemandGenerationMethod.hpp
stdair/basic/DemandGenerationMethod.cpp