stdair::PolicyKey Struct Reference
stdair::PolicyKey Struct Reference
Key of a given policy, made of a policy code.
#include <stdair/bom/PolicyKey.hpp>
Public Member Functions
PolicyKey (const PolicyCode_T &iPolicyCode)
PolicyKey (const PolicyKey &)
~PolicyKey ()
const PolicyCode_T & getPolicyCode () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
template<class Archive >
void serialize (Archive &ar, const unsigned int iFileVersion)
Friends
class boost::serialization::access
Detailed Description
Key of a given policy, made of a policy code.
Definition at line 26 of file PolicyKey.hpp.
Constructor & Destructor Documentation
stdair::PolicyKey::PolicyKey (const PolicyCode_T & iPolicyCode)
Constructor.
Definition at line 28 of file PolicyKey.cpp.
stdair::PolicyKey::PolicyKey (const PolicyKey & iPolicyKey)
Copy constructor.
Definition at line 23 of file PolicyKey.cpp.
stdair::PolicyKey::~PolicyKey ()
Destructor.
Definition at line 33 of file PolicyKey.cpp.
Member Function Documentation
const PolicyCode_T& stdair::PolicyKey::getPolicyCode () const inline
Get the policy code.
Definition at line 56 of file PolicyKey.hpp.
void stdair::PolicyKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 37 of file PolicyKey.cpp.
References toString().
void stdair::PolicyKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 42 of file PolicyKey.cpp.
const std::string stdair::PolicyKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-date.
Reimplemented from stdair::KeyAbstract.
Definition at line 46 of file PolicyKey.cpp.
Referenced by stdair::Policy::describeKey(), and toStream().
template<class Archive > void stdair::PolicyKey::serialize (Archive & ar, const unsigned int iFileVersion)
Serialisation.
Definition at line 68 of file PolicyKey.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 27 of file PolicyKey.hpp.
The documentation for this struct was generated from the following files:
stdair/bom/PolicyKey.hpp
stdair/bom/PolicyKey.cpp