stdair::FlightDateKey Struct Reference
stdair::FlightDateKey Struct Reference
Key of a given flight-date, made of a flight number and a departure date.
#include <stdair/bom/FlightDateKey.hpp>
Public Member Functions
FlightDateKey (const FlightNumber_T &, const Date_T &)
FlightDateKey (const FlightDateKey &)
~FlightDateKey ()
const FlightNumber_T & getFlightNumber () const
const Date_T & getDepartureDate () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
template<class Archive >
void serialize (Archive &ar, const unsigned int iFileVersion)
Friends
class boost::serialization::access
Detailed Description
Key of a given flight-date, made of a flight number and a departure date.
Definition at line 28 of file FlightDateKey.hpp.
Constructor & Destructor Documentation
stdair::FlightDateKey::FlightDateKey (const FlightNumber_T & iFlightNumber, const Date_T & iFlightDate)
Constructor.
Definition at line 28 of file FlightDateKey.cpp.
stdair::FlightDateKey::FlightDateKey (const FlightDateKey & iKey)
Copy constructor.
Definition at line 34 of file FlightDateKey.cpp.
stdair::FlightDateKey::~FlightDateKey ()
Destructor.
Definition at line 39 of file FlightDateKey.cpp.
Member Function Documentation
const FlightNumber_T& stdair::FlightDateKey::getFlightNumber () const inline
Get the flight number.
Definition at line 58 of file FlightDateKey.hpp.
Referenced by stdair::FlightDate::getFlightNumber().
const Date_T& stdair::FlightDateKey::getDepartureDate () const inline
Get the departure date of the (first leg of the) flight.
Definition at line 63 of file FlightDateKey.hpp.
Referenced by stdair::OnDDateKey::getDate(), and stdair::FlightDate::getDepartureDate().
void stdair::FlightDateKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 43 of file FlightDateKey.cpp.
References toString().
void stdair::FlightDateKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 48 of file FlightDateKey.cpp.
const std::string stdair::FlightDateKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-date.
Reimplemented from stdair::KeyAbstract.
Definition at line 52 of file FlightDateKey.cpp.
References stdair::DEFAULT_KEY_SUB_FLD_DELIMITER.
Referenced by stdair::FlightDate::describeKey(), stdair::Inventory::getFlightDate(), stdair::BomRetriever::retrieveSegmentDateFromLongKey(), and toStream().
template<class Archive > void stdair::FlightDateKey::serialize (Archive & ar, const unsigned int iFileVersion)
Serialisation.
Definition at line 77 of file FlightDateKey.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 29 of file FlightDateKey.hpp.
The documentation for this struct was generated from the following files:
stdair/bom/FlightDateKey.hpp
stdair/bom/FlightDateKey.cpp