stdair::NestingNodeKey Struct Reference
stdair::NestingNodeKey Struct Reference
Key of a given policy, made of a policy code.
#include <stdair/bom/NestingNodeKey.hpp>
Public Member Functions
NestingNodeKey (const NestingNodeCode_T &iNestingNodeCode)
NestingNodeKey (const NestingNodeKey &)
~NestingNodeKey ()
const NestingNodeCode_T & getNestingNodeCode () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
template<class Archive >
void serialize (Archive &ar, const unsigned int iFileVersion)
Friends
class boost::serialization::access
Detailed Description
Key of a given policy, made of a policy code.
Definition at line 26 of file NestingNodeKey.hpp.
Constructor & Destructor Documentation
stdair::NestingNodeKey::NestingNodeKey (const NestingNodeCode_T & iNestingNodeCode)
Constructor.
Definition at line 28 of file NestingNodeKey.cpp.
stdair::NestingNodeKey::NestingNodeKey (const NestingNodeKey & iNestingNodeKey)
Copy constructor.
Definition at line 23 of file NestingNodeKey.cpp.
stdair::NestingNodeKey::~NestingNodeKey ()
Destructor.
Definition at line 33 of file NestingNodeKey.cpp.
Member Function Documentation
const NestingNodeCode_T& stdair::NestingNodeKey::getNestingNodeCode () const inline
Get the policy code.
Definition at line 56 of file NestingNodeKey.hpp.
void stdair::NestingNodeKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 37 of file NestingNodeKey.cpp.
References toString().
void stdair::NestingNodeKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 42 of file NestingNodeKey.cpp.
const std::string stdair::NestingNodeKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-date.
Reimplemented from stdair::KeyAbstract.
Definition at line 46 of file NestingNodeKey.cpp.
Referenced by stdair::NestingNode::describeKey(), and toStream().
template<class Archive > void stdair::NestingNodeKey::serialize (Archive & ar, const unsigned int iFileVersion)
Serialisation.
Definition at line 68 of file NestingNodeKey.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 27 of file NestingNodeKey.hpp.
The documentation for this struct was generated from the following files:
stdair/bom/NestingNodeKey.hpp
stdair/bom/NestingNodeKey.cpp