stdair::InventoryKey Struct Reference
stdair::InventoryKey Struct Reference
Key of a given inventory, made of the airline code.
#include <stdair/bom/InventoryKey.hpp>
Public Member Functions
InventoryKey (const AirlineCode_T &iAirlineCode)
InventoryKey (const InventoryKey &)
~InventoryKey ()
const AirlineCode_T & getAirlineCode () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
template<class Archive >
void serialize (Archive &ar, const unsigned int iFileVersion)
Friends
class boost::serialization::access
Detailed Description
Key of a given inventory, made of the airline code.
Definition at line 26 of file InventoryKey.hpp.
Constructor & Destructor Documentation
stdair::InventoryKey::InventoryKey (const AirlineCode_T & iAirlineCode)
Constructor.
Definition at line 23 of file InventoryKey.cpp.
stdair::InventoryKey::InventoryKey (const InventoryKey & iKey)
Copy constructor.
Definition at line 28 of file InventoryKey.cpp.
stdair::InventoryKey::~InventoryKey ()
Destructor.
Definition at line 33 of file InventoryKey.cpp.
Member Function Documentation
const AirlineCode_T& stdair::InventoryKey::getAirlineCode () const inline
Get the airline code.
Definition at line 58 of file InventoryKey.hpp.
Referenced by stdair::Inventory::getAirlineCode(), stdair::BomRetriever::retrieveInventoryFromLongKey(), and stdair::BomRetriever::retrievePartnerSegmentDateFromLongKey().
void stdair::InventoryKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 37 of file InventoryKey.cpp.
References toString().
void stdair::InventoryKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 42 of file InventoryKey.cpp.
const std::string stdair::InventoryKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-date.
Reimplemented from stdair::KeyAbstract.
Definition at line 46 of file InventoryKey.cpp.
Referenced by stdair::Inventory::describeKey(), stdair::BomRoot::getInventory(), and toStream().
template<class Archive > void stdair::InventoryKey::serialize (Archive & ar, const unsigned int iFileVersion)
Serialisation.
Definition at line 68 of file InventoryKey.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 27 of file InventoryKey.hpp.
The documentation for this struct was generated from the following files:
stdair/bom/InventoryKey.hpp
stdair/bom/InventoryKey.cpp