stdair::OptimisationMethod Struct Reference
stdair::OptimisationMethod Struct Reference
#include <stdair/basic/OptimisationMethod.hpp>
Public Types
enum EN_OptimisationMethod { LEG_BASED_MC = 0, LEG_BASED_EMSR_B, LAST_VALUE }
Public Member Functions
EN_OptimisationMethod getMethod () const
std::string getMethodAsString () const
const std::string describe () const
bool operator== (const EN_OptimisationMethod &) const
OptimisationMethod (const EN_OptimisationMethod &)
OptimisationMethod (const char iMethod)
OptimisationMethod (const OptimisationMethod &)
void toStream (std::ostream &ioOut) const
virtual void fromStream (std::istream &ioIn)
Static Public Member Functions
static const std::string & getLabel (const EN_OptimisationMethod &)
static char getMethodLabel (const EN_OptimisationMethod &)
static std::string getMethodLabelAsString (const EN_OptimisationMethod &)
static std::string describeLabels ()
Detailed Description
Enumeration of Optimisation methods.
Definition at line 15 of file OptimisationMethod.hpp.
Member Enumeration Documentation
enum stdair::OptimisationMethod::EN_OptimisationMethod
Enumerator
LEG_BASED_MC
LEG_BASED_EMSR_B
LAST_VALUE
Definition at line 17 of file OptimisationMethod.hpp.
Constructor & Destructor Documentation
stdair::OptimisationMethod::OptimisationMethod (const EN_OptimisationMethod & iOptimisationMethod)
Constructor.
Definition at line 36 of file OptimisationMethod.cpp.
stdair::OptimisationMethod::OptimisationMethod (const char iMethod)
Constructor.
Definition at line 41 of file OptimisationMethod.cpp.
References describeLabels(), LAST_VALUE, LEG_BASED_EMSR_B, and LEG_BASED_MC.
stdair::OptimisationMethod::OptimisationMethod (const OptimisationMethod & iOptimisationMethod)
Default copy constructor.
Definition at line 30 of file OptimisationMethod.cpp.
Member Function Documentation
const std::string & stdair::OptimisationMethod::getLabel (const EN_OptimisationMethod & iMethod) static
Get the label as a string (e.g., "Leg based Monte Carlo" or "Leg based EMSRb").
Definition at line 59 of file OptimisationMethod.cpp.
char stdair::OptimisationMethod::getMethodLabel (const EN_OptimisationMethod & iMethod) static
Get the label as a single char (e.g., 'M' or 'E').
Definition at line 64 of file OptimisationMethod.cpp.
std::string stdair::OptimisationMethod::getMethodLabelAsString (const EN_OptimisationMethod & iMethod) static
Get the label as a string of a single char (e.g., "M" or "E").
Definition at line 70 of file OptimisationMethod.cpp.
std::string stdair::OptimisationMethod::describeLabels () static
List the labels.
Definition at line 77 of file OptimisationMethod.cpp.
References LAST_VALUE.
Referenced by OptimisationMethod().
OptimisationMethod::EN_OptimisationMethod stdair::OptimisationMethod::getMethod () const
Get the enumerated value.
Definition at line 89 of file OptimisationMethod.cpp.
Referenced by stdair::AirlineFeature::getOptimisationMethod().
std::string stdair::OptimisationMethod::getMethodAsString () const
Get the enumerated value as a short string (e.g., "M" or "E").
Definition at line 94 of file OptimisationMethod.cpp.
const std::string stdair::OptimisationMethod::describe () const virtual
Give a description of the structure (e.g., "Leg based Monte Carlo" or "Leg based EMSRb").
Implements stdair::StructAbstract.
Definition at line 101 of file OptimisationMethod.cpp.
bool stdair::OptimisationMethod::operator== (const EN_OptimisationMethod & iMethod) const
Comparaison operator.
Definition at line 109 of file OptimisationMethod.cpp.
void stdair::StructAbstract::toStream (std::ostream & ioOut) const inline inherited
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 29 of file StructAbstract.hpp.
References stdair::StructAbstract::describe().
virtual void stdair::StructAbstract::fromStream (std::istream & ioIn) inline virtual inherited
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented in stdair::BookingRequestStruct, stdair::EventStruct, stdair::TravelSolutionStruct, stdair::VirtualClassStruct, stdair::ConfigHolderStruct, stdair::FareOptionStruct, stdair::OptimisationNotificationStruct, stdair::ProgressStatusSet, stdair::YieldRange, stdair::CancellationStruct, stdair::AirlineStruct, stdair::RMEventStruct, stdair::SnapshotStruct, stdair::FFDisutilityCurveHolderStruct, stdair::FRAT5CurveHolderStruct, and stdair::BreakPointStruct.
Definition at line 38 of file StructAbstract.hpp.
Referenced by operator>>().
The documentation for this struct was generated from the following files:
stdair/basic/OptimisationMethod.hpp
stdair/basic/OptimisationMethod.cpp