stdair::Inventory Class Reference
stdair::Inventory Class Reference
Class representing the actual attributes for an airline inventory.
#include <stdair/bom/Inventory.hpp>
Public Types
typedef InventoryKey Key_T
Public Member Functions
const Key_T & getKey () const
const AirlineCode_T & getAirlineCode () const
ForecastingMethod::EN_ForecastingMethod getForecastingMethod () const
UnconstrainingMethod::EN_UnconstrainingMethod getUnconstrainingMethod () const
PreOptimisationMethod::EN_PreOptimisationMethod getPreOptimisationMethod () const
OptimisationMethod::EN_OptimisationMethod getOptimisationMethod () const
PartnershipTechnique::EN_PartnershipTechnique getPartnershipTechnique () const
BomAbstract *const getParent () const
const HolderMap_T & getHolderMap () const
FlightDate * getFlightDate (const std::string &iFlightDateKeyStr) const
FlightDate * getFlightDate (const FlightDateKey &) const
AirlineFeature * getAirlineFeature () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
std::string toString () const
const std::string describeKey () const
template<class Archive >
void serialize (Archive &ar, const unsigned int iFileVersion)
Protected Member Functions
Inventory (const Key_T &)
~Inventory ()
Protected Attributes
Key_T _key
BomAbstract * _parent
AirlineFeature * _airlineFeature
HolderMap_T _holderMap
Friends
template<typename BOM >
class FacBom
template<typename BOM >
class FacCloneBom
class FacBomManager
class boost::serialization::access
Detailed Description
Class representing the actual attributes for an airline inventory.
Definition at line 34 of file Inventory.hpp.
Member Typedef Documentation
typedef InventoryKey stdair::Inventory::Key_T
Definition allowing to retrieve the associated BOM key type.
Definition at line 45 of file Inventory.hpp.
Constructor & Destructor Documentation
stdair::Inventory::Inventory (const Key_T & iKey) protected
Constructor.
Definition at line 31 of file Inventory.cpp.
stdair::Inventory::~Inventory () protected
Destructor.
Definition at line 38 of file Inventory.cpp.
Member Function Documentation
const Key_T& stdair::Inventory::getKey () const inline
Get the inventory key (airline code).
Definition at line 51 of file Inventory.hpp.
References _key.
const AirlineCode_T& stdair::Inventory::getAirlineCode () const inline
Get the airline code (inventory/primary key).
Definition at line 56 of file Inventory.hpp.
References _key, and stdair::InventoryKey::getAirlineCode().
Referenced by stdair::OnDDate::getAirlineCode(), stdair::FlightDate::getAirlineCode(), stdair::BomJSONExport::jsonExportFlightDateList(), and stdair::BomRetriever::retrieveSegmentDateFromLongKey().
ForecastingMethod::EN_ForecastingMethod stdair::Inventory::getForecastingMethod () const
Get the forecasting method.
Definition at line 64 of file Inventory.cpp.
References _airlineFeature, and stdair::AirlineFeature::getForecastingMethod().
UnconstrainingMethod::EN_UnconstrainingMethod stdair::Inventory::getUnconstrainingMethod () const
Get the unconstraining method.
Definition at line 71 of file Inventory.cpp.
References _airlineFeature, and stdair::AirlineFeature::getUnconstrainingMethod().
PreOptimisationMethod::EN_PreOptimisationMethod stdair::Inventory::getPreOptimisationMethod () const
Get the pre-optimisation method.
Definition at line 78 of file Inventory.cpp.
References _airlineFeature, and stdair::AirlineFeature::getPreOptimisationMethod().
OptimisationMethod::EN_OptimisationMethod stdair::Inventory::getOptimisationMethod () const
Get the optimisation method.
Definition at line 85 of file Inventory.cpp.
References _airlineFeature, and stdair::AirlineFeature::getOptimisationMethod().
PartnershipTechnique::EN_PartnershipTechnique stdair::Inventory::getPartnershipTechnique () const
Get the partnership technique.
Definition at line 92 of file Inventory.cpp.
References _airlineFeature, and stdair::AirlineFeature::getPartnershipTechnique().
BomAbstract* const stdair::Inventory::getParent () const inline
Get the parent object.
Definition at line 76 of file Inventory.hpp.
References _parent.
const HolderMap_T& stdair::Inventory::getHolderMap () const inline
Get the map of children.
Definition at line 81 of file Inventory.hpp.
References _holderMap.
FlightDate * stdair::Inventory::getFlightDate (const std::string & iFlightDateKeyStr) const
Get a pointer on the FlightDate object corresponding to the given key.
Note
The FlightDate object can be inherited from, if needed. In that case, a dynamic_cast<> may be needed.
Parameters
const std::string& The flight-date key.
Returns
FlightDate* Found FlightDate object. NULL if not found.
Definition at line 50 of file Inventory.cpp.
Referenced by getFlightDate(), stdair::BomRetriever::retrieveFlightDateFromKey(), and stdair::BomRetriever::retrieveFlightDateFromLongKey().
FlightDate * stdair::Inventory::getFlightDate (const FlightDateKey & iFlightDateKey) const
Get a pointer on the FlightDate object corresponding to the given key.
Note
The FlightDate object can be inherited from, if needed. In that case, a dynamic_cast<> may be needed.
Parameters
const FlightDateKey& The flight-date key
Returns
FlightDate* Found FlightDate object. NULL if not found.
Definition at line 58 of file Inventory.cpp.
References getFlightDate(), and stdair::FlightDateKey::toString().
AirlineFeature* stdair::Inventory::getAirlineFeature () const inline
Get the airline feature.
Definition at line 112 of file Inventory.hpp.
References _airlineFeature.
Referenced by stdair::BomManager::getObjectPtr().
void stdair::Inventory::toStream (std::ostream & ioOut) const inline virtual
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Implements stdair::BomAbstract.
Definition at line 132 of file Inventory.hpp.
References toString().
void stdair::Inventory::fromStream (std::istream & ioIn) inline virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Implements stdair::BomAbstract.
Definition at line 141 of file Inventory.hpp.
std::string stdair::Inventory::toString () const virtual
Get the serialised version of the Business Object.
Implements stdair::BomAbstract.
Definition at line 42 of file Inventory.cpp.
References describeKey().
Referenced by toStream().
const std::string stdair::Inventory::describeKey () const inline
Get a string describing the key.
Definition at line 152 of file Inventory.hpp.
References _key, and stdair::InventoryKey::toString().
Referenced by stdair::BomRetriever::retrieveFullKeyFromSegmentDate(), and toString().
template<class Archive > void stdair::Inventory::serialize (Archive & ar, const unsigned int iFileVersion)
Serialisation.
Definition at line 160 of file CmdBomSerialiser.cpp.
References _key.
Friends And Related Function Documentation
template<typename BOM > friend class FacBom friend
Definition at line 35 of file Inventory.hpp.
template<typename BOM > friend class FacCloneBom friend
Definition at line 36 of file Inventory.hpp.
friend class FacBomManager friend
Definition at line 37 of file Inventory.hpp.
friend class boost::serialization::access friend
Definition at line 38 of file Inventory.hpp.
Member Data Documentation
Key_T stdair::Inventory::_key protected
Primary key (airline code).
Definition at line 204 of file Inventory.hpp.
Referenced by describeKey(), getAirlineCode(), getKey(), and serialize().
BomAbstract* stdair::Inventory::_parent protected
Pointer on the parent class (BomRoot).
Definition at line 209 of file Inventory.hpp.
Referenced by getParent().
AirlineFeature* stdair::Inventory::_airlineFeature protected
Features specific to the airline.
Definition at line 214 of file Inventory.hpp.
Referenced by getAirlineFeature(), getForecastingMethod(), getOptimisationMethod(), getPartnershipTechnique(), getPreOptimisationMethod(), and getUnconstrainingMethod().
HolderMap_T stdair::Inventory::_holderMap protected
Map holding the children (FlightDate objects).
Definition at line 219 of file Inventory.hpp.
Referenced by getHolderMap().
The documentation for this class was generated from the following files:
stdair/bom/Inventory.hpp
stdair/bom/Inventory.cpp
stdair/command/CmdBomSerialiser.cpp