stdair::PreOptimisationMethod Struct Reference
stdair::PreOptimisationMethod Struct Reference
#include <stdair/basic/PreOptimisationMethod.hpp>
Public Types
enum EN_PreOptimisationMethod { NONE = 0, FA, MRT, LAST_VALUE }
Public Member Functions
EN_PreOptimisationMethod getMethod () const
std::string getMethodAsString () const
const std::string describe () const
bool operator== (const EN_PreOptimisationMethod &) const
PreOptimisationMethod (const EN_PreOptimisationMethod &)
PreOptimisationMethod (const char iMethod)
PreOptimisationMethod (const PreOptimisationMethod &)
void toStream (std::ostream &ioOut) const
virtual void fromStream (std::istream &ioIn)
Static Public Member Functions
static const std::string & getLabel (const EN_PreOptimisationMethod &)
static char getMethodLabel (const EN_PreOptimisationMethod &)
static std::string getMethodLabelAsString (const EN_PreOptimisationMethod &)
static std::string describeLabels ()
Detailed Description
Enumeration of PreOptimisation methods.
Definition at line 15 of file PreOptimisationMethod.hpp.
Member Enumeration Documentation
enum stdair::PreOptimisationMethod::EN_PreOptimisationMethod
Enumerator
NONE
FA
MRT
LAST_VALUE
Definition at line 17 of file PreOptimisationMethod.hpp.
Constructor & Destructor Documentation
stdair::PreOptimisationMethod::PreOptimisationMethod (const EN_PreOptimisationMethod & iPreOptimisationMethod)
Constructor.
Definition at line 36 of file PreOptimisationMethod.cpp.
stdair::PreOptimisationMethod::PreOptimisationMethod (const char iMethod)
Constructor.
Definition at line 41 of file PreOptimisationMethod.cpp.
References describeLabels(), FA, LAST_VALUE, MRT, and NONE.
stdair::PreOptimisationMethod::PreOptimisationMethod (const PreOptimisationMethod & iPreOptimisationMethod)
Default copy constructor.
Definition at line 30 of file PreOptimisationMethod.cpp.
Member Function Documentation
const std::string & stdair::PreOptimisationMethod::getLabel (const EN_PreOptimisationMethod & iMethod) static
Get the label as a string (e.g., MRT or FA).
Definition at line 60 of file PreOptimisationMethod.cpp.
char stdair::PreOptimisationMethod::getMethodLabel (const EN_PreOptimisationMethod & iMethod) static
Get the label as a single char (e.g., 'M' or 'E').
Definition at line 65 of file PreOptimisationMethod.cpp.
std::string stdair::PreOptimisationMethod::getMethodLabelAsString (const EN_PreOptimisationMethod & iMethod) static
Get the label as a string of a single char (e.g., "M" or "E").
Definition at line 71 of file PreOptimisationMethod.cpp.
std::string stdair::PreOptimisationMethod::describeLabels () static
List the labels.
Definition at line 78 of file PreOptimisationMethod.cpp.
References LAST_VALUE.
Referenced by PreOptimisationMethod().
PreOptimisationMethod::EN_PreOptimisationMethod stdair::PreOptimisationMethod::getMethod () const
Get the enumerated value.
Definition at line 90 of file PreOptimisationMethod.cpp.
Referenced by stdair::AirlineFeature::getPreOptimisationMethod().
std::string stdair::PreOptimisationMethod::getMethodAsString () const
Get the enumerated value as a short string (e.g., "M" or "E").
Definition at line 95 of file PreOptimisationMethod.cpp.
const std::string stdair::PreOptimisationMethod::describe () const virtual
Give a description of the structure (e.g., MRT or FA).
Implements stdair::StructAbstract.
Definition at line 102 of file PreOptimisationMethod.cpp.
bool stdair::PreOptimisationMethod::operator== (const EN_PreOptimisationMethod & iMethod) const
Comparaison operator.
Definition at line 110 of file PreOptimisationMethod.cpp.
void stdair::StructAbstract::toStream (std::ostream & ioOut) const inline inherited
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 29 of file StructAbstract.hpp.
References stdair::StructAbstract::describe().
virtual void stdair::StructAbstract::fromStream (std::istream & ioIn) inline virtual inherited
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented in stdair::BookingRequestStruct, stdair::EventStruct, stdair::TravelSolutionStruct, stdair::VirtualClassStruct, stdair::ConfigHolderStruct, stdair::FareOptionStruct, stdair::OptimisationNotificationStruct, stdair::ProgressStatusSet, stdair::YieldRange, stdair::CancellationStruct, stdair::AirlineStruct, stdair::RMEventStruct, stdair::SnapshotStruct, stdair::FFDisutilityCurveHolderStruct, stdair::FRAT5CurveHolderStruct, and stdair::BreakPointStruct.
Definition at line 38 of file StructAbstract.hpp.
Referenced by operator>>().
The documentation for this struct was generated from the following files:
stdair/basic/PreOptimisationMethod.hpp
stdair/basic/PreOptimisationMethod.cpp