stdair::SegmentPeriodKey Struct Reference
stdair::SegmentPeriodKey Struct Reference
#include <stdair/bom/SegmentPeriodKey.hpp>
Public Member Functions
SegmentPeriodKey (const AirportCode_T &, const AirportCode_T &)
SegmentPeriodKey (const SegmentPeriodKey &)
~SegmentPeriodKey ()
const AirportCode_T & getBoardingPoint () const
const AirportCode_T & getOffPoint () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
Detailed Description
Key of segment-period.
Definition at line 14 of file SegmentPeriodKey.hpp.
Constructor & Destructor Documentation
stdair::SegmentPeriodKey::SegmentPeriodKey (const AirportCode_T & iBoardingPoint, const AirportCode_T & iOffPoint)
Constructors.
Definition at line 12 of file SegmentPeriodKey.cpp.
stdair::SegmentPeriodKey::SegmentPeriodKey (const SegmentPeriodKey & iKey)
Definition at line 18 of file SegmentPeriodKey.cpp.
stdair::SegmentPeriodKey::~SegmentPeriodKey ()
Destructor.
Definition at line 23 of file SegmentPeriodKey.cpp.
Member Function Documentation
const AirportCode_T& stdair::SegmentPeriodKey::getBoardingPoint () const inline
Get the boardinging point.
Definition at line 29 of file SegmentPeriodKey.hpp.
Referenced by stdair::SegmentPeriod::getBoardingPoint().
const AirportCode_T& stdair::SegmentPeriodKey::getOffPoint () const inline
Get the arrival point.
Definition at line 34 of file SegmentPeriodKey.hpp.
Referenced by stdair::SegmentPeriod::getOffPoint().
void stdair::SegmentPeriodKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 27 of file SegmentPeriodKey.cpp.
References toString().
void stdair::SegmentPeriodKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 32 of file SegmentPeriodKey.cpp.
const std::string stdair::SegmentPeriodKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-period.
Reimplemented from stdair::KeyAbstract.
Definition at line 36 of file SegmentPeriodKey.cpp.
Referenced by stdair::SegmentPeriod::describeKey(), and toStream().
The documentation for this struct was generated from the following files:
stdair/bom/SegmentPeriodKey.hpp
stdair/bom/SegmentPeriodKey.cpp