stdair::DictionaryManager Class Reference
stdair::DictionaryManager Class Reference
Class wrapper of dictionary business methods.
#include <stdair/basic/DictionaryManager.hpp>
Static Public Member Functions
static const stdair::Probability_T keyToValue (const DictionaryKey_T)
static const DictionaryKey_T valueToKey (const stdair::Probability_T)
Detailed Description
Class wrapper of dictionary business methods.
Definition at line 22 of file DictionaryManager.hpp.
Member Function Documentation
const stdair::Probability_T stdair::DictionaryManager::keyToValue (const DictionaryKey_T iKey) static
Convert from key to value.
Definition at line 12 of file DictionaryManager.cpp.
References stdair::DEFAULT_NUMBER_OF_SUBDIVISIONS.
Referenced by stdair::ContinuousAttributeLite< T >::displayCumulativeDistribution(), stdair::ContinuousAttributeLite< T >::getDerivativeValue(), stdair::ContinuousAttributeLite< T >::getRemainingProportion(), and stdair::ContinuousAttributeLite< T >::getValue().
const DictionaryKey_T stdair::DictionaryManager::valueToKey (const stdair::Probability_T iValue) static
Convert from value to key.
Definition at line 21 of file DictionaryManager.cpp.
References stdair::DEFAULT_NUMBER_OF_SUBDIVISIONS.
Referenced by stdair::ContinuousAttributeLite< T >::getValue().
The documentation for this class was generated from the following files:
stdair/basic/DictionaryManager.hpp
stdair/basic/DictionaryManager.cpp