stdair::FareOptionStruct Struct Reference
stdair::FareOptionStruct Struct Reference
Structure holding the elements of a fare option.
#include <stdair/bom/FareOptionStruct.hpp>
Public Member Functions
const ClassList_StringList_T & getClassPath () const
const Fare_T & getFare () const
const Availability_T & getAvailability () const
const ChangeFees_T getChangeFees () const
const NonRefundable_T getNonRefundable () const
const SaturdayStay_T getSaturdayStay () const
void addClassList (const std::string)
void emptyClassList ()
void setFare (const Fare_T &iFare)
void setAvailability (const Availability_T &iAvl)
void setChangeFees (const ChangeFees_T iRes)
void setNonRefundable (const NonRefundable_T iRes)
void setSaturdayStay (const SaturdayStay_T iRes)
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string describe () const
const std::string display () const
FareOptionStruct ()
FareOptionStruct (const std::string &iClassPath, const Fare_T &, const ChangeFees_T &, const NonRefundable_T &, const SaturdayStay_T &)
FareOptionStruct (const FareOptionStruct &)
~FareOptionStruct ()
Detailed Description
Structure holding the elements of a fare option.
Definition at line 20 of file FareOptionStruct.hpp.
Constructor & Destructor Documentation
stdair::FareOptionStruct::FareOptionStruct ()
Default constructor.
Definition at line 14 of file FareOptionStruct.cpp.
stdair::FareOptionStruct::FareOptionStruct (const std::string & iClassPath, const Fare_T & iFare, const ChangeFees_T & iChangeFee, const NonRefundable_T & iNonRefundable, const SaturdayStay_T & iSaturdayNightStay)
Main constructor.
Definition at line 26 of file FareOptionStruct.cpp.
stdair::FareOptionStruct::FareOptionStruct (const FareOptionStruct & iFO)
Copy constructor.
Definition at line 19 of file FareOptionStruct.cpp.
stdair::FareOptionStruct::~FareOptionStruct ()
Destructor.
Definition at line 38 of file FareOptionStruct.cpp.
Member Function Documentation
const ClassList_StringList_T& stdair::FareOptionStruct::getClassPath () const inline
Get the class-path.
Definition at line 24 of file FareOptionStruct.hpp.
const Fare_T& stdair::FareOptionStruct::getFare () const inline
Get the fare value.
Definition at line 29 of file FareOptionStruct.hpp.
const Availability_T& stdair::FareOptionStruct::getAvailability () const inline
Get the availability.
Definition at line 34 of file FareOptionStruct.hpp.
const ChangeFees_T stdair::FareOptionStruct::getChangeFees () const inline
Get the change fees.
Definition at line 39 of file FareOptionStruct.hpp.
const NonRefundable_T stdair::FareOptionStruct::getNonRefundable () const inline
State whether the ticket is refundable.
Definition at line 44 of file FareOptionStruct.hpp.
const SaturdayStay_T stdair::FareOptionStruct::getSaturdayStay () const inline
State whether there is a condition on the saturday night stay.
Definition at line 49 of file FareOptionStruct.hpp.
void stdair::FareOptionStruct::addClassList (const std::string iClassCodeList)
Set the class-path.
Definition at line 93 of file FareOptionStruct.cpp.
void stdair::FareOptionStruct::emptyClassList ()
Empty the class-path.
Definition at line 98 of file FareOptionStruct.cpp.
void stdair::FareOptionStruct::setFare (const Fare_T & iFare) inline
Set the fare value.
Definition at line 63 of file FareOptionStruct.hpp.
void stdair::FareOptionStruct::setAvailability (const Availability_T & iAvl) inline
Set the availability.
Definition at line 68 of file FareOptionStruct.hpp.
void stdair::FareOptionStruct::setChangeFees (const ChangeFees_T iRes) inline
Set the change fees.
Definition at line 73 of file FareOptionStruct.hpp.
void stdair::FareOptionStruct::setNonRefundable (const NonRefundable_T iRes) inline
Set the flag for the ticket refundability.
Definition at line 78 of file FareOptionStruct.hpp.
void stdair::FareOptionStruct::setSaturdayStay (const SaturdayStay_T iRes) inline
Set the flag for the saturday night stay condition.
Definition at line 83 of file FareOptionStruct.hpp.
void stdair::FareOptionStruct::toStream (std::ostream & ioOut) const
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 42 of file FareOptionStruct.cpp.
References describe().
void stdair::FareOptionStruct::fromStream (std::istream & ioIn) virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::StructAbstract.
Definition at line 47 of file FareOptionStruct.cpp.
const std::string stdair::FareOptionStruct::describe () const virtual
Display of the structure.
Implements stdair::StructAbstract.
Definition at line 51 of file FareOptionStruct.cpp.
Referenced by stdair::TravelSolutionStruct::describe(), and toStream().
const std::string stdair::FareOptionStruct::display () const
Display of the structure.
Definition at line 73 of file FareOptionStruct.cpp.
Referenced by stdair::TravelSolutionStruct::display().
The documentation for this struct was generated from the following files:
stdair/bom/FareOptionStruct.hpp
stdair/bom/FareOptionStruct.cpp