stdair::FacCloneBom< BOM > Class Template Reference
stdair::FacCloneBom< BOM > Class Template Reference
Base class for Factory layer.
#include <stdair/factory/FacCloneBom.hpp>
Public Member Functions
BOM & clone (const BOM &)
~FacCloneBom ()
void clean ()
Static Public Member Functions
static FacCloneBom & instance ()
Protected Member Functions
FacCloneBom ()
Detailed Description
template<typename BOM>
class stdair::FacCloneBom< BOM >
Base class for Factory layer.
Definition at line 22 of file FacCloneBom.hpp.
Constructor & Destructor Documentation
template<typename BOM > stdair::FacCloneBom< BOM >::FacCloneBom () inline protected
Default Constructor.
Definition at line 48 of file FacCloneBom.hpp.
template<typename BOM > stdair::FacCloneBom< BOM >::~FacCloneBom () inline
Destructor.
Definition at line 54 of file FacCloneBom.hpp.
References stdair::FacCloneBom< BOM >::clean().
Member Function Documentation
template<typename BOM > FacCloneBom< BOM > & stdair::FacCloneBom< BOM >::instance () static
Provide the unique instance.
The singleton is instantiated when first used.
Returns
FacCloneBom&
Definition at line 82 of file FacCloneBom.hpp.
References stdair::FacSupervisor::instance(), and stdair::FacSupervisor::registerCloneBomFactory().
template<typename BOM > BOM & stdair::FacCloneBom< BOM >::clone (const BOM & iBom)
Clone a BOM object.
Definition at line 110 of file FacCloneBom.hpp.
template<typename BOM > void stdair::FacCloneBom< BOM >::clean ()
Destroyed all the object instantiated by this factory.
Definition at line 93 of file FacCloneBom.hpp.
Referenced by stdair::FacCloneBom< BOM >::~FacCloneBom().
The documentation for this class was generated from the following file:
stdair/factory/FacCloneBom.hpp