stdair::OnDDateKey Struct Reference
stdair::OnDDateKey Struct Reference
Key of a given O&D-date, made of a list of OnD strings. a OnD string contains the airline code, the flight number, the date and the segment (origin and destination).
#include <stdair/bom/OnDDateKey.hpp>
Public Member Functions
OnDDateKey (const OnDStringList_T &)
OnDDateKey (const OnDDateKey &)
~OnDDateKey ()
const Date_T getDate () const
const AirportCode_T getOrigin () const
const AirportCode_T getDestination () const
const short getNbOfSegments () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
template<class Archive >
void serialize (Archive &ar, const unsigned int iFileVersion)
Friends
class boost::serialization::access
Detailed Description
Key of a given O&D-date, made of a list of OnD strings. a OnD string contains the airline code, the flight number, the date and the segment (origin and destination).
Definition at line 23 of file OnDDateKey.hpp.
Constructor & Destructor Documentation
stdair::OnDDateKey::OnDDateKey (const OnDStringList_T & iOnDStringList)
Constructor.
Definition at line 33 of file OnDDateKey.cpp.
stdair::OnDDateKey::OnDDateKey (const OnDDateKey & iKey)
Copy constructor.
Definition at line 38 of file OnDDateKey.cpp.
stdair::OnDDateKey::~OnDDateKey ()
Destructor.
Definition at line 43 of file OnDDateKey.cpp.
Member Function Documentation
const Date_T stdair::OnDDateKey::getDate () const
Get the boarding date.
Definition at line 47 of file OnDDateKey.cpp.
References stdair::BomKeyManager::extractFlightDateKey(), and stdair::FlightDateKey::getDepartureDate().
Referenced by stdair::OnDDate::getDate().
const AirportCode_T stdair::OnDDateKey::getOrigin () const
Get the origin.
Definition at line 54 of file OnDDateKey.cpp.
References stdair::BomKeyManager::extractSegmentDateKey(), and stdair::SegmentDateKey::getBoardingPoint().
Referenced by stdair::OnDDate::getOrigin().
const AirportCode_T stdair::OnDDateKey::getDestination () const
Get the destination.
Definition at line 61 of file OnDDateKey.cpp.
References stdair::BomKeyManager::extractSegmentDateKey(), and stdair::SegmentDateKey::getOffPoint().
Referenced by stdair::OnDDate::getDestination().
const short stdair::OnDDateKey::getNbOfSegments () const inline
Get the number of segments.
Definition at line 70 of file OnDDateKey.hpp.
Referenced by stdair::OnDDate::getNbOfSegments().
void stdair::OnDDateKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 68 of file OnDDateKey.cpp.
References toString().
void stdair::OnDDateKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 73 of file OnDDateKey.cpp.
const std::string stdair::OnDDateKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-date.
Reimplemented from stdair::KeyAbstract.
Definition at line 77 of file OnDDateKey.cpp.
Referenced by stdair::OnDDate::describeKey(), and toStream().
template<class Archive > void stdair::OnDDateKey::serialize (Archive & ar, const unsigned int iFileVersion)
Serialisation.
Definition at line 102 of file OnDDateKey.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 24 of file OnDDateKey.hpp.
The documentation for this struct was generated from the following files:
stdair/bom/OnDDateKey.hpp
stdair/bom/OnDDateKey.cpp