stdair::JSonCommand Struct Reference
stdair::JSonCommand Struct Reference
Enumeration of json commands.
#include <stdair/basic/JSonCommand.hpp>
Public Types
enum EN_JSonCommand {
LIST = 0, FLIGHT_DATE, EVENT_LIST, BREAK_POINT,
RUN, RESET, STATUS, CONFIG,
LAST_VALUE
}
Public Member Functions
EN_JSonCommand getCommand () const
const std::string describe () const
bool operator== (const EN_JSonCommand &) const
JSonCommand (const EN_JSonCommand &)
JSonCommand (const std::string &)
JSonCommand (const JSonCommand &)
void toStream (std::ostream &ioOut) const
virtual void fromStream (std::istream &ioIn)
Static Public Member Functions
static EN_JSonCommand getCommand (const std::string &iCommandStr)
static std::string getLabel (const EN_JSonCommand &)
static std::string describeLabels ()
Detailed Description
Enumeration of json commands.
Definition at line 17 of file JSonCommand.hpp.
Member Enumeration Documentation
enum stdair::JSonCommand::EN_JSonCommand
Enumerator
LIST
FLIGHT_DATE
EVENT_LIST
BREAK_POINT
RUN
RESET
STATUS
CONFIG
LAST_VALUE
Definition at line 19 of file JSonCommand.hpp.
Constructor & Destructor Documentation
stdair::JSonCommand::JSonCommand (const EN_JSonCommand &)
Main Constructor.
stdair::JSonCommand::JSonCommand (const std::string & iCommandStr)
Alternative constructor.
Definition at line 71 of file JSonCommand.cpp.
References getCommand().
stdair::JSonCommand::JSonCommand (const JSonCommand & iJSonCommand)
Default copy constructor.
Definition at line 25 of file JSonCommand.cpp.
Member Function Documentation
JSonCommand::EN_JSonCommand stdair::JSonCommand::getCommand (const std::string & iCommandStr) static
Get the command value from parsing a single char (e.g., "list", "flight_date", "event_list", "break_point", "run", "reset, "status" or "config").
Definition at line 31 of file JSonCommand.cpp.
References BREAK_POINT, CONFIG, describeLabels(), EVENT_LIST, FLIGHT_DATE, LAST_VALUE, LIST, RESET, RUN, and STATUS.
Referenced by stdair::BomJSONImport::jsonImportCommand().
std::string stdair::JSonCommand::getLabel (const EN_JSonCommand & iCommand) static
Get a label of a command
Definition at line 66 of file JSonCommand.cpp.
std::string stdair::JSonCommand::describeLabels () static
List the labels.
Definition at line 77 of file JSonCommand.cpp.
References LAST_VALUE.
Referenced by getCommand().
JSonCommand::EN_JSonCommand stdair::JSonCommand::getCommand () const
Get the enumerated value.
Definition at line 89 of file JSonCommand.cpp.
Referenced by JSonCommand().
const std::string stdair::JSonCommand::describe () const virtual
Give a description of the structure (e.g., "list", "flight_date", "event_list", "break_point" "run", "reset, "status" or "config").
Implements stdair::StructAbstract.
Definition at line 94 of file JSonCommand.cpp.
bool stdair::JSonCommand::operator== (const EN_JSonCommand & iCommand) const
Comparison operator.
Definition at line 102 of file JSonCommand.cpp.
void stdair::StructAbstract::toStream (std::ostream & ioOut) const inline inherited
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 29 of file StructAbstract.hpp.
References stdair::StructAbstract::describe().
virtual void stdair::StructAbstract::fromStream (std::istream & ioIn) inline virtual inherited
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented in stdair::BookingRequestStruct, stdair::EventStruct, stdair::TravelSolutionStruct, stdair::VirtualClassStruct, stdair::ConfigHolderStruct, stdair::FareOptionStruct, stdair::OptimisationNotificationStruct, stdair::ProgressStatusSet, stdair::YieldRange, stdair::CancellationStruct, stdair::AirlineStruct, stdair::RMEventStruct, stdair::SnapshotStruct, stdair::FFDisutilityCurveHolderStruct, stdair::FRAT5CurveHolderStruct, and stdair::BreakPointStruct.
Definition at line 38 of file StructAbstract.hpp.
Referenced by operator>>().
The documentation for this struct was generated from the following files:
stdair/basic/JSonCommand.hpp
stdair/basic/JSonCommand.cpp