stdair::FlightPeriodKey Struct Reference
stdair::FlightPeriodKey Struct Reference
#include <stdair/bom/FlightPeriodKey.hpp>
Public Member Functions
FlightPeriodKey (const FlightNumber_T &, const PeriodStruct &)
FlightPeriodKey (const FlightPeriodKey &)
~FlightPeriodKey ()
const FlightNumber_T & getFlightNumber () const
const PeriodStruct & getPeriod () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
Detailed Description
Key of flight-period.
Definition at line 13 of file FlightPeriodKey.hpp.
Constructor & Destructor Documentation
stdair::FlightPeriodKey::FlightPeriodKey (const FlightNumber_T & iFlightNumber, const PeriodStruct & iPeriod)
Constructors.
Definition at line 10 of file FlightPeriodKey.cpp.
stdair::FlightPeriodKey::FlightPeriodKey (const FlightPeriodKey & iKey)
Definition at line 16 of file FlightPeriodKey.cpp.
stdair::FlightPeriodKey::~FlightPeriodKey ()
Destructor.
Definition at line 21 of file FlightPeriodKey.cpp.
Member Function Documentation
const FlightNumber_T& stdair::FlightPeriodKey::getFlightNumber () const inline
Get the flight number.
Definition at line 28 of file FlightPeriodKey.hpp.
Referenced by stdair::FlightPeriod::getFlightNumber().
const PeriodStruct& stdair::FlightPeriodKey::getPeriod () const inline
Get the active days-of-week.
Definition at line 33 of file FlightPeriodKey.hpp.
Referenced by stdair::FlightPeriod::getPeriod().
void stdair::FlightPeriodKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 25 of file FlightPeriodKey.cpp.
References toString().
void stdair::FlightPeriodKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 30 of file FlightPeriodKey.cpp.
const std::string stdair::FlightPeriodKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-period.
Reimplemented from stdair::KeyAbstract.
Definition at line 34 of file FlightPeriodKey.cpp.
References stdair::PeriodStruct::describeShort().
Referenced by stdair::FlightPeriod::describeKey(), and toStream().
The documentation for this struct was generated from the following files:
stdair/bom/FlightPeriodKey.hpp
stdair/bom/FlightPeriodKey.cpp