stdair::SimpleNestingStructure Class Reference
stdair::SimpleNestingStructure Class Reference
#include <stdair/bom/SimpleNestingStructure.hpp>
Public Types
typedef NestingStructureKey Key_T
Public Member Functions
const Key_T & getKey () const
BomAbstract *const getParent () const
const HolderMap_T & getHolderMap () const
const NestingNodeList_T & getNestingNodeList () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
std::string toString () const
const std::string describeKey () const
template<class Archive >
void serialize (Archive &ar, const unsigned int iFileVersion)
SimpleNestingStructure (const Key_T &)
virtual ~SimpleNestingStructure ()
Friends
template<typename BOM >
class FacBom
class FacBomManager
class boost::serialization::access
Detailed Description
Structure holding a nesting node map according to the yield.
Definition at line 26 of file SimpleNestingStructure.hpp.
Member Typedef Documentation
typedef NestingStructureKey stdair::SimpleNestingStructure::Key_T
Definition allowing to retrieve the associated BOM key type.
Definition at line 36 of file SimpleNestingStructure.hpp.
Constructor & Destructor Documentation
stdair::SimpleNestingStructure::SimpleNestingStructure (const Key_T & iKey)
Main constructor.
Definition at line 36 of file SimpleNestingStructure.cpp.
stdair::SimpleNestingStructure::~SimpleNestingStructure () virtual
Destructor.
Definition at line 41 of file SimpleNestingStructure.cpp.
Member Function Documentation
const Key_T& stdair::SimpleNestingStructure::getKey () const inline
Get the nesting key.
Definition at line 41 of file SimpleNestingStructure.hpp.
BomAbstract* const stdair::SimpleNestingStructure::getParent () const inline
Get the parent object.
Definition at line 46 of file SimpleNestingStructure.hpp.
const HolderMap_T& stdair::SimpleNestingStructure::getHolderMap () const inline
Get the map of children holders.
Definition at line 53 of file SimpleNestingStructure.hpp.
const NestingNodeList_T & stdair::SimpleNestingStructure::getNestingNodeList () const
Get the nesting node list
Definition at line 115 of file SimpleNestingStructure.cpp.
void stdair::SimpleNestingStructure::toStream (std::ostream & ioOut) const inline virtual
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Implements stdair::BomAbstract.
Definition at line 69 of file SimpleNestingStructure.hpp.
References toString().
void stdair::SimpleNestingStructure::fromStream (std::istream & ioIn) inline virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Implements stdair::BomAbstract.
Definition at line 78 of file SimpleNestingStructure.hpp.
std::string stdair::SimpleNestingStructure::toString () const virtual
Get the serialised version of the Business Object.
Implements stdair::BomAbstract.
Definition at line 107 of file SimpleNestingStructure.cpp.
References describeKey().
Referenced by toStream().
const std::string stdair::SimpleNestingStructure::describeKey () const inline
Get a string describing the key.
Definition at line 89 of file SimpleNestingStructure.hpp.
References stdair::NestingStructureKey::toString().
Referenced by toString().
template<class Archive > void stdair::SimpleNestingStructure::serialize (Archive & ar, const unsigned int iFileVersion)
Serialisation.
Friends And Related Function Documentation
template<typename BOM > friend class FacBom friend
Definition at line 27 of file SimpleNestingStructure.hpp.
friend class FacBomManager friend
Definition at line 28 of file SimpleNestingStructure.hpp.
friend class boost::serialization::access friend
Definition at line 29 of file SimpleNestingStructure.hpp.
The documentation for this class was generated from the following files:
stdair/bom/SimpleNestingStructure.hpp
stdair/bom/SimpleNestingStructure.cpp