stdair::PosChannelKey Struct Reference
stdair::PosChannelKey Struct Reference
Key of point of sale and channel.
#include <stdair/bom/PosChannelKey.hpp>
Public Member Functions
PosChannelKey (const stdair::CityCode_T &, const stdair::ChannelLabel_T &)
PosChannelKey (const PosChannelKey &)
~PosChannelKey ()
const stdair::CityCode_T & getPos () const
const stdair::ChannelLabel_T & getChannel () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
Detailed Description
Key of point of sale and channel.
Definition at line 15 of file PosChannelKey.hpp.
Constructor & Destructor Documentation
stdair::PosChannelKey::PosChannelKey (const stdair::CityCode_T & iPos, const stdair::ChannelLabel_T & iChannel)
Main constructor.
Definition at line 22 of file PosChannelKey.cpp.
stdair::PosChannelKey::PosChannelKey (const PosChannelKey & iKey)
Copy constructor.
Definition at line 28 of file PosChannelKey.cpp.
stdair::PosChannelKey::~PosChannelKey ()
Destructor.
Definition at line 33 of file PosChannelKey.cpp.
Member Function Documentation
const stdair::CityCode_T& stdair::PosChannelKey::getPos () const inline
Get the point of sale.
Definition at line 43 of file PosChannelKey.hpp.
Referenced by stdair::PosChannel::getPos().
const stdair::ChannelLabel_T& stdair::PosChannelKey::getChannel () const inline
Get the channel.
Definition at line 50 of file PosChannelKey.hpp.
Referenced by stdair::PosChannel::getChannel().
void stdair::PosChannelKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 37 of file PosChannelKey.cpp.
References toString().
void stdair::PosChannelKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 42 of file PosChannelKey.cpp.
const std::string stdair::PosChannelKey::toString () const virtual
Get the serialised version of the Business Object Key. That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
Reimplemented from stdair::KeyAbstract.
Definition at line 46 of file PosChannelKey.cpp.
References stdair::DEFAULT_KEY_SUB_FLD_DELIMITER.
Referenced by stdair::PosChannel::describeKey(), and toStream().
The documentation for this struct was generated from the following files:
stdair/bom/PosChannelKey.hpp
stdair/bom/PosChannelKey.cpp