stdair::LegCabinKey Struct Reference
stdair::LegCabinKey Struct Reference
Key of a given leg-cabin, made of a cabin code (only).
#include <stdair/bom/LegCabinKey.hpp>
Public Member Functions
LegCabinKey (const CabinCode_T &iCabinCode)
LegCabinKey (const LegCabinKey &)
~LegCabinKey ()
const CabinCode_T & getCabinCode () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
template<class Archive >
void serialize (Archive &ar, const unsigned int iFileVersion)
Friends
class boost::serialization::access
Detailed Description
Key of a given leg-cabin, made of a cabin code (only).
Definition at line 26 of file LegCabinKey.hpp.
Constructor & Destructor Documentation
stdair::LegCabinKey::LegCabinKey (const CabinCode_T & iCabinCode)
Constructor.
Definition at line 23 of file LegCabinKey.cpp.
stdair::LegCabinKey::LegCabinKey (const LegCabinKey & iKey)
Copy constructor.
Definition at line 28 of file LegCabinKey.cpp.
stdair::LegCabinKey::~LegCabinKey ()
Destructor.
Definition at line 33 of file LegCabinKey.cpp.
Member Function Documentation
const CabinCode_T& stdair::LegCabinKey::getCabinCode () const inline
Get the cabin code.
Definition at line 56 of file LegCabinKey.hpp.
Referenced by stdair::LegCabin::getCabinCode().
void stdair::LegCabinKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 37 of file LegCabinKey.cpp.
References toString().
void stdair::LegCabinKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 42 of file LegCabinKey.cpp.
const std::string stdair::LegCabinKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-date.
Reimplemented from stdair::KeyAbstract.
Definition at line 46 of file LegCabinKey.cpp.
Referenced by stdair::LegCabin::describeKey(), stdair::LegDate::getLegCabin(), and toStream().
template<class Archive > void stdair::LegCabinKey::serialize (Archive & ar, const unsigned int iFileVersion)
Serialisation.
Definition at line 68 of file LegCabinKey.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 27 of file LegCabinKey.hpp.
The documentation for this struct was generated from the following files:
stdair/bom/LegCabinKey.hpp
stdair/bom/LegCabinKey.cpp