stdair::JSONString Class Reference
stdair::JSONString Class Reference
JSON-formatted string.
#include <stdair/stdair_json.hpp>
Public Member Functions
JSONString (const std::string &iJsonString)
JSONString ()
virtual ~JSONString ()
const std::string & getString () const
Protected Attributes
std::string _jsonString
Detailed Description
JSON-formatted string.
Definition at line 16 of file stdair_json.hpp.
Constructor & Destructor Documentation
stdair::JSONString::JSONString (const std::string & iJsonString) inline explicit
Main Constructor.
Definition at line 21 of file stdair_json.hpp.
stdair::JSONString::JSONString () inline explicit
Default constructor.
Definition at line 26 of file stdair_json.hpp.
virtual stdair::JSONString::~JSONString () inline virtual
Destructor.
Definition at line 31 of file stdair_json.hpp.
Member Function Documentation
const std::string& stdair::JSONString::getString () const inline
Get the string value.
Definition at line 36 of file stdair_json.hpp.
References _jsonString.
Referenced by stdair::BomJSONImport::jsonImportBreakPoints(), stdair::BomJSONImport::jsonImportCommand(), stdair::BomJSONImport::jsonImportConfig(), stdair::BomJSONImport::jsonImportEventType(), stdair::BomJSONImport::jsonImportFlightDate(), stdair::BomJSONImport::jsonImportFlightNumber(), and stdair::BomJSONImport::jsonImportInventoryKey().
Member Data Documentation
std::string stdair::JSONString::_jsonString protected
Definition at line 44 of file stdair_json.hpp.
Referenced by getString().
The documentation for this class was generated from the following file:
stdair/stdair_json.hpp