stdair::PosChannel Class Reference
stdair::PosChannel Class Reference
Class representing the actual attributes for a fare point of sale.
#include <stdair/bom/PosChannel.hpp>
Public Types
typedef PosChannelKey Key_T
Public Member Functions
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
std::string toString () const
const std::string describeKey () const
const Key_T & getKey () const
BomAbstract *const getParent () const
const stdair::HolderMap_T & getHolderMap () const
const CityCode_T & getPos () const
const ChannelLabel_T & getChannel () const
Protected Member Functions
PosChannel (const Key_T &)
virtual ~PosChannel ()
Protected Attributes
Key_T _key
BomAbstract * _parent
HolderMap_T _holderMap
Friends
template<typename BOM >
class FacBom
template<typename BOM >
class FacCloneBom
class FacBomManager
Detailed Description
Class representing the actual attributes for a fare point of sale.
Definition at line 19 of file PosChannel.hpp.
Member Typedef Documentation
typedef PosChannelKey stdair::PosChannel::Key_T
Definition allowing to retrieve the associated BOM key type.
Definition at line 29 of file PosChannel.hpp.
Constructor & Destructor Documentation
stdair::PosChannel::PosChannel (const Key_T & iKey) protected
Main constructor.
Definition at line 28 of file PosChannel.cpp.
stdair::PosChannel::~PosChannel () protected virtual
Destructor.
Definition at line 33 of file PosChannel.cpp.
Member Function Documentation
void stdair::PosChannel::toStream (std::ostream & ioOut) const inline virtual
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Implements stdair::BomAbstract.
Definition at line 38 of file PosChannel.hpp.
References toString().
void stdair::PosChannel::fromStream (std::istream & ioIn) inline virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Implements stdair::BomAbstract.
Definition at line 47 of file PosChannel.hpp.
std::string stdair::PosChannel::toString () const virtual
Get the serialised version of the Business Object.
Implements stdair::BomAbstract.
Definition at line 37 of file PosChannel.cpp.
References describeKey().
Referenced by toStream().
const std::string stdair::PosChannel::describeKey () const inline
Get a string describing the key.
Definition at line 58 of file PosChannel.hpp.
References _key, and stdair::PosChannelKey::toString().
Referenced by toString().
const Key_T& stdair::PosChannel::getKey () const inline
Get the primary key (pos, channel).
Definition at line 67 of file PosChannel.hpp.
References _key.
BomAbstract* const stdair::PosChannel::getParent () const inline
Get a reference on the parent object instance.
Definition at line 74 of file PosChannel.hpp.
References _parent.
const stdair::HolderMap_T& stdair::PosChannel::getHolderMap () const inline
Get a reference on the children holder.
Definition at line 81 of file PosChannel.hpp.
References _holderMap.
const CityCode_T& stdair::PosChannel::getPos () const inline
Get the point-of-sale.
Definition at line 88 of file PosChannel.hpp.
References _key, and stdair::PosChannelKey::getPos().
const ChannelLabel_T& stdair::PosChannel::getChannel () const inline
Get the channel.
Definition at line 95 of file PosChannel.hpp.
References _key, and stdair::PosChannelKey::getChannel().
Friends And Related Function Documentation
template<typename BOM > friend class FacBom friend
Definition at line 20 of file PosChannel.hpp.
template<typename BOM > friend class FacCloneBom friend
Definition at line 21 of file PosChannel.hpp.
friend class FacBomManager friend
Definition at line 22 of file PosChannel.hpp.
Member Data Documentation
Key_T stdair::PosChannel::_key protected
Primary key (flight number and departure date).
Definition at line 127 of file PosChannel.hpp.
Referenced by describeKey(), getChannel(), getKey(), and getPos().
BomAbstract* stdair::PosChannel::_parent protected
Pointer on the parent class.
Definition at line 132 of file PosChannel.hpp.
Referenced by getParent().
HolderMap_T stdair::PosChannel::_holderMap protected
Map holding the children.
Definition at line 137 of file PosChannel.hpp.
Referenced by getHolderMap().
The documentation for this class was generated from the following files:
stdair/bom/PosChannel.hpp
stdair/bom/PosChannel.cpp