stdair::DBManagerForAirlines Class Reference
stdair::DBManagerForAirlines Class Reference
#include <stdair/command/DBManagerForAirlines.hpp>
Static Public Member Functions
static void updateAirlineInDB (DBSession_T &, const AirlineStruct &)
static bool retrieveAirline (DBSession_T &, const AirlineCode_T &, AirlineStruct &)
static void prepareSelectStatement (DBSession_T &, DBRequestStatement_T &, AirlineStruct &)
static bool iterateOnStatement (DBRequestStatement_T &, AirlineStruct &)
Detailed Description
Class building the Business Object Model (BOM) from data retrieved from the database.
Definition at line 18 of file DBManagerForAirlines.hpp.
Member Function Documentation
void stdair::DBManagerForAirlines::updateAirlineInDB (DBSession_T & ioSociSession, const AirlineStruct & iAirline) static
Update the fields of the database row corresponding to the given BOM object. DBSession_T& AirlineStruct& .
Definition at line 99 of file DBManagerForAirlines.cpp.
References stdair::AirlineStruct::getAirlineCode(), and stdair::AirlineStruct::getAirlineName().
bool stdair::DBManagerForAirlines::retrieveAirline (DBSession_T & ioSociSession, const AirlineCode_T & iAirlineCode, AirlineStruct & ioAirline) static
Retrieve, from the (MySQL) database, the row corresponding to the given BOM code, and fill the given BOM object with that retrieved data. DBSession_T& const AirlineCode_T& AirlineStruct& .
Definition at line 134 of file DBManagerForAirlines.cpp.
References iterateOnStatement().
void stdair::DBManagerForAirlines::prepareSelectStatement (DBSession_T & ioSociSession, DBRequestStatement_T & ioSelectStatement, AirlineStruct & ioAirline) static
Prepare (parse and put in cache) the SQL statement. DBSession_T& DBRequestStatement_T& AirlineStruct& .
Definition at line 26 of file DBManagerForAirlines.cpp.
bool stdair::DBManagerForAirlines::iterateOnStatement (DBRequestStatement_T & ioStatement, AirlineStruct & ioAirline) static
Iterate on the SQL statement.
The SQL has to be already prepared. DBRequestStatement_T& AirlineStruct& .
Definition at line 82 of file DBManagerForAirlines.cpp.
Referenced by retrieveAirline().
The documentation for this class was generated from the following files:
stdair/command/DBManagerForAirlines.hpp
stdair/command/DBManagerForAirlines.cpp