stdair::NestingStructureKey Struct Reference
stdair::NestingStructureKey Struct Reference
Key of a given policy, made of a policy code.
#include <stdair/bom/NestingStructureKey.hpp>
Public Member Functions
NestingStructureKey (const NestingStructureCode_T &iNestingStructureCode)
NestingStructureKey (const NestingStructureKey &)
~NestingStructureKey ()
const NestingStructureCode_T & getNestingStructureCode () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
template<class Archive >
void serialize (Archive &ar, const unsigned int iFileVersion)
Friends
class boost::serialization::access
Detailed Description
Key of a given policy, made of a policy code.
Definition at line 26 of file NestingStructureKey.hpp.
Constructor & Destructor Documentation
stdair::NestingStructureKey::NestingStructureKey (const NestingStructureCode_T & iNestingStructureCode)
Constructor.
Definition at line 28 of file NestingStructureKey.cpp.
stdair::NestingStructureKey::NestingStructureKey (const NestingStructureKey & iNestingStructureKey)
Copy constructor.
Definition at line 23 of file NestingStructureKey.cpp.
stdair::NestingStructureKey::~NestingStructureKey ()
Destructor.
Definition at line 33 of file NestingStructureKey.cpp.
Member Function Documentation
const NestingStructureCode_T& stdair::NestingStructureKey::getNestingStructureCode () const inline
Get the nesting structure code.
Definition at line 56 of file NestingStructureKey.hpp.
void stdair::NestingStructureKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 37 of file NestingStructureKey.cpp.
References toString().
void stdair::NestingStructureKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 42 of file NestingStructureKey.cpp.
const std::string stdair::NestingStructureKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-date.
Reimplemented from stdair::KeyAbstract.
Definition at line 46 of file NestingStructureKey.cpp.
Referenced by stdair::SimpleNestingStructure::describeKey(), and toStream().
template<class Archive > void stdair::NestingStructureKey::serialize (Archive & ar, const unsigned int iFileVersion)
Serialisation.
Definition at line 68 of file NestingStructureKey.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 27 of file NestingStructureKey.hpp.
The documentation for this struct was generated from the following files:
stdair/bom/NestingStructureKey.hpp
stdair/bom/NestingStructureKey.cpp