stdair::ForecastingMethod Struct Reference
stdair::ForecastingMethod Struct Reference
#include <stdair/basic/ForecastingMethod.hpp>
Public Types
enum EN_ForecastingMethod {
Q_FORECASTING = 0, HYBRID_FORECASTING, OLD_QFF, NEW_QFF,
BASED_FORECASTING, LAST_VALUE
}
Public Member Functions
EN_ForecastingMethod getMethod () const
std::string getMethodAsString () const
const std::string describe () const
bool operator== (const EN_ForecastingMethod &) const
ForecastingMethod (const EN_ForecastingMethod &)
ForecastingMethod (const char iMethod)
ForecastingMethod (const ForecastingMethod &)
void toStream (std::ostream &ioOut) const
virtual void fromStream (std::istream &ioIn)
Static Public Member Functions
static const std::string & getLabel (const EN_ForecastingMethod &)
static char getMethodLabel (const EN_ForecastingMethod &)
static std::string getMethodLabelAsString (const EN_ForecastingMethod &)
static std::string describeLabels ()
Detailed Description
Enumeration of forecasting methods.
Definition at line 15 of file ForecastingMethod.hpp.
Member Enumeration Documentation
enum stdair::ForecastingMethod::EN_ForecastingMethod
Enumerator
Q_FORECASTING
HYBRID_FORECASTING
OLD_QFF
NEW_QFF
BASED_FORECASTING
LAST_VALUE
Definition at line 17 of file ForecastingMethod.hpp.
Constructor & Destructor Documentation
stdair::ForecastingMethod::ForecastingMethod (const EN_ForecastingMethod & iForecastingMethod)
Constructor.
Definition at line 37 of file ForecastingMethod.cpp.
stdair::ForecastingMethod::ForecastingMethod (const char iMethod)
Constructor.
Definition at line 42 of file ForecastingMethod.cpp.
References BASED_FORECASTING, describeLabels(), HYBRID_FORECASTING, LAST_VALUE, NEW_QFF, OLD_QFF, and Q_FORECASTING.
stdair::ForecastingMethod::ForecastingMethod (const ForecastingMethod & iForecastingMethod)
Default copy constructor.
Definition at line 31 of file ForecastingMethod.cpp.
Member Function Documentation
const std::string & stdair::ForecastingMethod::getLabel (const EN_ForecastingMethod & iMethod) static
Get the label as a string (e.g., "Q Forecasting", "Hybrid Forecasting", "Old QFF" or "New QFF").
Definition at line 63 of file ForecastingMethod.cpp.
char stdair::ForecastingMethod::getMethodLabel (const EN_ForecastingMethod & iMethod) static
Get the label as a single char (e.g., 'Q', 'H', 'O', 'N' or 'B').
Definition at line 68 of file ForecastingMethod.cpp.
std::string stdair::ForecastingMethod::getMethodLabelAsString (const EN_ForecastingMethod & iMethod) static
Get the label as a string of a single char (e.g., "Q", "H", "O", "N" or "B").
Definition at line 74 of file ForecastingMethod.cpp.
std::string stdair::ForecastingMethod::describeLabels () static
List the labels.
Definition at line 81 of file ForecastingMethod.cpp.
References LAST_VALUE.
Referenced by ForecastingMethod().
ForecastingMethod::EN_ForecastingMethod stdair::ForecastingMethod::getMethod () const
Get the enumerated value.
Definition at line 93 of file ForecastingMethod.cpp.
Referenced by stdair::AirlineFeature::getForecastingMethod().
std::string stdair::ForecastingMethod::getMethodAsString () const
Get the enumerated value as a short string (e.g., "Q", "H", "O", "N" or "B").
Definition at line 98 of file ForecastingMethod.cpp.
const std::string stdair::ForecastingMethod::describe () const virtual
Give a description of the structure (e.g., "Q Forecasting", "Hybrid Forecasting, "Old QFF", "New QFF" or "Based Forecasting").
Implements stdair::StructAbstract.
Definition at line 105 of file ForecastingMethod.cpp.
bool stdair::ForecastingMethod::operator== (const EN_ForecastingMethod & iMethod) const
Comparison operator.
Definition at line 113 of file ForecastingMethod.cpp.
void stdair::StructAbstract::toStream (std::ostream & ioOut) const inline inherited
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 29 of file StructAbstract.hpp.
References stdair::StructAbstract::describe().
virtual void stdair::StructAbstract::fromStream (std::istream & ioIn) inline virtual inherited
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented in stdair::BookingRequestStruct, stdair::EventStruct, stdair::TravelSolutionStruct, stdair::VirtualClassStruct, stdair::ConfigHolderStruct, stdair::FareOptionStruct, stdair::OptimisationNotificationStruct, stdair::ProgressStatusSet, stdair::YieldRange, stdair::CancellationStruct, stdair::AirlineStruct, stdair::RMEventStruct, stdair::SnapshotStruct, stdair::FFDisutilityCurveHolderStruct, stdair::FRAT5CurveHolderStruct, and stdair::BreakPointStruct.
Definition at line 38 of file StructAbstract.hpp.
Referenced by operator>>().
The documentation for this struct was generated from the following files:
stdair/basic/ForecastingMethod.hpp
stdair/basic/ForecastingMethod.cpp