stdair::ProgressStatusSet Struct Reference
stdair::ProgressStatusSet Struct Reference
#include <stdair/basic/ProgressStatusSet.hpp>
Public Member Functions
const ProgressStatus & getTypeSpecificStatus () const
const ProgressStatus & getSpecificGeneratorStatus () const
const ProgressStatus & getOverallStatus () const
void setTypeSpecificStatus (const ProgressStatus &iProgressStatus)
void setSpecificGeneratorStatus (const ProgressStatus &iProgressStatus, const EventGeneratorKey_T &iKey)
void setOverallStatus (const ProgressStatus &iProgressStatus)
void fromStream (std::istream &ioIn)
const std::string describe () const
ProgressStatusSet (const EventType::EN_EventType &)
ProgressStatusSet (const ProgressStatusSet &)
~ProgressStatusSet ()
void toStream (std::ostream &ioOut) const
Detailed Description
Structrure holding a set of progress status.
Definition at line 22 of file ProgressStatusSet.hpp.
Constructor & Destructor Documentation
stdair::ProgressStatusSet::ProgressStatusSet (const EventType::EN_EventType & iType)
Constructor .
Definition at line 20 of file ProgressStatusSet.cpp.
stdair::ProgressStatusSet::ProgressStatusSet (const ProgressStatusSet & iProgressStatusSet)
Copy constructor.
Definition at line 27 of file ProgressStatusSet.cpp.
stdair::ProgressStatusSet::~ProgressStatusSet ()
Destructor.
Definition at line 36 of file ProgressStatusSet.cpp.
Member Function Documentation
const ProgressStatus& stdair::ProgressStatusSet::getTypeSpecificStatus () const inline
Get the progress status specific to that event type.
Note that that progress status may not be up-to-date. That attribute is up-to-date only after a call to the popEvent() method of SEvMgr.
Definition at line 31 of file ProgressStatusSet.hpp.
const ProgressStatus& stdair::ProgressStatusSet::getSpecificGeneratorStatus () const inline
Get the progress status specific to the content key for that event.
Note that that progress status may not be up-to-date. That attribute is up-to-date only after a call to the popEvent() method of SEvMgr.
Definition at line 43 of file ProgressStatusSet.hpp.
const ProgressStatus& stdair::ProgressStatusSet::getOverallStatus () const inline
Get the overall progress status (absolute, for all the events).
Note that that progress status may not be up-to-date. That attribute is up-to-date only after a call to the popEvent() method of SEvMgr.
Definition at line 54 of file ProgressStatusSet.hpp.
void stdair::ProgressStatusSet::setTypeSpecificStatus (const ProgressStatus & iProgressStatus) inline
Set/update the progress status specific to that event type.
Definition at line 62 of file ProgressStatusSet.hpp.
void stdair::ProgressStatusSet::setSpecificGeneratorStatus (const ProgressStatus & iProgressStatus, const EventGeneratorKey_T & iKey) inline
Set/update the progress status specific to the content key for that event.
Definition at line 68 of file ProgressStatusSet.hpp.
void stdair::ProgressStatusSet::setOverallStatus (const ProgressStatus & iProgressStatus) inline
Set/update the overall progress status (absolute, for all the events).
Definition at line 76 of file ProgressStatusSet.hpp.
void stdair::ProgressStatusSet::fromStream (std::istream & ioIn) virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::StructAbstract.
Definition at line 40 of file ProgressStatusSet.cpp.
const std::string stdair::ProgressStatusSet::describe () const virtual
Display of the structure.
Implements stdair::StructAbstract.
Definition at line 44 of file ProgressStatusSet.cpp.
References stdair::ProgressStatus::getActualNb(), stdair::ProgressStatus::getCurrentNb(), and stdair::ProgressStatus::getExpectedNb().
void stdair::StructAbstract::toStream (std::ostream & ioOut) const inline inherited
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 29 of file StructAbstract.hpp.
References stdair::StructAbstract::describe().
The documentation for this struct was generated from the following files:
stdair/basic/ProgressStatusSet.hpp
stdair/basic/ProgressStatusSet.cpp