stdair::PassengerType Struct Reference
stdair::PassengerType Struct Reference
#include <stdair/basic/PassengerType.hpp>
Public Types
enum EN_PassengerType { LEISURE = 0, BUSINESS, FIRST, LAST_VALUE }
Public Member Functions
EN_PassengerType getType () const
std::string getTypeAsString () const
const std::string describe () const
bool operator== (const EN_PassengerType &) const
PassengerType (const EN_PassengerType &)
PassengerType (const char iType)
void toStream (std::ostream &ioOut) const
virtual void fromStream (std::istream &ioIn)
Static Public Member Functions
static const std::string & getLabel (const EN_PassengerType &)
static char getTypeLabel (const EN_PassengerType &)
static std::string getTypeLabelAsString (const EN_PassengerType &)
static std::string describeLabels ()
Detailed Description
Enumeration of Frequent Flyer types.
Definition at line 15 of file PassengerType.hpp.
Member Enumeration Documentation
enum stdair::PassengerType::EN_PassengerType
Enumerator
LEISURE
BUSINESS
FIRST
LAST_VALUE
Definition at line 17 of file PassengerType.hpp.
Constructor & Destructor Documentation
stdair::PassengerType::PassengerType (const EN_PassengerType & iPassengerType)
Constructor.
Definition at line 21 of file PassengerType.cpp.
stdair::PassengerType::PassengerType (const char iType)
Constructor.
Definition at line 26 of file PassengerType.cpp.
References BUSINESS, describeLabels(), FIRST, LAST_VALUE, and LEISURE.
Member Function Documentation
const std::string & stdair::PassengerType::getLabel (const EN_PassengerType & iType) static
Get the label as a string (e.g., "Leisure" or "Business").
Definition at line 44 of file PassengerType.cpp.
char stdair::PassengerType::getTypeLabel (const EN_PassengerType & iType) static
Get the label as a single char (e.g., 'L' or 'B').
Definition at line 49 of file PassengerType.cpp.
std::string stdair::PassengerType::getTypeLabelAsString (const EN_PassengerType & iType) static
Get the label as a single char (e.g., 'L' or 'B').
Definition at line 55 of file PassengerType.cpp.
std::string stdair::PassengerType::describeLabels () static
List the labels.
Definition at line 62 of file PassengerType.cpp.
References LAST_VALUE.
Referenced by PassengerType().
PassengerType::EN_PassengerType stdair::PassengerType::getType () const
Get the enumerated value.
Definition at line 74 of file PassengerType.cpp.
std::string stdair::PassengerType::getTypeAsString () const
Get the enumerated value as a short string (e.g., 'L' or 'B').
Definition at line 79 of file PassengerType.cpp.
const std::string stdair::PassengerType::describe () const virtual
Give a description of the structure (e.g., "Leisure" or "Business").
Implements stdair::StructAbstract.
Definition at line 86 of file PassengerType.cpp.
bool stdair::PassengerType::operator== (const EN_PassengerType & iType) const
Comparison operator.
Definition at line 93 of file PassengerType.cpp.
void stdair::StructAbstract::toStream (std::ostream & ioOut) const inline inherited
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 29 of file StructAbstract.hpp.
References stdair::StructAbstract::describe().
virtual void stdair::StructAbstract::fromStream (std::istream & ioIn) inline virtual inherited
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented in stdair::BookingRequestStruct, stdair::EventStruct, stdair::TravelSolutionStruct, stdair::VirtualClassStruct, stdair::ConfigHolderStruct, stdair::FareOptionStruct, stdair::OptimisationNotificationStruct, stdair::ProgressStatusSet, stdair::YieldRange, stdair::CancellationStruct, stdair::AirlineStruct, stdair::RMEventStruct, stdair::SnapshotStruct, stdair::FFDisutilityCurveHolderStruct, stdair::FRAT5CurveHolderStruct, and stdair::BreakPointStruct.
Definition at line 38 of file StructAbstract.hpp.
Referenced by operator>>().
The documentation for this struct was generated from the following files:
stdair/basic/PassengerType.hpp
stdair/basic/PassengerType.cpp