stdair::ParsedKey Struct Reference
stdair::ParsedKey Struct Reference
#include <stdair/bom/ParsedKey.hpp>
Public Member Functions
InventoryKey getInventoryKey () const
FlightDateKey getFlightDateKey () const
SegmentDateKey getSegmentKey () const
LegDateKey getLegKey () const
const Duration_T getBoardingTime () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
ParsedKey ()
~ParsedKey ()
Public Attributes
std::string _fullKey
std::string _airlineCode
std::string _flightNumber
std::string _departureDate
std::string _boardingPoint
std::string _offPoint
std::string _boardingTime
Detailed Description
Structure which holds the results/keys after the parsing.
Definition at line 22 of file ParsedKey.hpp.
Constructor & Destructor Documentation
stdair::ParsedKey::ParsedKey ()
Definition at line 41 of file ParsedKey.cpp.
stdair::ParsedKey::~ParsedKey ()
Definition at line 47 of file ParsedKey.cpp.
Member Function Documentation
InventoryKey stdair::ParsedKey::getInventoryKey () const
Inventory key.
Definition at line 51 of file ParsedKey.cpp.
References _airlineCode, _fullKey, STDAIR_LOG_DEBUG, STDAIR_LOG_ERROR, and toString().
Referenced by stdair::BomKeyManager::extractInventoryKey().
FlightDateKey stdair::ParsedKey::getFlightDateKey () const
Flight-date key.
Definition at line 62 of file ParsedKey.cpp.
References _departureDate, _flightNumber, _fullKey, STDAIR_LOG_DEBUG, STDAIR_LOG_ERROR, stdair::TokeniserDashSeparator(), and toString().
Referenced by stdair::BomKeyManager::extractFlightDateKey(), and stdair::BomRetriever::retrieveSegmentDateFromLongKey().
SegmentDateKey stdair::ParsedKey::getSegmentKey () const
Segment-date key.
Definition at line 98 of file ParsedKey.cpp.
References _boardingPoint, _fullKey, _offPoint, STDAIR_LOG_DEBUG, STDAIR_LOG_ERROR, and toString().
Referenced by stdair::BomKeyManager::extractSegmentDateKey(), and stdair::BomRetriever::retrieveSegmentDateFromLongKey().
LegDateKey stdair::ParsedKey::getLegKey () const
Leg-date key.
Definition at line 84 of file ParsedKey.cpp.
References _boardingPoint, _fullKey, STDAIR_LOG_DEBUG, STDAIR_LOG_ERROR, and toString().
Referenced by stdair::BomKeyManager::extractLegDateKey().
const Duration_T stdair::ParsedKey::getBoardingTime () const
Boarding time.
Definition at line 112 of file ParsedKey.cpp.
References _boardingTime, _fullKey, STDAIR_LOG_DEBUG, STDAIR_LOG_ERROR, stdair::TokeniserTimeSeparator(), and toString().
void stdair::ParsedKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 130 of file ParsedKey.cpp.
References toString().
void stdair::ParsedKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 135 of file ParsedKey.cpp.
const std::string stdair::ParsedKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-date.
Reimplemented from stdair::KeyAbstract.
Definition at line 139 of file ParsedKey.cpp.
References _airlineCode, _boardingPoint, _boardingTime, _departureDate, _flightNumber, _offPoint, stdair::DEFAULT_KEY_FLD_DELIMITER, and stdair::DEFAULT_KEY_SUB_FLD_DELIMITER.
Referenced by stdair::TravelSolutionStruct::describe(), stdair::TravelSolutionStruct::describeSegmentPath(), stdair::TravelSolutionStruct::display(), getBoardingTime(), getFlightDateKey(), getInventoryKey(), getLegKey(), getSegmentKey(), and toStream().
Member Data Documentation
std::string stdair::ParsedKey::_fullKey
Definition at line 76 of file ParsedKey.hpp.
Referenced by stdair::BomKeyManager::extractKeys(), getBoardingTime(), getFlightDateKey(), getInventoryKey(), getLegKey(), and getSegmentKey().
std::string stdair::ParsedKey::_airlineCode
Definition at line 77 of file ParsedKey.hpp.
Referenced by stdair::BomKeyManager::extractKeys(), getInventoryKey(), stdair::BomRetriever::retrieveSegmentDateFromLongKey(), and toString().
std::string stdair::ParsedKey::_flightNumber
Definition at line 78 of file ParsedKey.hpp.
Referenced by stdair::BomKeyManager::extractKeys(), getFlightDateKey(), and toString().
std::string stdair::ParsedKey::_departureDate
Definition at line 79 of file ParsedKey.hpp.
Referenced by stdair::BomKeyManager::extractKeys(), getFlightDateKey(), and toString().
std::string stdair::ParsedKey::_boardingPoint
Definition at line 80 of file ParsedKey.hpp.
Referenced by stdair::BomKeyManager::extractKeys(), getLegKey(), getSegmentKey(), and toString().
std::string stdair::ParsedKey::_offPoint
Definition at line 81 of file ParsedKey.hpp.
Referenced by stdair::BomKeyManager::extractKeys(), getSegmentKey(), and toString().
std::string stdair::ParsedKey::_boardingTime
Definition at line 82 of file ParsedKey.hpp.
Referenced by stdair::BomKeyManager::extractKeys(), getBoardingTime(), and toString().
The documentation for this struct was generated from the following files:
stdair/bom/ParsedKey.hpp
stdair/bom/ParsedKey.cpp