stdair::FlightPeriod Class Reference
stdair::FlightPeriod Class Reference
#include <stdair/bom/FlightPeriod.hpp>
Public Types
typedef FlightPeriodKey Key_T
Public Member Functions
const Key_T & getKey () const
BomAbstract *const getParent () const
const FlightNumber_T & getFlightNumber () const
const PeriodStruct & getPeriod () const
const HolderMap_T & getHolderMap () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
std::string toString () const
const std::string describeKey () const
Protected Member Functions
FlightPeriod (const Key_T &)
~FlightPeriod ()
Protected Attributes
Key_T _key
BomAbstract * _parent
HolderMap_T _holderMap
Friends
template<typename BOM >
class FacBom
template<typename BOM >
class FacCloneBom
class FacBomManager
Detailed Description
Class representing the actual attributes for an airline flight-period.
Definition at line 15 of file FlightPeriod.hpp.
Member Typedef Documentation
typedef FlightPeriodKey stdair::FlightPeriod::Key_T
Definition allowing to retrieve the associated BOM key type.
Definition at line 23 of file FlightPeriod.hpp.
Constructor & Destructor Documentation
stdair::FlightPeriod::FlightPeriod (const Key_T & iKey) protected
Main constructor.
Definition at line 12 of file FlightPeriod.cpp.
stdair::FlightPeriod::~FlightPeriod () protected
Destructor.
Definition at line 22 of file FlightPeriod.cpp.
Member Function Documentation
const Key_T& stdair::FlightPeriod::getKey () const inline
Get the flight-period key.
Definition at line 28 of file FlightPeriod.hpp.
References _key.
BomAbstract* const stdair::FlightPeriod::getParent () const inline
Get the parent object.
Definition at line 31 of file FlightPeriod.hpp.
References _parent.
const FlightNumber_T& stdair::FlightPeriod::getFlightNumber () const inline
Get the flight number (part of the primary key).
Definition at line 34 of file FlightPeriod.hpp.
References _key, and stdair::FlightPeriodKey::getFlightNumber().
const PeriodStruct& stdair::FlightPeriod::getPeriod () const inline
Get the departure period (part of the key).
Definition at line 39 of file FlightPeriod.hpp.
References _key, and stdair::FlightPeriodKey::getPeriod().
const HolderMap_T& stdair::FlightPeriod::getHolderMap () const inline
Get the map of children holders.
Definition at line 42 of file FlightPeriod.hpp.
References _holderMap.
void stdair::FlightPeriod::toStream (std::ostream & ioOut) const inline virtual
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Implements stdair::BomAbstract.
Definition at line 49 of file FlightPeriod.hpp.
References toString().
void stdair::FlightPeriod::fromStream (std::istream & ioIn) inline virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Implements stdair::BomAbstract.
Definition at line 53 of file FlightPeriod.hpp.
std::string stdair::FlightPeriod::toString () const virtual
Get the serialised version of the Business Object.
Implements stdair::BomAbstract.
Definition at line 26 of file FlightPeriod.cpp.
References describeKey().
Referenced by toStream().
const std::string stdair::FlightPeriod::describeKey () const inline
Get a string describing the key.
Definition at line 59 of file FlightPeriod.hpp.
References _key, and stdair::FlightPeriodKey::toString().
Referenced by toString().
Friends And Related Function Documentation
template<typename BOM > friend class FacBom friend
Definition at line 16 of file FlightPeriod.hpp.
template<typename BOM > friend class FacCloneBom friend
Definition at line 17 of file FlightPeriod.hpp.
friend class FacBomManager friend
Definition at line 18 of file FlightPeriod.hpp.
Member Data Documentation
Key_T stdair::FlightPeriod::_key protected
Definition at line 86 of file FlightPeriod.hpp.
Referenced by describeKey(), getFlightNumber(), getKey(), and getPeriod().
BomAbstract* stdair::FlightPeriod::_parent protected
Definition at line 87 of file FlightPeriod.hpp.
Referenced by getParent().
HolderMap_T stdair::FlightPeriod::_holderMap protected
Definition at line 88 of file FlightPeriod.hpp.
Referenced by getHolderMap().
The documentation for this class was generated from the following files:
stdair/bom/FlightPeriod.hpp
stdair/bom/FlightPeriod.cpp