stdair::SampleType Struct Reference
stdair::SampleType Struct Reference
Enumeration of BOM sample types.
#include <stdair/basic/SampleType.hpp>
Public Types
enum EN_SampleType {
ALL = 0, A4P, RMS, INV,
SCH, RAC, FQT, CRS,
DEM, EVT, CCM, LAST_VALUE
}
Public Member Functions
EN_SampleType getType () const
std::string getTypeAsString () const
const std::string describe () const
bool operator== (const EN_SampleType &) const
SampleType (const EN_SampleType &)
SampleType (const char iType)
SampleType (const SampleType &)
void toStream (std::ostream &ioOut) const
virtual void fromStream (std::istream &ioIn)
Static Public Member Functions
static const std::string & getLabel (const EN_SampleType &)
static char getTypeLabel (const EN_SampleType &)
static std::string getTypeLabelAsString (const EN_SampleType &)
static std::string describeLabels ()
Detailed Description
Enumeration of BOM sample types.
In order to test some components, it is often easier to fill the BOM tree with hard-coded structures than set up CSV input files and parsing them. That enumeration structure tells for which component(s) the sample BOM tree should be built. By default, a BOM sample tree is built for all the components, i.e., it contains StdAir objects for all the other components (AirInv, AirSched, etc).
Definition at line 25 of file SampleType.hpp.
Member Enumeration Documentation
enum stdair::SampleType::EN_SampleType
Enumerator
ALL
A4P
RMS
INV
SCH
RAC
FQT
CRS
DEM
EVT
CCM
LAST_VALUE
Definition at line 27 of file SampleType.hpp.
Constructor & Destructor Documentation
stdair::SampleType::SampleType (const EN_SampleType & iSampleType)
Constructor.
Definition at line 36 of file SampleType.cpp.
stdair::SampleType::SampleType (const char iType)
Constructor.
Definition at line 41 of file SampleType.cpp.
References A4P, ALL, CCM, CRS, DEM, describeLabels(), EVT, FQT, INV, LAST_VALUE, RAC, RMS, and SCH.
stdair::SampleType::SampleType (const SampleType & iSampleType)
Default copy constructor.
Definition at line 31 of file SampleType.cpp.
Member Function Documentation
const std::string & stdair::SampleType::getLabel (const EN_SampleType & iType) static
Get the label as a string (e.g., "Inventory" or "Schedule").
Definition at line 67 of file SampleType.cpp.
char stdair::SampleType::getTypeLabel (const EN_SampleType & iType) static
Get the label as a single char (e.g., 'I' or 'S').
Definition at line 72 of file SampleType.cpp.
std::string stdair::SampleType::getTypeLabelAsString (const EN_SampleType & iType) static
Get the label as a string of a single char (e.g., "I" or "S").
Definition at line 77 of file SampleType.cpp.
std::string stdair::SampleType::describeLabels () static
List the labels.
Definition at line 84 of file SampleType.cpp.
References LAST_VALUE.
Referenced by SampleType().
SampleType::EN_SampleType stdair::SampleType::getType () const
Get the enumerated value.
Definition at line 96 of file SampleType.cpp.
std::string stdair::SampleType::getTypeAsString () const
Get the enumerated value as a short string (e.g., "I" or "S").
Definition at line 101 of file SampleType.cpp.
const std::string stdair::SampleType::describe () const virtual
Give a description of the structure (e.g., "Inventory" or "Schedule").
Implements stdair::StructAbstract.
Definition at line 108 of file SampleType.cpp.
bool stdair::SampleType::operator== (const EN_SampleType & iType) const
Comparison operator.
Definition at line 115 of file SampleType.cpp.
void stdair::StructAbstract::toStream (std::ostream & ioOut) const inline inherited
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 29 of file StructAbstract.hpp.
References stdair::StructAbstract::describe().
virtual void stdair::StructAbstract::fromStream (std::istream & ioIn) inline virtual inherited
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented in stdair::BookingRequestStruct, stdair::EventStruct, stdair::TravelSolutionStruct, stdair::VirtualClassStruct, stdair::ConfigHolderStruct, stdair::FareOptionStruct, stdair::OptimisationNotificationStruct, stdair::ProgressStatusSet, stdair::YieldRange, stdair::CancellationStruct, stdair::AirlineStruct, stdair::RMEventStruct, stdair::SnapshotStruct, stdair::FFDisutilityCurveHolderStruct, stdair::FRAT5CurveHolderStruct, and stdair::BreakPointStruct.
Definition at line 38 of file StructAbstract.hpp.
Referenced by operator>>().
The documentation for this struct was generated from the following files:
stdair/basic/SampleType.hpp
stdair/basic/SampleType.cpp