stdair::PartnershipTechnique Struct Reference
stdair::PartnershipTechnique Struct Reference
Enumeration of partnership techniques.
#include <stdair/basic/PartnershipTechnique.hpp>
Public Types
enum EN_PartnershipTechnique {
NONE = 0, RAE_DA, RAE_YP, IBP_DA,
IBP_YP, IBP_YP_U, RMC, A_RMC,
LAST_VALUE
}
Public Member Functions
EN_PartnershipTechnique getTechnique () const
char getTechniqueAsChar () const
std::string getTechniqueAsString () const
const std::string describe () const
bool operator== (const EN_PartnershipTechnique &) const
PartnershipTechnique (const EN_PartnershipTechnique &)
PartnershipTechnique (const char iTechnique)
PartnershipTechnique (const std::string &iTechnique)
PartnershipTechnique (const PartnershipTechnique &)
void toStream (std::ostream &ioOut) const
virtual void fromStream (std::istream &ioIn)
Static Public Member Functions
static const std::string & getLabel (const EN_PartnershipTechnique &)
static EN_PartnershipTechnique getTechnique (const char)
static char getTechniqueLabel (const EN_PartnershipTechnique &)
static std::string getTechniqueLabelAsString (const EN_PartnershipTechnique &)
static std::string describeLabels ()
Detailed Description
Enumeration of partnership techniques.
Definition at line 17 of file PartnershipTechnique.hpp.
Member Enumeration Documentation
enum stdair::PartnershipTechnique::EN_PartnershipTechnique
Enumerator
NONE
RAE_DA
RAE_YP
IBP_DA
IBP_YP
IBP_YP_U
RMC
A_RMC
LAST_VALUE
Definition at line 19 of file PartnershipTechnique.hpp.
Constructor & Destructor Documentation
stdair::PartnershipTechnique::PartnershipTechnique (const EN_PartnershipTechnique & iPartnershipTechnique)
Main constructor.
Definition at line 48 of file PartnershipTechnique.cpp.
stdair::PartnershipTechnique::PartnershipTechnique (const char iTechnique)
Alternative constructor.
Definition at line 82 of file PartnershipTechnique.cpp.
stdair::PartnershipTechnique::PartnershipTechnique (const std::string & iTechnique)
Alternative constructor.
Definition at line 88 of file PartnershipTechnique.cpp.
References getTechnique().
stdair::PartnershipTechnique::PartnershipTechnique (const PartnershipTechnique & iPartnershipTechnique)
Default copy constructor.
Definition at line 42 of file PartnershipTechnique.cpp.
Member Function Documentation
const std::string & stdair::PartnershipTechnique::getLabel (const EN_PartnershipTechnique & iTechnique) static
Get the label as a string (e.g., "RevenueManagementCooperation").
Definition at line 98 of file PartnershipTechnique.cpp.
PartnershipTechnique::EN_PartnershipTechnique stdair::PartnershipTechnique::getTechnique (const char iTechniqueChar) static
Get the technique value from parsing a single char (e.g., 'r' or 'C').
Definition at line 54 of file PartnershipTechnique.cpp.
References A_RMC, describeLabels(), IBP_DA, IBP_YP, IBP_YP_U, LAST_VALUE, NONE, RAE_DA, RAE_YP, and RMC.
Referenced by stdair::AirlineFeature::getPartnershipTechnique().
char stdair::PartnershipTechnique::getTechniqueLabel (const EN_PartnershipTechnique & iTechnique) static
Get the label as a single char (e.g., 'r' or 'C').
Definition at line 104 of file PartnershipTechnique.cpp.
std::string stdair::PartnershipTechnique::getTechniqueLabelAsString (const EN_PartnershipTechnique & iTechnique) static
Get the label as a string of a single char (e.g., "r" or "C").
Definition at line 110 of file PartnershipTechnique.cpp.
std::string stdair::PartnershipTechnique::describeLabels () static
List the labels.
Definition at line 117 of file PartnershipTechnique.cpp.
References LAST_VALUE.
Referenced by getTechnique().
PartnershipTechnique::EN_PartnershipTechnique stdair::PartnershipTechnique::getTechnique () const
Get the enumerated value.
Definition at line 130 of file PartnershipTechnique.cpp.
Referenced by PartnershipTechnique().
char stdair::PartnershipTechnique::getTechniqueAsChar () const
Get the enumerated value as a char (e.g., 'r' or 'C').
Definition at line 135 of file PartnershipTechnique.cpp.
std::string stdair::PartnershipTechnique::getTechniqueAsString () const
Get the enumerated value as a short string (e.g., "r" or "C").
Definition at line 141 of file PartnershipTechnique.cpp.
const std::string stdair::PartnershipTechnique::describe () const virtual
Give a description of the structure (e.g., "RevenueManagementCooperation" or "InterlineBidPriceYieldProration").
Implements stdair::StructAbstract.
Definition at line 148 of file PartnershipTechnique.cpp.
bool stdair::PartnershipTechnique::operator== (const EN_PartnershipTechnique & iTechnique) const
Comparison operator.
Definition at line 156 of file PartnershipTechnique.cpp.
void stdair::StructAbstract::toStream (std::ostream & ioOut) const inline inherited
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 29 of file StructAbstract.hpp.
References stdair::StructAbstract::describe().
virtual void stdair::StructAbstract::fromStream (std::istream & ioIn) inline virtual inherited
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented in stdair::BookingRequestStruct, stdair::EventStruct, stdair::TravelSolutionStruct, stdair::VirtualClassStruct, stdair::ConfigHolderStruct, stdair::FareOptionStruct, stdair::OptimisationNotificationStruct, stdair::ProgressStatusSet, stdair::YieldRange, stdair::CancellationStruct, stdair::AirlineStruct, stdair::RMEventStruct, stdair::SnapshotStruct, stdair::FFDisutilityCurveHolderStruct, stdair::FRAT5CurveHolderStruct, and stdair::BreakPointStruct.
Definition at line 38 of file StructAbstract.hpp.
Referenced by operator>>().
The documentation for this struct was generated from the following files:
stdair/basic/PartnershipTechnique.hpp
stdair/basic/PartnershipTechnique.cpp