stdair::FacBom< BOM > Class Template Reference
stdair::FacBom< BOM > Class Template Reference
Base class for Factory layer.
#include <stdair/factory/FacBom.hpp>
Public Member Functions
BOM & create ()
BOM & create (const Key_T &)
BOM & create (const BOM &)
~FacBom ()
void clean ()
Static Public Member Functions
static FacBom & instance ()
Protected Member Functions
FacBom ()
Detailed Description
template<typename BOM>
class stdair::FacBom< BOM >
Base class for Factory layer.
Definition at line 22 of file FacBom.hpp.
Constructor & Destructor Documentation
template<typename BOM > stdair::FacBom< BOM >::FacBom () inline protected
Default Constructor.
Definition at line 50 of file FacBom.hpp.
template<typename BOM > stdair::FacBom< BOM >::~FacBom () inline
Destructor.
Definition at line 56 of file FacBom.hpp.
References stdair::FacBom< BOM >::clean().
Member Function Documentation
template<typename BOM > FacBom< BOM > & stdair::FacBom< BOM >::instance () static
Provide the unique instance.
The singleton is instantiated when first used.
Returns
FacBom&
Definition at line 84 of file FacBom.hpp.
References stdair::FacSupervisor::instance(), and stdair::FacSupervisor::registerPersistentBomFactory().
template<typename BOM > BOM & stdair::FacBom< BOM >::create ()
Create a BOM object, given a key or not.
Definition at line 112 of file FacBom.hpp.
Referenced by stdair::FacBomManager::addBomHolder().
template<typename BOM > BOM & stdair::FacBom< BOM >::create (const Key_T & iKey)
Definition at line 118 of file FacBom.hpp.
template<typename BOM > BOM & stdair::FacBom< BOM >::create (const BOM & iBom)
Definition at line 126 of file FacBom.hpp.
template<typename BOM > void stdair::FacBom< BOM >::clean ()
Destroyed all the object instantiated by this factory.
Definition at line 95 of file FacBom.hpp.
Referenced by stdair::FacBom< BOM >::~FacBom().
The documentation for this class was generated from the following file:
stdair/factory/FacBom.hpp