stdair::NestingNode Class Reference
stdair::NestingNode Class Reference
#include <stdair/bom/NestingNode.hpp>
Public Types
typedef NestingNodeKey Key_T
Public Member Functions
const Key_T & getKey () const
BomAbstract *const getParent () const
const HolderMap_T & getHolderMap () const
const Yield_T & getYield () const
void setYield (const Yield_T &iYield)
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
std::string toString () const
const std::string describeKey () const
template<class Archive >
void serialize (Archive &ar, const unsigned int iFileVersion)
Protected Member Functions
NestingNode (const Key_T &)
virtual ~NestingNode ()
Friends
template<typename BOM >
class FacBom
class FacBomManager
class boost::serialization::access
Detailed Description
Structure holding the elements of a nesting node. A nesting node is a set of booking classes.
Definition at line 29 of file NestingNode.hpp.
Member Typedef Documentation
typedef NestingNodeKey stdair::NestingNode::Key_T
Definition allowing to retrieve the associated BOM key type.
Definition at line 39 of file NestingNode.hpp.
Constructor & Destructor Documentation
stdair::NestingNode::NestingNode (const Key_T & iKey) protected
Main constructor.
Definition at line 31 of file NestingNode.cpp.
stdair::NestingNode::~NestingNode () protected virtual
Destructor.
Definition at line 35 of file NestingNode.cpp.
Member Function Documentation
const Key_T& stdair::NestingNode::getKey () const inline
Get the policy key.
Definition at line 44 of file NestingNode.hpp.
BomAbstract* const stdair::NestingNode::getParent () const inline
Get the parent object.
Definition at line 49 of file NestingNode.hpp.
const HolderMap_T& stdair::NestingNode::getHolderMap () const inline
Get the map of children holders.
Definition at line 56 of file NestingNode.hpp.
Referenced by stdair::FacBomManager::resetYieldBasedNestingStructure().
const Yield_T& stdair::NestingNode::getYield () const inline
Getter for the yield.
Definition at line 61 of file NestingNode.hpp.
void stdair::NestingNode::setYield (const Yield_T & iYield) inline
Setter for the yield.
Definition at line 68 of file NestingNode.hpp.
Referenced by stdair::FacBomManager::resetYieldBasedNestingStructure().
void stdair::NestingNode::toStream (std::ostream & ioOut) const inline virtual
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Implements stdair::BomAbstract.
Definition at line 80 of file NestingNode.hpp.
References toString().
void stdair::NestingNode::fromStream (std::istream & ioIn) inline virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Implements stdair::BomAbstract.
Definition at line 89 of file NestingNode.hpp.
std::string stdair::NestingNode::toString () const virtual
Get the serialised version of the Business Object.
Implements stdair::BomAbstract.
Definition at line 39 of file NestingNode.cpp.
References describeKey().
Referenced by toStream().
const std::string stdair::NestingNode::describeKey () const inline
Get a string describing the key.
Definition at line 100 of file NestingNode.hpp.
References stdair::NestingNodeKey::toString().
Referenced by stdair::FacBomManager::resetYieldBasedNestingStructure(), and toString().
template<class Archive > void stdair::NestingNode::serialize (Archive & ar, const unsigned int iFileVersion)
Serialisation.
Friends And Related Function Documentation
template<typename BOM > friend class FacBom friend
Definition at line 30 of file NestingNode.hpp.
friend class FacBomManager friend
Definition at line 31 of file NestingNode.hpp.
friend class boost::serialization::access friend
Definition at line 32 of file NestingNode.hpp.
The documentation for this class was generated from the following files:
stdair/bom/NestingNode.hpp
stdair/bom/NestingNode.cpp