stdair::LegDateKey Struct Reference
stdair::LegDateKey Struct Reference
#include <stdair/bom/LegDateKey.hpp>
Public Member Functions
LegDateKey (const AirportCode_T &iBoardingPoint)
LegDateKey (const LegDateKey &)
~LegDateKey ()
const AirportCode_T & getBoardingPoint () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
Detailed Description
Key of a given leg-date, made of an origin airport.
Definition at line 16 of file LegDateKey.hpp.
Constructor & Destructor Documentation
stdair::LegDateKey::LegDateKey (const AirportCode_T & iBoardingPoint)
Constructor.
Definition at line 19 of file LegDateKey.cpp.
stdair::LegDateKey::LegDateKey (const LegDateKey & iKey)
Default copy constructor.
Definition at line 24 of file LegDateKey.cpp.
stdair::LegDateKey::~LegDateKey ()
Destructor.
Definition at line 29 of file LegDateKey.cpp.
Member Function Documentation
const AirportCode_T& stdair::LegDateKey::getBoardingPoint () const inline
Get the boarding point.
Definition at line 34 of file LegDateKey.hpp.
Referenced by stdair::LegDate::getBoardingPoint().
void stdair::LegDateKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 33 of file LegDateKey.cpp.
References toString().
void stdair::LegDateKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 38 of file LegDateKey.cpp.
const std::string stdair::LegDateKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same leg-date.
Reimplemented from stdair::KeyAbstract.
Definition at line 42 of file LegDateKey.cpp.
Referenced by stdair::LegDate::describeKey(), stdair::FlightDate::getLegDate(), and toStream().
The documentation for this struct was generated from the following files:
stdair/bom/LegDateKey.hpp
stdair/bom/LegDateKey.cpp