stdair::FRAT5CurveHolderStruct Struct Reference
stdair::FRAT5CurveHolderStruct Struct Reference
#include <stdair/bom/FRAT5CurveHolderStruct.hpp>
Public Member Functions
const FRAT5Curve_T & getFRAT5Curve (const std::string &) const
void addCurve (const std::string &, const FRAT5Curve_T &)
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string describe () const
FRAT5CurveHolderStruct ()
FRAT5CurveHolderStruct (const FRAT5CurveHolderStruct &)
~FRAT5CurveHolderStruct ()
Detailed Description
Structure holding the elements of a snapshot .
Definition at line 19 of file FRAT5CurveHolderStruct.hpp.
Constructor & Destructor Documentation
stdair::FRAT5CurveHolderStruct::FRAT5CurveHolderStruct ()
Constructor.
Definition at line 14 of file FRAT5CurveHolderStruct.cpp.
stdair::FRAT5CurveHolderStruct::FRAT5CurveHolderStruct (const FRAT5CurveHolderStruct & iHolder)
Copy constructor.
Definition at line 19 of file FRAT5CurveHolderStruct.cpp.
stdair::FRAT5CurveHolderStruct::~FRAT5CurveHolderStruct ()
Destructor.
Definition at line 24 of file FRAT5CurveHolderStruct.cpp.
Member Function Documentation
const FRAT5Curve_T & stdair::FRAT5CurveHolderStruct::getFRAT5Curve (const std::string & iKey) const
Get the FRAT5 curve corresponding to the given key.
Definition at line 29 of file FRAT5CurveHolderStruct.cpp.
References STDAIR_LOG_DEBUG.
Referenced by stdair::BomRoot::getFRAT5Curve().
void stdair::FRAT5CurveHolderStruct::addCurve (const std::string & iKey, const FRAT5Curve_T & iCurve)
Add a new curve to the holder.
Definition at line 42 of file FRAT5CurveHolderStruct.cpp.
References STDAIR_LOG_DEBUG.
Referenced by stdair::BomRoot::addFRAT5Curve().
void stdair::FRAT5CurveHolderStruct::toStream (std::ostream & ioOut) const
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 53 of file FRAT5CurveHolderStruct.cpp.
References describe().
void stdair::FRAT5CurveHolderStruct::fromStream (std::istream & ioIn) virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::StructAbstract.
Definition at line 58 of file FRAT5CurveHolderStruct.cpp.
const std::string stdair::FRAT5CurveHolderStruct::describe () const virtual
Display of the structure.
Implements stdair::StructAbstract.
Definition at line 62 of file FRAT5CurveHolderStruct.cpp.
Referenced by toStream().
The documentation for this struct was generated from the following files:
stdair/bom/FRAT5CurveHolderStruct.hpp
stdair/bom/FRAT5CurveHolderStruct.cpp