stdair::SegmentDateKey Struct Reference
stdair::SegmentDateKey Struct Reference
Key of a given segment-date, made of an origin and a destination airports.
#include <stdair/bom/SegmentDateKey.hpp>
Public Member Functions
SegmentDateKey (const AirportCode_T &, const AirportCode_T &)
SegmentDateKey (const SegmentDateKey &)
~SegmentDateKey ()
const AirportCode_T & getBoardingPoint () const
const AirportCode_T & getOffPoint () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
template<class Archive >
void serialize (Archive &ar, const unsigned int iFileVersion)
Friends
class boost::serialization::access
Detailed Description
Key of a given segment-date, made of an origin and a destination airports.
Definition at line 24 of file SegmentDateKey.hpp.
Constructor & Destructor Documentation
stdair::SegmentDateKey::SegmentDateKey (const AirportCode_T & iBoardingPoint, const AirportCode_T & iOffPoint)
Main constructor.
Definition at line 25 of file SegmentDateKey.cpp.
stdair::SegmentDateKey::SegmentDateKey (const SegmentDateKey & iKey)
Copy constructor.
Definition at line 31 of file SegmentDateKey.cpp.
stdair::SegmentDateKey::~SegmentDateKey ()
Destructor.
Definition at line 36 of file SegmentDateKey.cpp.
Member Function Documentation
const AirportCode_T& stdair::SegmentDateKey::getBoardingPoint () const inline
Get the boardinging point.
Definition at line 51 of file SegmentDateKey.hpp.
Referenced by stdair::SegmentDate::getBoardingPoint(), and stdair::OnDDateKey::getOrigin().
const AirportCode_T& stdair::SegmentDateKey::getOffPoint () const inline
Get the arrival point.
Definition at line 56 of file SegmentDateKey.hpp.
Referenced by stdair::OnDDateKey::getDestination(), and stdair::SegmentDate::getOffPoint().
void stdair::SegmentDateKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 40 of file SegmentDateKey.cpp.
References toString().
void stdair::SegmentDateKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 45 of file SegmentDateKey.cpp.
const std::string stdair::SegmentDateKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-date.
Reimplemented from stdair::KeyAbstract.
Definition at line 49 of file SegmentDateKey.cpp.
References stdair::DEFAULT_KEY_SUB_FLD_DELIMITER.
Referenced by stdair::SegmentDate::describeKey(), stdair::FlightDate::getSegmentDate(), stdair::BomRetriever::retrieveSegmentDateFromLongKey(), and toStream().
template<class Archive > void stdair::SegmentDateKey::serialize (Archive & ar, const unsigned int iFileVersion)
Serialisation.
Definition at line 72 of file SegmentDateKey.cpp.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 25 of file SegmentDateKey.hpp.
The documentation for this struct was generated from the following files:
stdair/bom/SegmentDateKey.hpp
stdair/bom/SegmentDateKey.cpp