stdair::YieldFeaturesKey Struct Reference
stdair::YieldFeaturesKey Struct Reference
Key of date-period.
#include <stdair/bom/YieldFeaturesKey.hpp>
Public Member Functions
YieldFeaturesKey (const TripType_T &, const CabinCode_T &)
YieldFeaturesKey (const YieldFeaturesKey &)
~YieldFeaturesKey ()
const TripType_T & getTripType () const
const CabinCode_T & getCabinCode () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
Detailed Description
Key of date-period.
Definition at line 18 of file YieldFeaturesKey.hpp.
Constructor & Destructor Documentation
stdair::YieldFeaturesKey::YieldFeaturesKey (const TripType_T & iTripType, const CabinCode_T & iCabin)
Main constructor.
Definition at line 21 of file YieldFeaturesKey.cpp.
stdair::YieldFeaturesKey::YieldFeaturesKey (const YieldFeaturesKey & iKey)
Copy constructor.
Definition at line 27 of file YieldFeaturesKey.cpp.
stdair::YieldFeaturesKey::~YieldFeaturesKey ()
Destructor.
Definition at line 32 of file YieldFeaturesKey.cpp.
Member Function Documentation
const TripType_T& stdair::YieldFeaturesKey::getTripType () const inline
Get the fare trip type.
Definition at line 44 of file YieldFeaturesKey.hpp.
Referenced by stdair::YieldFeatures::getTripType().
const CabinCode_T& stdair::YieldFeaturesKey::getCabinCode () const inline
Get the cabin.
Definition at line 51 of file YieldFeaturesKey.hpp.
Referenced by stdair::YieldFeatures::getCabinCode().
void stdair::YieldFeaturesKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 36 of file YieldFeaturesKey.cpp.
References toString().
void stdair::YieldFeaturesKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 41 of file YieldFeaturesKey.cpp.
const std::string stdair::YieldFeaturesKey::toString () const virtual
Get the serialised version of the Business Object Key. That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
Reimplemented from stdair::KeyAbstract.
Definition at line 45 of file YieldFeaturesKey.cpp.
Referenced by stdair::YieldFeatures::describeKey(), and toStream().
The documentation for this struct was generated from the following files:
stdair/bom/YieldFeaturesKey.hpp
stdair/bom/YieldFeaturesKey.cpp