stdair::VirtualClassStruct Struct Reference
stdair::VirtualClassStruct Struct Reference
#include <stdair/bom/VirtualClassStruct.hpp>
Public Member Functions
const BookingClassList_T & getBookingClassList () const
const Yield_T & getYield () const
const MeanValue_T & getMean () const
const StdDevValue_T & getStdDev () const
const BookingLimit_T & getCumulatedBookingLimit () const
const ProtectionLevel_T & getCumulatedProtection () const
const GeneratedDemandVector_T getGeneratedDemandVector () const
void setYield (const Yield_T &iYield)
void setMean (const MeanValue_T &iMean)
void setStdDev (const StdDevValue_T &iStdDev)
void setCumulatedBookingLimit (const BookingLimit_T &iBL)
void setCumulatedProtection (const ProtectionLevel_T &iP)
void addBookingClass (BookingClass &iBookingClass)
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string describe () const
VirtualClassStruct (const VirtualClassStruct &)
VirtualClassStruct (const BookingClassList_T &)
~VirtualClassStruct ()
Detailed Description
Structure holding the elements of a virtual class.
Definition at line 24 of file VirtualClassStruct.hpp.
Constructor & Destructor Documentation
stdair::VirtualClassStruct::VirtualClassStruct (const VirtualClassStruct & iVC)
Default copy constructor.
Definition at line 19 of file VirtualClassStruct.cpp.
stdair::VirtualClassStruct::VirtualClassStruct (const BookingClassList_T & ioBookingClassList)
Constructor.
Definition at line 26 of file VirtualClassStruct.cpp.
stdair::VirtualClassStruct::~VirtualClassStruct ()
Destructor.
Definition at line 31 of file VirtualClassStruct.cpp.
Member Function Documentation
const BookingClassList_T& stdair::VirtualClassStruct::getBookingClassList () const inline
Get the list of booking class.
Definition at line 28 of file VirtualClassStruct.hpp.
const Yield_T& stdair::VirtualClassStruct::getYield () const inline
Get the yield (average price paid for that virtual class).
Definition at line 33 of file VirtualClassStruct.hpp.
Referenced by stdair::LegCabin::displayVirtualClassList().
const MeanValue_T& stdair::VirtualClassStruct::getMean () const inline
Get the mean value of the demand distribution.
Definition at line 38 of file VirtualClassStruct.hpp.
const StdDevValue_T& stdair::VirtualClassStruct::getStdDev () const inline
Get the standard deviation of the demand distribution.
Definition at line 43 of file VirtualClassStruct.hpp.
const BookingLimit_T& stdair::VirtualClassStruct::getCumulatedBookingLimit () const inline
Get the booking limit of the class.
Definition at line 48 of file VirtualClassStruct.hpp.
Referenced by stdair::LegCabin::displayVirtualClassList().
const ProtectionLevel_T& stdair::VirtualClassStruct::getCumulatedProtection () const inline
Get the protection level of the class.
Definition at line 53 of file VirtualClassStruct.hpp.
Referenced by stdair::LegCabin::displayVirtualClassList().
const GeneratedDemandVector_T stdair::VirtualClassStruct::getGeneratedDemandVector () const
Get the generated demand sample vector for Monte-Carlo method.
Definition at line 54 of file VirtualClassStruct.cpp.
References stdair::BookingClass::getGeneratedDemandVector().
void stdair::VirtualClassStruct::setYield (const Yield_T & iYield) inline
Set the yield (average price paid for that virtual class).
Definition at line 63 of file VirtualClassStruct.hpp.
void stdair::VirtualClassStruct::setMean (const MeanValue_T & iMean) inline
Set the mean value of the demand distribution.
Definition at line 68 of file VirtualClassStruct.hpp.
void stdair::VirtualClassStruct::setStdDev (const StdDevValue_T & iStdDev) inline
Set the standard deviation of the demand distribution.
Definition at line 73 of file VirtualClassStruct.hpp.
void stdair::VirtualClassStruct::setCumulatedBookingLimit (const BookingLimit_T & iBL) inline
Set the booking limit of the class.
Definition at line 78 of file VirtualClassStruct.hpp.
void stdair::VirtualClassStruct::setCumulatedProtection (const ProtectionLevel_T & iP) inline
Set the protection level of the class.
Definition at line 83 of file VirtualClassStruct.hpp.
void stdair::VirtualClassStruct::addBookingClass (BookingClass & iBookingClass) inline
Add a booking class to the list of booking classes. Note: it is not a link Parent/Child so we don't use the FacBom. The Virtual Classes are not bom objects because the optimiser needs to build them before each optimisation.
Definition at line 92 of file VirtualClassStruct.hpp.
void stdair::VirtualClassStruct::toStream (std::ostream & ioOut) const
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 36 of file VirtualClassStruct.cpp.
References describe().
void stdair::VirtualClassStruct::fromStream (std::istream & ioIn) virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::StructAbstract.
Definition at line 41 of file VirtualClassStruct.cpp.
const std::string stdair::VirtualClassStruct::describe () const virtual
Display of the structure.
Implements stdair::StructAbstract.
Definition at line 45 of file VirtualClassStruct.cpp.
Referenced by toStream().
The documentation for this struct was generated from the following files:
stdair/bom/VirtualClassStruct.hpp
stdair/bom/VirtualClassStruct.cpp