stdair::TimePeriodKey Struct Reference
stdair::TimePeriodKey Struct Reference
Key of time-period.
#include <stdair/bom/TimePeriodKey.hpp>
Public Member Functions
TimePeriodKey (const Time_T &, const Time_T &)
TimePeriodKey (const TimePeriodKey &)
~TimePeriodKey ()
const Time_T & getTimeRangeStart () const
const Time_T & getTimeRangeEnd () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
Detailed Description
Key of time-period.
Definition at line 15 of file TimePeriodKey.hpp.
Constructor & Destructor Documentation
stdair::TimePeriodKey::TimePeriodKey (const Time_T & iTimeRangeStart, const Time_T & iTimeRangeEnd)
Main constructor.
Definition at line 21 of file TimePeriodKey.cpp.
stdair::TimePeriodKey::TimePeriodKey (const TimePeriodKey & iKey)
Copy constructor.
Definition at line 28 of file TimePeriodKey.cpp.
stdair::TimePeriodKey::~TimePeriodKey ()
Destructor.
Definition at line 34 of file TimePeriodKey.cpp.
Member Function Documentation
const Time_T& stdair::TimePeriodKey::getTimeRangeStart () const inline
Get the time period start.
Definition at line 35 of file TimePeriodKey.hpp.
Referenced by stdair::TimePeriod::getTimeRangeStart().
const Time_T& stdair::TimePeriodKey::getTimeRangeEnd () const inline
Get the time period end.
Definition at line 42 of file TimePeriodKey.hpp.
Referenced by stdair::TimePeriod::getTimeRangeEnd().
void stdair::TimePeriodKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 38 of file TimePeriodKey.cpp.
References toString().
void stdair::TimePeriodKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 43 of file TimePeriodKey.cpp.
const std::string stdair::TimePeriodKey::toString () const virtual
Get the serialised version of the Business Object Key. That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
Reimplemented from stdair::KeyAbstract.
Definition at line 47 of file TimePeriodKey.cpp.
Referenced by stdair::TimePeriod::describeKey(), and toStream().
The documentation for this struct was generated from the following files:
stdair/bom/TimePeriodKey.hpp
stdair/bom/TimePeriodKey.cpp