stdair::YieldStoreKey Struct Reference
stdair::YieldStoreKey Struct Reference
#include <stdair/bom/YieldStoreKey.hpp>
Public Member Functions
YieldStoreKey (const AirlineCode_T &iAirlineCode)
YieldStoreKey (const YieldStoreKey &)
~YieldStoreKey ()
const AirlineCode_T & getAirlineCode () const
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string toString () const
Detailed Description
Key of YieldStore.
Definition at line 14 of file YieldStoreKey.hpp.
Constructor & Destructor Documentation
stdair::YieldStoreKey::YieldStoreKey (const AirlineCode_T & iAirlineCode)
Constructors.
Definition at line 10 of file YieldStoreKey.cpp.
stdair::YieldStoreKey::YieldStoreKey (const YieldStoreKey & iKey)
Definition at line 14 of file YieldStoreKey.cpp.
stdair::YieldStoreKey::~YieldStoreKey ()
Destructor.
Definition at line 19 of file YieldStoreKey.cpp.
Member Function Documentation
const AirlineCode_T& stdair::YieldStoreKey::getAirlineCode () const inline
Get the airline code.
Definition at line 30 of file YieldStoreKey.hpp.
Referenced by stdair::YieldStore::getAirlineCode().
void stdair::YieldStoreKey::toStream (std::ostream & ioOut) const virtual
Dump a Business Object Key into an output stream.
Parameters
ostream& the output stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 23 of file YieldStoreKey.cpp.
References toString().
void stdair::YieldStoreKey::fromStream (std::istream & ioIn) virtual
Read a Business Object Key from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::KeyAbstract.
Definition at line 28 of file YieldStoreKey.cpp.
const std::string stdair::YieldStoreKey::toString () const virtual
Get the serialised version of the Business Object Key.
That string is unique, at the level of a given Business Object, when among children of a given parent Business Object.
For instance, "H" and "K" allow to differentiate among two marketing classes for the same segment-date.
Reimplemented from stdair::KeyAbstract.
Definition at line 32 of file YieldStoreKey.cpp.
Referenced by stdair::YieldStore::describeKey(), toStream(), and stdair::YieldStore::toString().
The documentation for this struct was generated from the following files:
stdair/bom/YieldStoreKey.hpp
stdair/bom/YieldStoreKey.cpp