stdair::TravelSolutionStruct Struct Reference
stdair::TravelSolutionStruct Struct Reference
Structure holding the elements of a travel solution.
#include <stdair/bom/TravelSolutionStruct.hpp>
Public Member Functions
const SegmentPath_T & getSegmentPath () const
const ClassAvailabilityMapHolder_T & getClassAvailabilityMapHolder () const
const ClassObjectIDMapHolder_T & getClassObjectIDMapHolder () const
const ClassYieldMapHolder_T & getClassYieldMapHolder () const
const BidPriceVectorHolder_T & getBidPriceVectorHolder () const
const ClassBpvMapHolder_T & getClassBpvMapHolder () const
const FareOptionList_T & getFareOptionList () const
FareOptionList_T & getFareOptionListRef ()
const FareOptionStruct & getChosenFareOption () const
void addSegment (const std::string &)
void addClassAvailabilityMap (const ClassAvailabilityMap_T &)
void addClassObjectIDMap (const ClassObjectIDMap_T &)
void addClassYieldMap (const ClassYieldMap_T &)
void addBidPriceVector (const BidPriceVector_T &)
void addClassBpvMap (const ClassBpvMap_T &)
void addFareOption (const FareOptionStruct &)
void setChosenFareOption (const FareOptionStruct &iChosenFO)
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
const std::string describe () const
const std::string display () const
const std::string describeSegmentPath () const
TravelSolutionStruct ()
~TravelSolutionStruct ()
Detailed Description
Structure holding the elements of a travel solution.
Definition at line 24 of file TravelSolutionStruct.hpp.
Constructor & Destructor Documentation
stdair::TravelSolutionStruct::TravelSolutionStruct ()
Default constructor.
Definition at line 15 of file TravelSolutionStruct.cpp.
stdair::TravelSolutionStruct::~TravelSolutionStruct ()
Destructor.
Definition at line 19 of file TravelSolutionStruct.cpp.
Member Function Documentation
const SegmentPath_T& stdair::TravelSolutionStruct::getSegmentPath () const inline
Get the segment path.
Definition at line 28 of file TravelSolutionStruct.hpp.
const ClassAvailabilityMapHolder_T& stdair::TravelSolutionStruct::getClassAvailabilityMapHolder () const inline
Get the holder of avalabilities.
Definition at line 33 of file TravelSolutionStruct.hpp.
const ClassObjectIDMapHolder_T& stdair::TravelSolutionStruct::getClassObjectIDMapHolder () const inline
Get the holder of object ID's.
Definition at line 38 of file TravelSolutionStruct.hpp.
const ClassYieldMapHolder_T& stdair::TravelSolutionStruct::getClassYieldMapHolder () const inline
Get the holder of yields.
Definition at line 43 of file TravelSolutionStruct.hpp.
const BidPriceVectorHolder_T& stdair::TravelSolutionStruct::getBidPriceVectorHolder () const inline
Get the holder of bid price vectors.
Definition at line 48 of file TravelSolutionStruct.hpp.
const ClassBpvMapHolder_T& stdair::TravelSolutionStruct::getClassBpvMapHolder () const inline
Get the holder of class - bid price reference.
Definition at line 53 of file TravelSolutionStruct.hpp.
const FareOptionList_T& stdair::TravelSolutionStruct::getFareOptionList () const inline
Get the list of fare options.
Definition at line 58 of file TravelSolutionStruct.hpp.
FareOptionList_T& stdair::TravelSolutionStruct::getFareOptionListRef () inline
Get the non-const list of fare options.
Definition at line 63 of file TravelSolutionStruct.hpp.
const FareOptionStruct& stdair::TravelSolutionStruct::getChosenFareOption () const inline
Get the chosen fare option.
Definition at line 68 of file TravelSolutionStruct.hpp.
void stdair::TravelSolutionStruct::addSegment (const std::string & iKey)
Add a segment key to the segment path.
Definition at line 154 of file TravelSolutionStruct.cpp.
void stdair::TravelSolutionStruct::addClassAvailabilityMap (const ClassAvailabilityMap_T & iMap)
Add a class availability map.
Definition at line 160 of file TravelSolutionStruct.cpp.
void stdair::TravelSolutionStruct::addClassObjectIDMap (const ClassObjectIDMap_T & iMap)
Add a class object ID map.
Definition at line 166 of file TravelSolutionStruct.cpp.
void stdair::TravelSolutionStruct::addClassYieldMap (const ClassYieldMap_T & iMap)
Add a class yield map.
Definition at line 172 of file TravelSolutionStruct.cpp.
void stdair::TravelSolutionStruct::addBidPriceVector (const BidPriceVector_T & iBpv)
Add a bid price vector.
Definition at line 178 of file TravelSolutionStruct.cpp.
void stdair::TravelSolutionStruct::addClassBpvMap (const ClassBpvMap_T & iMap)
Add a class bpv reference map.
Definition at line 184 of file TravelSolutionStruct.cpp.
void stdair::TravelSolutionStruct::addFareOption (const FareOptionStruct & iFareOption)
Add a fare option.
Definition at line 190 of file TravelSolutionStruct.cpp.
void stdair::TravelSolutionStruct::setChosenFareOption (const FareOptionStruct & iChosenFO) inline
Set the chosen fare option.
Definition at line 97 of file TravelSolutionStruct.hpp.
void stdair::TravelSolutionStruct::toStream (std::ostream & ioOut) const
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 23 of file TravelSolutionStruct.cpp.
References describe().
void stdair::TravelSolutionStruct::fromStream (std::istream & ioIn) virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented from stdair::StructAbstract.
Definition at line 28 of file TravelSolutionStruct.cpp.
const std::string stdair::TravelSolutionStruct::describe () const virtual
Display of the structure.
Implements stdair::StructAbstract.
Definition at line 53 of file TravelSolutionStruct.cpp.
References stdair::FareOptionStruct::describe(), stdair::BomKeyManager::extractKeys(), and stdair::ParsedKey::toString().
Referenced by toStream().
const std::string stdair::TravelSolutionStruct::display () const
Display of the structure.
Definition at line 95 of file TravelSolutionStruct.cpp.
References stdair::FareOptionStruct::display(), stdair::BomKeyManager::extractKeys(), and stdair::ParsedKey::toString().
const std::string stdair::TravelSolutionStruct::describeSegmentPath () const
Display only the segment path.
Definition at line 32 of file TravelSolutionStruct.cpp.
References stdair::BomKeyManager::extractKeys(), and stdair::ParsedKey::toString().
The documentation for this struct was generated from the following files:
stdair/bom/TravelSolutionStruct.hpp
stdair/bom/TravelSolutionStruct.cpp