stdair::YieldStore Class Reference
stdair::YieldStore Class Reference
#include <stdair/bom/YieldStore.hpp>
Public Types
typedef YieldStoreKey Key_T
Public Member Functions
void toStream (std::ostream &ioOut) const
BomAbstract *const getParent () const
void fromStream (std::istream &ioIn)
std::string toString () const
const std::string describeKey () const
const Key_T & getKey () const
const AirlineCode_T & getAirlineCode () const
Protected Member Functions
YieldStore (const Key_T &)
YieldStore (const YieldStore &)
~YieldStore ()
Protected Attributes
Key_T _key
BomAbstract * _parent
Friends
template<typename BOM >
class FacBom
class FacBomManager
Detailed Description
Class representing the actual attributes for an airline YieldStore.
Definition at line 18 of file YieldStore.hpp.
Member Typedef Documentation
typedef YieldStoreKey stdair::YieldStore::Key_T
Definition allowing to retrieve the associated BOM key type.
Definition at line 25 of file YieldStore.hpp.
Constructor & Destructor Documentation
stdair::YieldStore::YieldStore (const Key_T & iKey) protected
Default constructors.
Definition at line 13 of file YieldStore.cpp.
stdair::YieldStore::YieldStore (const YieldStore &) protected
stdair::YieldStore::~YieldStore () protected
Destructor.
Definition at line 17 of file YieldStore.cpp.
Member Function Documentation
void stdair::YieldStore::toStream (std::ostream & ioOut) const inline virtual
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Implements stdair::BomAbstract.
Definition at line 31 of file YieldStore.hpp.
References toString().
BomAbstract* const stdair::YieldStore::getParent () const inline
Get the parent object.
Definition at line 34 of file YieldStore.hpp.
References _parent.
void stdair::YieldStore::fromStream (std::istream & ioIn) inline virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Implements stdair::BomAbstract.
Definition at line 38 of file YieldStore.hpp.
std::string stdair::YieldStore::toString () const virtual
Get the serialised version of the Business Object.
Implements stdair::BomAbstract.
Definition at line 21 of file YieldStore.cpp.
References _key, and stdair::YieldStoreKey::toString().
Referenced by toStream().
const std::string stdair::YieldStore::describeKey () const inline
Get a string describing the key.
Definition at line 44 of file YieldStore.hpp.
References _key, and stdair::YieldStoreKey::toString().
const Key_T& stdair::YieldStore::getKey () const inline
Get the YieldStore key.
Definition at line 49 of file YieldStore.hpp.
References _key.
const AirlineCode_T& stdair::YieldStore::getAirlineCode () const inline
Get the airline code.
Definition at line 52 of file YieldStore.hpp.
References _key, and stdair::YieldStoreKey::getAirlineCode().
Friends And Related Function Documentation
template<typename BOM > friend class FacBom friend
Definition at line 19 of file YieldStore.hpp.
friend class FacBomManager friend
Definition at line 20 of file YieldStore.hpp.
Member Data Documentation
Key_T stdair::YieldStore::_key protected
The key of both structure and objects.
Definition at line 66 of file YieldStore.hpp.
Referenced by describeKey(), getAirlineCode(), getKey(), and toString().
BomAbstract* stdair::YieldStore::_parent protected
Definition at line 67 of file YieldStore.hpp.
Referenced by getParent().
The documentation for this class was generated from the following files:
stdair/bom/YieldStore.hpp
stdair/bom/YieldStore.cpp