stdair::TimePeriod Class Reference
stdair::TimePeriod Class Reference
Class representing the actual attributes for a fare time-period.
#include <stdair/bom/TimePeriod.hpp>
Public Types
typedef TimePeriodKey Key_T
Public Member Functions
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
std::string toString () const
const std::string describeKey () const
const Key_T & getKey () const
BomAbstract *const getParent () const
const HolderMap_T & getHolderMap () const
const Time_T & getTimeRangeStart () const
const Time_T & getTimeRangeEnd () const
bool isDepartureTimeValid (const Time_T &) const
Protected Member Functions
TimePeriod (const Key_T &)
virtual ~TimePeriod ()
Protected Attributes
Key_T _key
BomAbstract * _parent
HolderMap_T _holderMap
Friends
template<typename BOM >
class FacBom
template<typename BOM >
class FacCloneBom
class FacBomManager
Detailed Description
Class representing the actual attributes for a fare time-period.
Definition at line 18 of file TimePeriod.hpp.
Member Typedef Documentation
typedef TimePeriodKey stdair::TimePeriod::Key_T
Definition allowing to retrieve the associated BOM key type.
Definition at line 28 of file TimePeriod.hpp.
Constructor & Destructor Documentation
stdair::TimePeriod::TimePeriod (const Key_T & iKey) protected
Main constructor.
Definition at line 27 of file TimePeriod.cpp.
stdair::TimePeriod::~TimePeriod () protected virtual
Destructor.
Definition at line 32 of file TimePeriod.cpp.
Member Function Documentation
void stdair::TimePeriod::toStream (std::ostream & ioOut) const inline virtual
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Implements stdair::BomAbstract.
Definition at line 38 of file TimePeriod.hpp.
References toString().
void stdair::TimePeriod::fromStream (std::istream & ioIn) inline virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Implements stdair::BomAbstract.
Definition at line 47 of file TimePeriod.hpp.
std::string stdair::TimePeriod::toString () const virtual
Get the serialised version of the Business Object.
Implements stdair::BomAbstract.
Definition at line 36 of file TimePeriod.cpp.
References describeKey().
Referenced by toStream().
const std::string stdair::TimePeriod::describeKey () const inline
Get a string describing the key.
Definition at line 58 of file TimePeriod.hpp.
References _key, and stdair::TimePeriodKey::toString().
Referenced by toString().
const Key_T& stdair::TimePeriod::getKey () const inline
Get the primary key (time range start, time range end).
Definition at line 67 of file TimePeriod.hpp.
References _key.
BomAbstract* const stdair::TimePeriod::getParent () const inline
Get a reference on the parent object instance.
Definition at line 74 of file TimePeriod.hpp.
References _parent.
const HolderMap_T& stdair::TimePeriod::getHolderMap () const inline
Get a reference on the children holder.
Definition at line 81 of file TimePeriod.hpp.
References _holderMap.
const Time_T& stdair::TimePeriod::getTimeRangeStart () const inline
Get the time range start.
Definition at line 88 of file TimePeriod.hpp.
References _key, and stdair::TimePeriodKey::getTimeRangeStart().
Referenced by isDepartureTimeValid().
const Time_T& stdair::TimePeriod::getTimeRangeEnd () const inline
Get the time range end
Definition at line 95 of file TimePeriod.hpp.
References _key, and stdair::TimePeriodKey::getTimeRangeEnd().
Referenced by isDepartureTimeValid().
bool stdair::TimePeriod::isDepartureTimeValid (const Time_T & iFlightTime) const
Check if the given departure time is included in the departure period of the segment path.
Definition at line 44 of file TimePeriod.cpp.
References getTimeRangeEnd(), getTimeRangeStart(), and STDAIR_LOG_DEBUG.
Friends And Related Function Documentation
template<typename BOM > friend class FacBom friend
Definition at line 19 of file TimePeriod.hpp.
template<typename BOM > friend class FacCloneBom friend
Definition at line 20 of file TimePeriod.hpp.
friend class FacBomManager friend
Definition at line 21 of file TimePeriod.hpp.
Member Data Documentation
Key_T stdair::TimePeriod::_key protected
Primary key (flight number and departure date).
Definition at line 133 of file TimePeriod.hpp.
Referenced by describeKey(), getKey(), getTimeRangeEnd(), and getTimeRangeStart().
BomAbstract* stdair::TimePeriod::_parent protected
Pointer on the parent class (Inventory).
Definition at line 138 of file TimePeriod.hpp.
Referenced by getParent().
HolderMap_T stdair::TimePeriod::_holderMap protected
Map holding the children.
Definition at line 143 of file TimePeriod.hpp.
Referenced by getHolderMap().
The documentation for this class was generated from the following files:
stdair/bom/TimePeriod.hpp
stdair/bom/TimePeriod.cpp