soci::type_conversion< stdair::AirlineStruct > Struct Template Reference
soci::type_conversion< stdair::AirlineStruct > Struct Template Reference
#include <stdair/dbadaptor/DbaAirline.hpp>
Public Types
typedef values base_type
Static Public Member Functions
static void from_base (values const &iAirlineValues, indicator, stdair::AirlineStruct &ioAirline)
static void to_base (const stdair::AirlineStruct &iAirline, values &ioAirlineValues, indicator &ioIndicator)
Detailed Description
template<>
struct soci::type_conversion< stdair::AirlineStruct >
Specify how the AirlineStruct struct can be converted to (resp. from) values stored into (resp. retrieved from) database, using the SOCI framework.
Definition at line 25 of file DbaAirline.hpp.
Member Typedef Documentation
typedef values soci::type_conversion< stdair::AirlineStruct >::base_type
Definition at line 27 of file DbaAirline.hpp.
Member Function Documentation
void soci::type_conversion< stdair::AirlineStruct >::from_base (values const & iAirlineValues, indicator , stdair::AirlineStruct & ioAirline) static
Fill an Airline object from the database values.
Definition at line 17 of file DbaAirline.cpp.
References stdair::AirlineStruct::setAirlineCode(), and stdair::AirlineStruct::setAirlineName().
void soci::type_conversion< stdair::AirlineStruct >::to_base (const stdair::AirlineStruct & iAirline, values & ioAirlineValues, indicator & ioIndicator) static
Fill the database values from an Airline object.
Definition at line 30 of file DbaAirline.cpp.
References stdair::AirlineStruct::getAirlineCode(), and stdair::AirlineStruct::getAirlineName().
The documentation for this struct was generated from the following files:
stdair/dbadaptor/DbaAirline.hpp
stdair/dbadaptor/DbaAirline.cpp