stdair::YieldFeatures Class Reference
stdair::YieldFeatures Class Reference
Class representing the actual attributes for a yield date-period.
#include <stdair/bom/YieldFeatures.hpp>
Public Types
typedef YieldFeaturesKey Key_T
Public Member Functions
void toStream (std::ostream &ioOut) const
void fromStream (std::istream &ioIn)
std::string toString () const
const std::string describeKey () const
const Key_T & getKey () const
BomAbstract *const getParent () const
const HolderMap_T & getHolderMap () const
const CabinCode_T & getCabinCode () const
const TripType_T & getTripType () const
bool isTripTypeValid (const TripType_T &) const
Protected Member Functions
YieldFeatures (const Key_T &)
virtual ~YieldFeatures ()
Protected Attributes
Key_T _key
BomAbstract * _parent
HolderMap_T _holderMap
Friends
template<typename BOM >
class FacBom
template<typename BOM >
class FacCloneBom
class FacBomManager
Detailed Description
Class representing the actual attributes for a yield date-period.
Definition at line 19 of file YieldFeatures.hpp.
Member Typedef Documentation
typedef YieldFeaturesKey stdair::YieldFeatures::Key_T
Definition allowing to retrieve the associated BOM key type.
Definition at line 29 of file YieldFeatures.hpp.
Constructor & Destructor Documentation
stdair::YieldFeatures::YieldFeatures (const Key_T & iKey) protected
Main constructor.
Definition at line 28 of file YieldFeatures.cpp.
stdair::YieldFeatures::~YieldFeatures () protected virtual
Destructor.
Definition at line 33 of file YieldFeatures.cpp.
Member Function Documentation
void stdair::YieldFeatures::toStream (std::ostream & ioOut) const inline virtual
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Implements stdair::BomAbstract.
Definition at line 38 of file YieldFeatures.hpp.
References toString().
void stdair::YieldFeatures::fromStream (std::istream & ioIn) inline virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Implements stdair::BomAbstract.
Definition at line 47 of file YieldFeatures.hpp.
std::string stdair::YieldFeatures::toString () const virtual
Get the serialised version of the Business Object.
Implements stdair::BomAbstract.
Definition at line 37 of file YieldFeatures.cpp.
References describeKey().
Referenced by toStream().
const std::string stdair::YieldFeatures::describeKey () const inline
Get a string describing the key.
Definition at line 58 of file YieldFeatures.hpp.
References _key, and stdair::YieldFeaturesKey::toString().
Referenced by toString().
const Key_T& stdair::YieldFeatures::getKey () const inline
Get the primary key (trip type, cabin code).
Definition at line 67 of file YieldFeatures.hpp.
References _key.
BomAbstract* const stdair::YieldFeatures::getParent () const inline
Get a reference on the parent object instance.
Definition at line 74 of file YieldFeatures.hpp.
References _parent.
const HolderMap_T& stdair::YieldFeatures::getHolderMap () const inline
Get a reference on the children holder.
Definition at line 81 of file YieldFeatures.hpp.
References _holderMap.
const CabinCode_T& stdair::YieldFeatures::getCabinCode () const inline
Get the cabin code.
Definition at line 88 of file YieldFeatures.hpp.
References _key, and stdair::YieldFeaturesKey::getCabinCode().
const TripType_T& stdair::YieldFeatures::getTripType () const inline
Get the trip type.
Definition at line 95 of file YieldFeatures.hpp.
References _key, and stdair::YieldFeaturesKey::getTripType().
Referenced by isTripTypeValid().
bool stdair::YieldFeatures::isTripTypeValid (const TripType_T & iBookingRequestTripType) const
Check whether the fare rule trip type corresponds to the booking request trip type.
Definition at line 45 of file YieldFeatures.cpp.
References getTripType(), stdair::TRIP_TYPE_INBOUND, stdair::TRIP_TYPE_OUTBOUND, and stdair::TRIP_TYPE_ROUND_TRIP.
Friends And Related Function Documentation
template<typename BOM > friend class FacBom friend
Definition at line 20 of file YieldFeatures.hpp.
template<typename BOM > friend class FacCloneBom friend
Definition at line 21 of file YieldFeatures.hpp.
friend class FacBomManager friend
Definition at line 22 of file YieldFeatures.hpp.
Member Data Documentation
Key_T stdair::YieldFeatures::_key protected
Primary key (flight number and departure date).
Definition at line 138 of file YieldFeatures.hpp.
Referenced by describeKey(), getCabinCode(), getKey(), and getTripType().
BomAbstract* stdair::YieldFeatures::_parent protected
Pointer on the parent class.
Definition at line 143 of file YieldFeatures.hpp.
Referenced by getParent().
HolderMap_T stdair::YieldFeatures::_holderMap protected
Map holding the children.
Definition at line 148 of file YieldFeatures.hpp.
Referenced by getHolderMap().
The documentation for this class was generated from the following files:
stdair/bom/YieldFeatures.hpp
stdair/bom/YieldFeatures.cpp