stdair::UnconstrainingMethod Struct Reference
stdair::UnconstrainingMethod Struct Reference
#include <stdair/basic/UnconstrainingMethod.hpp>
Public Types
enum EN_UnconstrainingMethod { EM = 0, LAST_VALUE }
Public Member Functions
EN_UnconstrainingMethod getMethod () const
std::string getMethodAsString () const
const std::string describe () const
bool operator== (const EN_UnconstrainingMethod &) const
UnconstrainingMethod (const EN_UnconstrainingMethod &)
UnconstrainingMethod (const char iMethod)
UnconstrainingMethod (const UnconstrainingMethod &)
void toStream (std::ostream &ioOut) const
virtual void fromStream (std::istream &ioIn)
Static Public Member Functions
static const std::string & getLabel (const EN_UnconstrainingMethod &)
static char getMethodLabel (const EN_UnconstrainingMethod &)
static std::string getMethodLabelAsString (const EN_UnconstrainingMethod &)
static std::string describeLabels ()
Detailed Description
Enumeration of unconstraining methods.
Definition at line 15 of file UnconstrainingMethod.hpp.
Member Enumeration Documentation
enum stdair::UnconstrainingMethod::EN_UnconstrainingMethod
Enumerator
EM
LAST_VALUE
Definition at line 17 of file UnconstrainingMethod.hpp.
Constructor & Destructor Documentation
stdair::UnconstrainingMethod::UnconstrainingMethod (const EN_UnconstrainingMethod & iUnconstrainingMethod)
Constructor.
Definition at line 36 of file UnconstrainingMethod.cpp.
stdair::UnconstrainingMethod::UnconstrainingMethod (const char iMethod)
Constructor.
Definition at line 41 of file UnconstrainingMethod.cpp.
References describeLabels(), EM, and LAST_VALUE.
stdair::UnconstrainingMethod::UnconstrainingMethod (const UnconstrainingMethod & iUnconstrainingMethod)
Default copy constructor.
Definition at line 30 of file UnconstrainingMethod.cpp.
Member Function Documentation
const std::string & stdair::UnconstrainingMethod::getLabel (const EN_UnconstrainingMethod & iMethod) static
Get the label as a string (e.g., "Expectation-Maximisation")
Definition at line 58 of file UnconstrainingMethod.cpp.
char stdair::UnconstrainingMethod::getMethodLabel (const EN_UnconstrainingMethod & iMethod) static
Get the label as a single char (e.g., 'T' or 'B').
Definition at line 63 of file UnconstrainingMethod.cpp.
std::string stdair::UnconstrainingMethod::getMethodLabelAsString (const EN_UnconstrainingMethod & iMethod) static
Get the label as a string of a single char (e.g., "T" or "B").
Definition at line 69 of file UnconstrainingMethod.cpp.
std::string stdair::UnconstrainingMethod::describeLabels () static
List the labels.
Definition at line 76 of file UnconstrainingMethod.cpp.
References LAST_VALUE.
Referenced by UnconstrainingMethod().
UnconstrainingMethod::EN_UnconstrainingMethod stdair::UnconstrainingMethod::getMethod () const
Get the enumerated value.
Definition at line 88 of file UnconstrainingMethod.cpp.
Referenced by stdair::AirlineFeature::getUnconstrainingMethod().
std::string stdair::UnconstrainingMethod::getMethodAsString () const
Get the enumerated value as a short string (e.g., "T" or "B").
Definition at line 93 of file UnconstrainingMethod.cpp.
const std::string stdair::UnconstrainingMethod::describe () const virtual
Give a description of the structure (e.g., "Expectation-Maximisation").
Implements stdair::StructAbstract.
Definition at line 100 of file UnconstrainingMethod.cpp.
bool stdair::UnconstrainingMethod::operator== (const EN_UnconstrainingMethod & iMethod) const
Comparison operator.
Definition at line 108 of file UnconstrainingMethod.cpp.
void stdair::StructAbstract::toStream (std::ostream & ioOut) const inline inherited
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 29 of file StructAbstract.hpp.
References stdair::StructAbstract::describe().
virtual void stdair::StructAbstract::fromStream (std::istream & ioIn) inline virtual inherited
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented in stdair::BookingRequestStruct, stdair::EventStruct, stdair::TravelSolutionStruct, stdair::VirtualClassStruct, stdair::ConfigHolderStruct, stdair::FareOptionStruct, stdair::OptimisationNotificationStruct, stdair::ProgressStatusSet, stdair::YieldRange, stdair::CancellationStruct, stdair::AirlineStruct, stdair::RMEventStruct, stdair::SnapshotStruct, stdair::FFDisutilityCurveHolderStruct, stdair::FRAT5CurveHolderStruct, and stdair::BreakPointStruct.
Definition at line 38 of file StructAbstract.hpp.
Referenced by operator>>().
The documentation for this struct was generated from the following files:
stdair/basic/UnconstrainingMethod.hpp
stdair/basic/UnconstrainingMethod.cpp