stdair::StructAbstract Struct Reference
stdair::StructAbstract Struct Reference abstract
Base class for the light structures.
#include <stdair/basic/StructAbstract.hpp>
Public Member Functions
virtual ~StructAbstract ()
void toStream (std::ostream &ioOut) const
virtual void fromStream (std::istream &ioIn)
virtual const std::string describe () const =0
Protected Member Functions
StructAbstract ()
Detailed Description
Base class for the light structures.
Definition at line 16 of file StructAbstract.hpp.
Constructor & Destructor Documentation
virtual stdair::StructAbstract::~StructAbstract () inline virtual
Destructor.
Definition at line 22 of file StructAbstract.hpp.
stdair::StructAbstract::StructAbstract () inline protected
Protected Default Constructor to ensure this class is abtract.
Definition at line 49 of file StructAbstract.hpp.
Member Function Documentation
void stdair::StructAbstract::toStream (std::ostream & ioOut) const inline
Dump a Business Object into an output stream.
Parameters
ostream& the output stream.
Definition at line 29 of file StructAbstract.hpp.
References describe().
virtual void stdair::StructAbstract::fromStream (std::istream & ioIn) inline virtual
Read a Business Object from an input stream.
Parameters
istream& the input stream.
Reimplemented in stdair::BookingRequestStruct, stdair::EventStruct, stdair::TravelSolutionStruct, stdair::VirtualClassStruct, stdair::ConfigHolderStruct, stdair::FareOptionStruct, stdair::OptimisationNotificationStruct, stdair::ProgressStatusSet, stdair::YieldRange, stdair::CancellationStruct, stdair::AirlineStruct, stdair::RMEventStruct, stdair::SnapshotStruct, stdair::FFDisutilityCurveHolderStruct, stdair::FRAT5CurveHolderStruct, and stdair::BreakPointStruct.
Definition at line 38 of file StructAbstract.hpp.
Referenced by operator>>().
virtual const std::string stdair::StructAbstract::describe () const pure virtual
Display of the structure.
Implemented in stdair::BookingRequestStruct, stdair::EventStruct, stdair::TravelSolutionStruct, stdair::ConfigHolderStruct, stdair::FareOptionStruct, stdair::VirtualClassStruct, stdair::OptimisationNotificationStruct, stdair::ProgressStatus, stdair::BasDBParams, stdair::ProgressStatusSet, stdair::YieldRange, stdair::PartnershipTechnique, stdair::SampleType, stdair::ServiceInitialisationType, stdair::DemandGenerationMethod, stdair::CancellationStruct, stdair::BasLogParams, stdair::RandomGeneration, stdair::EventType, stdair::JSonCommand, stdair::AirlineStruct, stdair::ForecastingMethod, stdair::RMEventStruct, stdair::PassengerChoiceModel, stdair::OptimisationMethod, stdair::PassengerType, stdair::PreOptimisationMethod, stdair::UnconstrainingMethod, stdair::SnapshotStruct, stdair::PeriodStruct, stdair::DoWStruct, stdair::FFDisutilityCurveHolderStruct, stdair::FRAT5CurveHolderStruct, and stdair::BreakPointStruct.
Referenced by toStream().
The documentation for this struct was generated from the following file:
stdair/basic/StructAbstract.hpp