var hierarchy =
[
    [ "std::allocator< T >", null, null ],
    [ "std::array< T >", null, null ],
    [ "std::auto_ptr< T >", null, null ],
    [ "stdair::BasChronometer", "a00058.html", null ],
    [ "stdair::BasFileMgr", "a00060.html", null ],
    [ "std::basic_string< Char >", null, [
      [ "std::string", null, null ],
      [ "std::wstring", null, null ]
    ] ],
    [ "std::basic_string< char >", null, null ],
    [ "std::basic_string< wchar_t >", null, null ],
    [ "std::bitset< Bits >", null, null ],
    [ "stdair::BomAbstract", "a00062.html", [
      [ "stdair::AirlineClassList", "a00051.html", null ],
      [ "stdair::AirlineFeature", "a00053.html", null ],
      [ "stdair::AirportPair", "a00056.html", null ],
      [ "stdair::BomHolder< BOM >", "a00065.html", null ],
      [ "stdair::BomRoot", "a00074.html", null ],
      [ "stdair::BookingClass", "a00077.html", null ],
      [ "stdair::Bucket", "a00082.html", null ],
      [ "stdair::DatePeriod", "a00097.html", null ],
      [ "stdair::FareFamily", "a00120.html", null ],
      [ "stdair::FareFeatures", "a00122.html", null ],
      [ "stdair::FlightDate", "a00128.html", null ],
      [ "stdair::FlightPeriod", "a00130.html", null ],
      [ "stdair::Inventory", "a00137.html", null ],
      [ "stdair::LegCabin", "a00144.html", null ],
      [ "stdair::LegDate", "a00146.html", null ],
      [ "stdair::NestingNode", "a00150.html", null ],
      [ "stdair::OnDDate", "a00162.html", null ],
      [ "stdair::Policy", "a00173.html", null ],
      [ "stdair::PosChannel", "a00175.html", null ],
      [ "stdair::SegmentCabin", "a00186.html", null ],
      [ "stdair::SegmentDate", "a00188.html", null ],
      [ "stdair::SegmentPeriod", "a00190.html", null ],
      [ "stdair::SegmentSnapshotTable", "a00192.html", null ],
      [ "stdair::SimpleNestingStructure", "a00198.html", null ],
      [ "stdair::TimePeriod", "a00207.html", null ],
      [ "stdair::YieldFeatures", "a00216.html", null ],
      [ "stdair::YieldStore", "a00219.html", null ]
    ] ],
    [ "stdair::BomArchive", "a00063.html", null ],
    [ "stdair::BomDisplay", "a00064.html", null ],
    [ "stdair::BomID< BOM >", "a00067.html", null ],
    [ "stdair::BomINIImport", "a00068.html", null ],
    [ "stdair::BomJSONExport", "a00069.html", null ],
    [ "stdair::BomJSONImport", "a00070.html", null ],
    [ "stdair::BomKeyManager", "a00071.html", null ],
    [ "stdair::BomManager", "a00072.html", null ],
    [ "stdair::BomRetriever", "a00073.html", null ],
    [ "stdair_test::BookingClass", "a00076.html", null ],
    [ "stdair_test::Cabin", "a00084.html", null ],
    [ "stdair::CmdAbstract", "a00086.html", [
      [ "stdair::CmdBomManager", "a00087.html", null ],
      [ "stdair::CmdBomSerialiser", "a00088.html", null ],
      [ "stdair::CmdCloneBomManager", "a00089.html", null ],
      [ "stdair::DBManagerForAirlines", "a00100.html", null ]
    ] ],
    [ "COMMAND", "a00092.html", null ],
    [ "std::complex", null, null ],
    [ "std::list< T >::const_iterator", null, null ],
    [ "std::forward_list< T >::const_iterator", null, null ],
    [ "std::map< K, T >::const_iterator", null, null ],
    [ "std::unordered_map< K, T >::const_iterator", null, null ],
    [ "std::basic_string< Char >::const_iterator", null, null ],
    [ "std::multimap< K, T >::const_iterator", null, null ],
    [ "std::unordered_multimap< K, T >::const_iterator", null, null ],
    [ "std::set< K >::const_iterator", null, null ],
    [ "std::string::const_iterator", null, null ],
    [ "std::unordered_set< K >::const_iterator", null, null ],
    [ "std::wstring::const_iterator", null, null ],
    [ "std::multiset< K >::const_iterator", null, null ],
    [ "std::unordered_multiset< K >::const_iterator", null, null ],
    [ "std::vector< T >::const_iterator", null, null ],
    [ "std::deque< T >::const_iterator", null, null ],
    [ "std::list< T >::const_reverse_iterator", null, null ],
    [ "std::forward_list< T >::const_reverse_iterator", null, null ],
    [ "std::map< K, T >::const_reverse_iterator", null, null ],
    [ "std::unordered_map< K, T >::const_reverse_iterator", null, null ],
    [ "std::multimap< K, T >::const_reverse_iterator", null, null ],
    [ "std::basic_string< Char >::const_reverse_iterator", null, null ],
    [ "std::unordered_multimap< K, T >::const_reverse_iterator", null, null ],
    [ "std::set< K >::const_reverse_iterator", null, null ],
    [ "std::string::const_reverse_iterator", null, null ],
    [ "std::unordered_set< K >::const_reverse_iterator", null, null ],
    [ "std::multiset< K >::const_reverse_iterator", null, null ],
    [ "std::wstring::const_reverse_iterator", null, null ],
    [ "std::unordered_multiset< K >::const_reverse_iterator", null, null ],
    [ "std::vector< T >::const_reverse_iterator", null, null ],
    [ "std::deque< T >::const_reverse_iterator", null, null ],
    [ "stdair::ContinuousAttributeLite< T >", "a00095.html", null ],
    [ "stdair::date_time_element< MIN, MAX >", "a00096.html", null ],
    [ "stdair::DbaAbstract", "a00099.html", null ],
    [ "stdair::DBSessionManager", "a00101.html", null ],
    [ "stdair::DefaultDCPList", "a00102.html", null ],
    [ "stdair::DefaultDtdFratMap", "a00103.html", null ],
    [ "stdair::DefaultDtdProbMap", "a00104.html", null ],
    [ "stdair::DefaultMap", "a00105.html", null ],
    [ "std::deque< T >", null, null ],
    [ "stdair::DictionaryManager", "a00107.html", null ],
    [ "std::error_category", null, null ],
    [ "std::error_code", null, null ],
    [ "std::error_condition", null, null ],
    [ "std::exception", null, [
      [ "std::bad_alloc", null, null ],
      [ "std::bad_cast", null, null ],
      [ "std::bad_exception", null, null ],
      [ "std::bad_typeid", null, null ],
      [ "std::ios_base::failure", null, null ],
      [ "std::logic_error", null, [
        [ "std::domain_error", null, null ],
        [ "std::invalid_argument", null, null ],
        [ "std::length_error", null, null ],
        [ "std::out_of_range", null, null ]
      ] ],
      [ "std::runtime_error", null, [
        [ "std::overflow_error", null, null ],
        [ "std::range_error", null, null ],
        [ "std::underflow_error", null, null ]
      ] ],
      [ "stdair::RootException", "a00182.html", [
        [ "stdair::DocumentNotFoundException", "a00108.html", null ],
        [ "stdair::EventException", "a00110.html", null ],
        [ "stdair::FileNotFoundException", "a00127.html", null ],
        [ "stdair::KeyNotFoundException", "a00143.html", null ],
        [ "stdair::MemoryAllocationException", "a00149.html", null ],
        [ "stdair::NonInitialisedContainerException", "a00153.html", null ],
        [ "stdair::NonInitialisedDBSessionManagerException", "a00154.html", null ],
        [ "stdair::NonInitialisedLogServiceException", "a00155.html", null ],
        [ "stdair::NonInitialisedRelationShipException", "a00156.html", null ],
        [ "stdair::NonInitialisedServiceException", "a00157.html", null ],
        [ "stdair::ObjectLinkingException", "a00159.html", null ],
        [ "stdair::ObjectNotFoundException", "a00160.html", null ],
        [ "stdair::ParserException", "a00167.html", [
          [ "stdair::CodeConversionException", "a00090.html", null ],
          [ "stdair::CodeDuplicationException", "a00091.html", null ],
          [ "stdair::KeyDuplicationException", "a00142.html", null ],
          [ "stdair::ObjectCreationgDuplicationException", "a00158.html", null ],
          [ "stdair::ParsingFileFailedException", "a00168.html", null ]
        ] ],
        [ "stdair::SerialisationException", "a00194.html", null ],
        [ "stdair::SimpleNestingStructException", "a00197.html", [
          [ "stdair::BookingClassListEmptyInNestingStructException", "a00079.html", null ]
        ] ],
        [ "stdair::SQLDatabaseException", "a00202.html", [
          [ "stdair::SQLDatabaseConnectionImpossibleException", "a00201.html", null ]
        ] ]
      ] ]
    ] ],
    [ "stdair::FacAbstract", "a00113.html", [
      [ "stdair::FacBom< BOM >", "a00114.html", null ],
      [ "stdair::FacBomManager", "a00115.html", null ],
      [ "stdair::FacCloneBom< BOM >", "a00116.html", null ]
    ] ],
    [ "stdair::FacServiceAbstract", "a00117.html", [
      [ "stdair::FacSTDAIRServiceContext", "a00118.html", null ]
    ] ],
    [ "stdair::FacSupervisor", "a00119.html", null ],
    [ "FloatingPoint< RawType >", "a00132.html", null ],
    [ "std::forward_list< T >", null, null ],
    [ "std::ios_base", null, [
      [ "std::basic_ios< char >", null, null ],
      [ "std::basic_ios< wchar_t >", null, null ],
      [ "std::basic_ios< Char >", null, [
        [ "std::basic_istream< char >", null, null ],
        [ "std::basic_istream< wchar_t >", null, null ],
        [ "std::basic_ostream< char >", null, null ],
        [ "std::basic_ostream< wchar_t >", null, null ],
        [ "std::basic_istream< Char >", null, [
          [ "std::basic_ifstream< char >", null, null ],
          [ "std::basic_ifstream< wchar_t >", null, null ],
          [ "std::basic_iostream< char >", null, null ],
          [ "std::basic_iostream< wchar_t >", null, null ],
          [ "std::basic_istringstream< char >", null, null ],
          [ "std::basic_istringstream< wchar_t >", null, null ],
          [ "std::basic_ifstream< Char >", null, [
            [ "std::ifstream", null, null ],
            [ "std::wifstream", null, null ]
          ] ],
          [ "std::basic_iostream< Char >", null, [
            [ "std::basic_fstream< char >", null, null ],
            [ "std::basic_fstream< wchar_t >", null, null ],
            [ "std::basic_stringstream< char >", null, null ],
            [ "std::basic_stringstream< wchar_t >", null, null ],
            [ "std::basic_fstream< Char >", null, [
              [ "std::fstream", null, null ],
              [ "std::wfstream", null, null ]
            ] ],
            [ "std::basic_stringstream< Char >", null, [
              [ "std::stringstream", null, null ],
              [ "std::wstringstream", null, null ]
            ] ]
          ] ],
          [ "std::basic_istringstream< Char >", null, [
            [ "std::istringstream", null, null ],
            [ "std::wistringstream", null, null ]
          ] ],
          [ "std::istream", null, null ],
          [ "std::wistream", null, null ]
        ] ],
        [ "std::basic_ostream< Char >", null, [
          [ "std::basic_iostream< char >", null, null ],
          [ "std::basic_iostream< wchar_t >", null, null ],
          [ "std::basic_ofstream< char >", null, null ],
          [ "std::basic_ofstream< wchar_t >", null, null ],
          [ "std::basic_ostringstream< char >", null, null ],
          [ "std::basic_ostringstream< wchar_t >", null, null ],
          [ "std::basic_iostream< Char >", null, null ],
          [ "std::basic_ofstream< Char >", null, [
            [ "std::ofstream", null, null ],
            [ "std::wofstream", null, null ]
          ] ],
          [ "std::basic_ostringstream< Char >", null, [
            [ "std::ostringstream", null, null ],
            [ "std::wostringstream", null, null ]
          ] ],
          [ "std::ostream", null, null ],
          [ "std::wostream", null, null ]
        ] ],
        [ "std::ios", null, null ],
        [ "std::wios", null, null ]
      ] ]
    ] ],
    [ "std::forward_list< T >::iterator", null, null ],
    [ "std::map< K, T >::iterator", null, null ],
    [ "std::unordered_map< K, T >::iterator", null, null ],
    [ "std::multimap< K, T >::iterator", null, null ],
    [ "std::basic_string< Char >::iterator", null, null ],
    [ "std::unordered_multimap< K, T >::iterator", null, null ],
    [ "std::set< K >::iterator", null, null ],
    [ "std::string::iterator", null, null ],
    [ "std::unordered_set< K >::iterator", null, null ],
    [ "std::wstring::iterator", null, null ],
    [ "std::multiset< K >::iterator", null, null ],
    [ "std::list< T >::iterator", null, null ],
    [ "std::unordered_multiset< K >::iterator", null, null ],
    [ "std::vector< T >::iterator", null, null ],
    [ "std::deque< T >::iterator", null, null ],
    [ "stdair::JSONString", "a00140.html", null ],
    [ "stdair::KeyAbstract", "a00141.html", [
      [ "stdair::AirlineClassListKey", "a00052.html", null ],
      [ "stdair::AirlineFeatureKey", "a00054.html", null ],
      [ "stdair::AirportPairKey", "a00057.html", null ],
      [ "stdair::BomHolderKey", "a00066.html", null ],
      [ "stdair::BomRootKey", "a00075.html", null ],
      [ "stdair::BookingClassKey", "a00078.html", null ],
      [ "stdair::BucketKey", "a00083.html", null ],
      [ "stdair::DatePeriodKey", "a00098.html", null ],
      [ "stdair::FareFamilyKey", "a00121.html", null ],
      [ "stdair::FareFeaturesKey", "a00123.html", null ],
      [ "stdair::FlightDateKey", "a00129.html", null ],
      [ "stdair::FlightPeriodKey", "a00131.html", null ],
      [ "stdair::InventoryKey", "a00138.html", null ],
      [ "stdair::LegCabinKey", "a00145.html", null ],
      [ "stdair::LegDateKey", "a00147.html", null ],
      [ "stdair::NestingNodeKey", "a00151.html", null ],
      [ "stdair::NestingStructureKey", "a00152.html", null ],
      [ "stdair::OnDDateKey", "a00163.html", null ],
      [ "stdair::ParsedKey", "a00166.html", null ],
      [ "stdair::PolicyKey", "a00174.html", null ],
      [ "stdair::PosChannelKey", "a00176.html", null ],
      [ "stdair::SegmentCabinKey", "a00187.html", null ],
      [ "stdair::SegmentDateKey", "a00189.html", null ],
      [ "stdair::SegmentPeriodKey", "a00191.html", null ],
      [ "stdair::SegmentSnapshotTableKey", "a00193.html", null ],
      [ "stdair::TimePeriodKey", "a00208.html", null ],
      [ "stdair::YieldFeaturesKey", "a00217.html", null ],
      [ "stdair::YieldStoreKey", "a00220.html", null ]
    ] ],
    [ "std::list< T >", null, null ],
    [ "std::list< BidPriceVector_T >", null, null ],
    [ "std::list< BOM * >", null, null ],
    [ "std::list< BookingClass * >", null, null ],
    [ "std::list< BookingClassID_T >", null, null ],
    [ "std::list< ClassAvailabilityMap_T >", null, null ],
    [ "std::list< ClassBpvMap_T >", null, null ],
    [ "std::list< ClassObjectIDMap_T >", null, null ],
    [ "std::list< ClassYieldMap_T >", null, null ],
    [ "std::list< FacAbstract * >", null, null ],
    [ "std::list< FacServiceAbstract * >", null, null ],
    [ "std::list< FareOptionStruct >", null, null ],
    [ "std::list< OnDString_T >", null, null ],
    [ "std::list< Policy * >", null, null ],
    [ "std::list< SegmentDate * >", null, null ],
    [ "std::list< std::string >", null, null ],
    [ "std::list< VirtualClassStruct >", null, null ],
    [ "stdair::Logger", "a00148.html", null ],
    [ "std::map< K, T >", null, null ],
    [ "std::map< CabinCode_T, ClassList_String_T >", null, null ],
    [ "std::map< CabinCode_T, WTPDemandPair_T >", null, null ],
    [ "std::map< const DTD_T, double >", null, null ],
    [ "std::map< const DTD_T, FRAT5_T >", null, null ],
    [ "std::map< const MapKey_T, BOM * >", null, null ],
    [ "std::map< const MapKey_T, ClassIndex_T >", null, null ],
    [ "std::map< const SegmentCabin *, SegmentDataID_T >", null, null ],
    [ "std::map< const std::string, FFDisutilityCurve_T >", null, null ],
    [ "std::map< const std::string, FRAT5Curve_T >", null, null ],
    [ "std::map< const std::type_info *, BomAbstract * >", null, null ],
    [ "std::map< const Yield_T, double >", null, null ],
    [ "std::map< std::string, CabinClassPairList_T >", null, null ],
    [ "std::map< std::string, YieldDemandPair_T >", null, null ],
    [ "std::map< YieldLevel_T, MeanStdDevPair_T >", null, null ],
    [ "std::multimap< K, T >", null, null ],
    [ "std::multiset< K >", null, null ],
    [ "std::priority_queue< T >", null, null ],
    [ "std::queue< T >", null, null ],
    [ "std::forward_list< T >::reverse_iterator", null, null ],
    [ "std::list< T >::reverse_iterator", null, null ],
    [ "std::unordered_multiset< K >::reverse_iterator", null, null ],
    [ "std::unordered_multimap< K, T >::reverse_iterator", null, null ],
    [ "std::unordered_map< K, T >::reverse_iterator", null, null ],
    [ "std::set< K >::reverse_iterator", null, null ],
    [ "std::map< K, T >::reverse_iterator", null, null ],
    [ "std::string::reverse_iterator", null, null ],
    [ "std::basic_string< Char >::reverse_iterator", null, null ],
    [ "std::unordered_set< K >::reverse_iterator", null, null ],
    [ "std::wstring::reverse_iterator", null, null ],
    [ "std::multiset< K >::reverse_iterator", null, null ],
    [ "std::multimap< K, T >::reverse_iterator", null, null ],
    [ "std::deque< T >::reverse_iterator", null, null ],
    [ "std::vector< T >::reverse_iterator", null, null ],
    [ "stdair::RootFilePath", "a00183.html", [
      [ "stdair::InputFilePath", "a00136.html", [
        [ "stdair::ConfigINIFile", "a00094.html", null ],
        [ "stdair::FFDisutilityFilePath", "a00126.html", null ],
        [ "stdair::FRAT5FilePath", "a00135.html", null ],
        [ "stdair::ODFilePath", "a00161.html", null ],
        [ "stdair::ScheduleFilePath", "a00185.html", null ]
      ] ]
    ] ],
    [ "stdair::ServiceAbstract", "a00195.html", [
      [ "stdair::STDAIR_ServiceContext", "a00205.html", null ]
    ] ],
    [ "std::set< K >", null, null ],
    [ "swift::SKeymap", "a00199.html", null ],
    [ "std::smart_ptr< T >", null, null ],
    [ "swift::SReadline", "a00203.html", null ],
    [ "std::stack< T >", null, null ],
    [ "stdair::STDAIR_Service", "a00204.html", null ],
    [ "stdair::StructAbstract", "a00206.html", [
      [ "stdair::AirlineStruct", "a00055.html", null ],
      [ "stdair::BasDBParams", "a00059.html", null ],
      [ "stdair::BasLogParams", "a00061.html", null ],
      [ "stdair::BookingRequestStruct", "a00080.html", null ],
      [ "stdair::BreakPointStruct", "a00081.html", null ],
      [ "stdair::CancellationStruct", "a00085.html", null ],
      [ "stdair::ConfigHolderStruct", "a00093.html", null ],
      [ "stdair::DemandGenerationMethod", "a00106.html", null ],
      [ "stdair::DoWStruct", "a00109.html", null ],
      [ "stdair::EventStruct", "a00111.html", null ],
      [ "stdair::EventType", "a00112.html", null ],
      [ "stdair::FareOptionStruct", "a00124.html", null ],
      [ "stdair::FFDisutilityCurveHolderStruct", "a00125.html", null ],
      [ "stdair::ForecastingMethod", "a00133.html", null ],
      [ "stdair::FRAT5CurveHolderStruct", "a00134.html", null ],
      [ "stdair::JSonCommand", "a00139.html", null ],
      [ "stdair::OptimisationMethod", "a00164.html", null ],
      [ "stdair::OptimisationNotificationStruct", "a00165.html", null ],
      [ "stdair::PartnershipTechnique", "a00169.html", null ],
      [ "stdair::PassengerChoiceModel", "a00170.html", null ],
      [ "stdair::PassengerType", "a00171.html", null ],
      [ "stdair::PeriodStruct", "a00172.html", null ],
      [ "stdair::PreOptimisationMethod", "a00177.html", null ],
      [ "stdair::ProgressStatus", "a00178.html", null ],
      [ "stdair::ProgressStatusSet", "a00179.html", null ],
      [ "stdair::RandomGeneration", "a00180.html", null ],
      [ "stdair::RMEventStruct", "a00181.html", null ],
      [ "stdair::SampleType", "a00184.html", null ],
      [ "stdair::ServiceInitialisationType", "a00196.html", null ],
      [ "stdair::SnapshotStruct", "a00200.html", null ],
      [ "stdair::TravelSolutionStruct", "a00209.html", null ],
      [ "stdair::UnconstrainingMethod", "a00214.html", null ],
      [ "stdair::VirtualClassStruct", "a00215.html", null ],
      [ "stdair::YieldRange", "a00218.html", null ]
    ] ],
    [ "std::system_error", null, null ],
    [ "std::thread", null, null ],
    [ "soci::type_conversion< stdair::AirlineStruct >", "a00210.html", null ],
    [ "TypeWithSize< size >", "a00211.html", null ],
    [ "TypeWithSize< 4 >", "a00212.html", null ],
    [ "TypeWithSize< 8 >", "a00213.html", null ],
    [ "TypeWithSize< sizeof(RawType)>", "a00211.html", null ],
    [ "std::unique_ptr< T >", null, null ],
    [ "std::unordered_map< K, T >", null, null ],
    [ "std::unordered_multimap< K, T >", null, null ],
    [ "std::unordered_multiset< K >", null, null ],
    [ "std::unordered_set< K >", null, null ],
    [ "std::valarray< T >", null, null ],
    [ "std::vector< T >", null, null ],
    [ "std::vector< AirlineCode_T >", null, null ],
    [ "std::vector< BidPrice_T >", null, null ],
    [ "std::vector< bool >", null, null ],
    [ "std::vector< ClassList_String_T >", null, null ],
    [ "std::vector< DictionaryKey_T >", null, null ],
    [ "std::vector< double >", null, null ],
    [ "std::vector< MeanStdDevPair_T >", null, null ],
    [ "std::vector< ServiceAbstract * >", null, null ],
    [ "std::weak_ptr< T >", null, null ],
    [ "BOM *", null, null ],
    [ "bool", null, null ],
    [ "char", null, null ],
    [ "char *", null, null ],
    [ "char const *", null, null ],
    [ "const Date_T", null, null ],
    [ "const DateTime_T", null, null ],
    [ "const DayDuration_T", null, null ],
    [ "const DTD_T", null, null ],
    [ "const Duration_T", null, null ],
    [ "const NbOfSeats_T", null, null ],
    [ "const PriceValue_T", null, null ],
    [ "const size_t", null, null ],
    [ "const WTP_T", null, null ],
    [ "date", null, null ],
    [ "date_duration", null, null ],
    [ "date_period", null, null ],
    [ "DBSession_T *", null, null ],
    [ "double", null, null ],
    [ "EN_DemandGenerationMethod", null, null ],
    [ "EN_EventType", null, null ],
    [ "EN_EventType", null, null ],
    [ "EN_EventType", null, null ],
    [ "EN_ForecastingMethod", null, null ],
    [ "EN_JSonCommand", null, null ],
    [ "EN_LogLevel", null, null ],
    [ "EN_LogLevel", null, null ],
    [ "EN_OptimisationMethod", null, null ],
    [ "EN_PartnershipTechnique", null, null ],
    [ "EN_PassengerChoiceModel", null, null ],
    [ "EN_PassengerType", null, null ],
    [ "EN_PreOptimisationMethod", null, null ],
    [ "EN_SampleType", null, null ],
    [ "EN_ServiceInitialisationType", null, null ],
    [ "EN_UnconstrainingMethod", null, null ],
    [ "int", null, null ],
    [ "K", null, null ],
    [ "Keymap", null, null ],
    [ "MeanStdDevPair_T", null, null ],
    [ "minstd_rand", null, null ],
    [ "multi_array< double, 2 >", null, null ],
    [ "pt2Func *", null, null ],
    [ "ptime", null, null ],
    [ "RawType", null, null ],
    [ "rl_completion_func_t *", null, null ],
    [ "shared_ptr< BookingRequestStruct >", null, null ],
    [ "shared_ptr< BreakPointStruct >", null, null ],
    [ "shared_ptr< CancellationStruct >", null, null ],
    [ "shared_ptr< ConfigHolderStruct >", null, null ],
    [ "shared_ptr< OptimisationNotificationStruct >", null, null ],
    [ "shared_ptr< RMEventStruct >", null, null ],
    [ "shared_ptr< SnapshotStruct >", null, null ],
    [ "short", null, null ],
    [ "static const Bits", null, null ],
    [ "static const char", null, null ],
    [ "static const size_t", null, null ],
    [ "T", null, null ],
    [ "time_duration", null, null ],
    [ "type_info *", null, null ],
    [ "unsigned short", null, null ],
    [ "vector< T >", null, null ],
    [ "WTPDemandPair_T", null, null ],
    [ "YieldDemandPair_T", null, null ],
    [ "YieldLevel_T", null, null ]
];