# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/localoriuser/dev/sim/stdair/stdairgit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/localoriuser/dev/sim/stdair/stdairgit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"devel\" \"runtime\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/localoriuser/dev/sim/stdair/stdairgit/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/localoriuser/dev/sim/stdair/stdairgit/CMakeFiles /home/localoriuser/dev/sim/stdair/stdairgit/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/localoriuser/dev/sim/stdair/stdairgit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named devhelpers

# Build rule for target.
devhelpers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 devhelpers
.PHONY : devhelpers

# fast build rule for target.
devhelpers/fast:
	$(MAKE) -f CMakeFiles/devhelpers.dir/build.make CMakeFiles/devhelpers.dir/build
.PHONY : devhelpers/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f CMakeFiles/dist.dir/build.make CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named hdr_cfg_stdair

# Build rule for target.
hdr_cfg_stdair: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hdr_cfg_stdair
.PHONY : hdr_cfg_stdair

# fast build rule for target.
hdr_cfg_stdair/fast:
	$(MAKE) -f stdair/CMakeFiles/hdr_cfg_stdair.dir/build.make stdair/CMakeFiles/hdr_cfg_stdair.dir/build
.PHONY : hdr_cfg_stdair/fast

#=============================================================================
# Target rules for targets named stdairbin

# Build rule for target.
stdairbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stdairbin
.PHONY : stdairbin

# fast build rule for target.
stdairbin/fast:
	$(MAKE) -f stdair/CMakeFiles/stdairbin.dir/build.make stdair/CMakeFiles/stdairbin.dir/build
.PHONY : stdairbin/fast

#=============================================================================
# Target rules for targets named stdairlib

# Build rule for target.
stdairlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stdairlib
.PHONY : stdairlib

# fast build rule for target.
stdairlib/fast:
	$(MAKE) -f stdair/CMakeFiles/stdairlib.dir/build.make stdair/CMakeFiles/stdairlib.dir/build
.PHONY : stdairlib/fast

#=============================================================================
# Target rules for targets named stdairuicllib

# Build rule for target.
stdairuicllib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stdairuicllib
.PHONY : stdairuicllib

# fast build rule for target.
stdairuicllib/fast:
	$(MAKE) -f stdair/CMakeFiles/stdairuicllib.dir/build.make stdair/CMakeFiles/stdairuicllib.dir/build
.PHONY : stdairuicllib/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f doc/CMakeFiles/doc.dir/build.make doc/CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named img_favicon.ico

# Build rule for target.
img_favicon.ico: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 img_favicon.ico
.PHONY : img_favicon.ico

# fast build rule for target.
img_favicon.ico/fast:
	$(MAKE) -f doc/CMakeFiles/img_favicon.ico.dir/build.make doc/CMakeFiles/img_favicon.ico.dir/build
.PHONY : img_favicon.ico/fast

#=============================================================================
# Target rules for targets named img_sfx_logo.png

# Build rule for target.
img_sfx_logo.png: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 img_sfx_logo.png
.PHONY : img_sfx_logo.png

# fast build rule for target.
img_sfx_logo.png/fast:
	$(MAKE) -f doc/CMakeFiles/img_sfx_logo.png.dir/build.make doc/CMakeFiles/img_sfx_logo.png.dir/build
.PHONY : img_sfx_logo.png/fast

#=============================================================================
# Target rules for targets named img_stdair_logo.png

# Build rule for target.
img_stdair_logo.png: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 img_stdair_logo.png
.PHONY : img_stdair_logo.png

# fast build rule for target.
img_stdair_logo.png/fast:
	$(MAKE) -f doc/CMakeFiles/img_stdair_logo.png.dir/build.make doc/CMakeFiles/img_stdair_logo.png.dir/build
.PHONY : img_stdair_logo.png/fast

#=============================================================================
# Target rules for targets named pdf

# Build rule for target.
pdf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pdf
.PHONY : pdf

# fast build rule for target.
pdf/fast:
	$(MAKE) -f doc/CMakeFiles/pdf.dir/build.make doc/CMakeFiles/pdf.dir/build
.PHONY : pdf/fast

#=============================================================================
# Target rules for targets named dbadmin

# Build rule for target.
dbadmin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dbadmin
.PHONY : dbadmin

# fast build rule for target.
dbadmin/fast:
	$(MAKE) -f db/CMakeFiles/dbadmin.dir/build.make db/CMakeFiles/dbadmin.dir/build
.PHONY : dbadmin/fast

#=============================================================================
# Target rules for targets named man

# Build rule for target.
man: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 man
.PHONY : man

# fast build rule for target.
man/fast:
	$(MAKE) -f man/CMakeFiles/man.dir/build.make man/CMakeFiles/man.dir/build
.PHONY : man/fast

#=============================================================================
# Target rules for targets named StdAirTesttst

# Build rule for target.
StdAirTesttst: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StdAirTesttst
.PHONY : StdAirTesttst

# fast build rule for target.
StdAirTesttst/fast:
	$(MAKE) -f test/stdair/CMakeFiles/StdAirTesttst.dir/build.make test/stdair/CMakeFiles/StdAirTesttst.dir/build
.PHONY : StdAirTesttst/fast

#=============================================================================
# Target rules for targets named check_stdairtst

# Build rule for target.
check_stdairtst: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_stdairtst
.PHONY : check_stdairtst

# fast build rule for target.
check_stdairtst/fast:
	$(MAKE) -f test/stdair/CMakeFiles/check_stdairtst.dir/build.make test/stdair/CMakeFiles/check_stdairtst.dir/build
.PHONY : check_stdairtst/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... check"
	@echo "... devhelpers"
	@echo "... dist"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... hdr_cfg_stdair"
	@echo "... stdairbin"
	@echo "... stdairlib"
	@echo "... stdairuicllib"
	@echo "... doc"
	@echo "... img_favicon.ico"
	@echo "... img_sfx_logo.png"
	@echo "... img_stdair_logo.png"
	@echo "... pdf"
	@echo "... dbadmin"
	@echo "... man"
	@echo "... StdAirTesttst"
	@echo "... check_stdairtst"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

