#ifndef __STDAIR_BOM_BOMKEYMANAGER_HPP
#define __STDAIR_BOM_BOMKEYMANAGER_HPP

// //////////////////////////////////////////////////////////////////////
// Import section
// //////////////////////////////////////////////////////////////////////
// STL
#include <iosfwd>
// StdAir
#include <stdair/stdair_basic_types.hpp>

namespace stdair {

  /// Forward declarations
  struct BomRootKey;
  struct InventoryKey;
  struct FlightDateKey;
  struct LegDateKey;
  struct SegmentDateKey;
  struct LegCabinKey;
  struct SegmentCabinKey;
  struct FareFamilyKey;
  struct BookingClassKey;

  /**
   * @brief Utility class to extract key structures from strings.
   */
  class BomKeyManager {
  public:
    // //////////////// Key management support methods /////////////////
    /**
     * Build an InventoryKey object from a (full) key string.
     *
     * The full key string gathers airline code, flight number, origin
     * and destination, cabin and booking class. It corresponds to the
     * output generated by the toString() methods of the XxxKey
     * structures.
     *
     * @param const std::string& The full key string.
     * @return InventoryKey The just built InventoryKey object.
     */
    static InventoryKey extractInventoryKey (const std::string& iFullKeyStr);

    /**
     * Build an FlightDateKey object from a (full) key string.
     *
     * The full key string gathers airline code, flight number, origin
     * and destination, cabin and booking class. It corresponds to the
     * output generated by the toString() methods of the XxxKey
     * structures.
     *
     * @param const std::string& The full key string.
     * @return FlightDateKey The just built FlightDateKey object.
     */
    static FlightDateKey extractFlightDateKey (const std::string& iFullKeyStr);

    /**
     * Build an SegmentDateKey object from a (full) key string.
     *
     * The full key string gathers airline code, flight number, origin
     * and destination, cabin and booking class. It corresponds to the
     * output generated by the toString() methods of the XxxKey
     * structures.
     *
     * @param const std::string& The full key string.
     * @return SegmentDateKey The just built SegmentDateKey object.
     */
    static SegmentDateKey extractSegmentDateKey (const std::string& iFullKeyStr);

    /**
     * Build an BookingClassKey object from a (full) key string.
     *
     * The full key string gathers airline code, flight number, origin
     * and destination, cabin and booking class. It corresponds to the
     * output generated by the toString() methods of the XxxKey
     * structures.
     *
     * @param const std::string& The full key string.
     * @return BookingClassKey The just built BookingClassKey object.
     */
    static BookingClassKey
    extractBookingClassKey (const std::string& iFullKeyStr);
  };
  
}
#endif // __STDAIR_BOM_BOMKEYMANAGER_HPP
