#ifndef __STDAIR_BOM_BOMRETRIEVER_HPP
#define __STDAIR_BOM_BOMRETRIEVER_HPP

// //////////////////////////////////////////////////////////////////////
// Import section
// //////////////////////////////////////////////////////////////////////
// STL
#include <iosfwd>
// StdAir
#include <stdair/stdair_basic_types.hpp>

namespace stdair {

  /// Forward declarations
  class BomRoot;
  class Inventory;
  class FlightDate;
  class LegDate;
  class SegmentDate;
  class LegCabin;
  class SegmentCabin;
  class FareFamily;
  class BookingClass;

  /**
   * @brief Utility class to retrieve StdAir objects.
   */
  class BomRetriever {
  public:
    // //////////////// Key management support methods /////////////////
    /**
     * Retrieve an Inventory object from a (full) key string.
     *
     * The full key string gathers airline code, flight number, origin
     * and destination, cabin and booking class. It corresponds to the
     * output generated by the toString() methods of the XxxKey
     * structures.
     *
     * @param const BomRoot& The root of the BOM tree.
     * @param const std::string& The full key string.
     * @return Inventory* The just retrieved Inventory object.
     */
    static Inventory*
    retrieveInventoryFromLongKey (const BomRoot&,
                                  const std::string& iFullKeyStr);

    /**
     * Retrieve an Inventory object from a (short) key string.
     *
     * The short key string is the airline code. It corresponds to the
     * output generated by the toString() methods of the InventoryKey
     * structure.
     *
     * @param const BomRoot& The root of the BOM tree.
     * @param const std::string& The full key string.
     * @return Inventory* The just retrieved Inventory object.
     */
    static Inventory*
    retrieveInventoryFromShortKey (const BomRoot&,
                                   const std::string& iShortKeyStr);

    /**
     * Retrieve an Inventory object from an InventoryKey structure.
     *
     * @param const BomRoot& The root of the BOM tree.
     * @param const InventoryKey& The key.
     * @return Inventory* The just retrieved Inventory object.
     */
    static Inventory* retrieveInventoryFromKey (const BomRoot&,
                                                const InventoryKey&);

    /**
     * Retrieve an Inventory object from an InventoryKey structure.
     *
     * @param const BomRoot& The root of the BOM tree.
     * @param const AirlineCode_T& The key.
     * @return Inventory* The just retrieved Inventory object.
     */
    static Inventory* retrieveInventoryFromKey (const BomRoot&,
                                                const AirlineCode_T&);

    /**
     * Retrieve an FlightDate object from a (full) key string.
     *
     * The full key string gathers airline code, flight number, origin
     * and destination, cabin and booking class. It corresponds to the
     * output generated by the toString() methods of the XxxKey
     * structures.
     *
     * @param const BomRoot& The root of the BOM tree.
     * @param const std::string& The full key string.
     * @return FlightDate* The just retrieved FlightDate object.
     */
    static FlightDate*
    retrieveFlightDateFromLongKey (const BomRoot&,
                                   const std::string& iFullKeyStr);

    /**
     * Retrieve an FlightDate object from a (full) key string.
     *
     * The full key string gathers airline code, flight number, origin
     * and destination, cabin and booking class. It corresponds to the
     * output generated by the toString() methods of the XxxKey
     * structures.
     *
     * @param const Inventory& The root of the BOM tree.
     * @param const std::string& The full key string.
     * @return FlightDate* The just retrieved FlightDate object.
     */
    static FlightDate*
    retrieveFlightDateFromLongKey (const Inventory&,
                                   const std::string& iFullKeyStr);

    /**
     * Retrieve an FlightDate object from a (short) key string.
     *
     * The short key string is the airline code. It corresponds to the
     * output generated by the toString() methods of the FlightDateKey
     * structure.
     *
     * @param const Inventory& The root of the BOM tree.
     * @param const std::string& The full key string.
     * @return FlightDate* The just retrieved FlightDate object.
     */
    static FlightDate*
    retrieveFlightDateFromShortKey (const Inventory&,
                                    const std::string& iShortKeyStr);

    /**
     * Retrieve an FlightDate object from an FlightDateKey structure.
     *
     * @param const Inventory& The root of the BOM tree.
     * @param const FlightDateKey& The key.
     * @return FlightDate* The just retrieved FlightDate object.
     */
    static FlightDate* retrieveFlightDateFromKey (const Inventory&,
                                                  const FlightDateKey&);

    /**
     * Retrieve an FlightDate object from an FlightDateKey structure.
     *
     * @param const Inventory& The root of the BOM tree.
     * @param const FlightNumber_T& Part of the key.
     * @param const Date_T& Part of the key.
     * @return FlightDate* The just retrieved FlightDate object.
     */
    static FlightDate* retrieveFlightDateFromKey (const Inventory&,
                                                  const FlightNumber_T&,
                                                  const Date_T& iFlightDateDate);

    /**
     * Retrieve an SegmentDate object from a (full) key string.
     *
     * The full key string gathers airline code, segment number, origin
     * and destination, cabin and booking class. It corresponds to the
     * output generated by the toString() methods of the XxxKey
     * structures.
     *
     * @param const BomRoot& The root of the BOM tree.
     * @param const std::string& The full key string.
     * @return SegmentDate* The just retrieved SegmentDate object.
     */
    static SegmentDate*
    retrieveSegmentDateFromLongKey (const BomRoot&,
                                    const std::string& iFullKeyStr);

    /**
     * Retrieve an SegmentDate object from a (full) key string.
     *
     * The full key string gathers airline code, segment number, origin
     * and destination, cabin and booking class. It corresponds to the
     * output generated by the toString() methods of the XxxKey
     * structures.
     *
     * @param const Inventory& The root of the BOM tree.
     * @param const std::string& The full key string.
     * @return SegmentDate* The just retrieved SegmentDate object.
     */
    static SegmentDate*
    retrieveSegmentDateFromLongKey (const Inventory&,
                                    const std::string& iFullKeyStr);

    /**
     * Retrieve an SegmentDate object from a (full) key string.
     *
     * The full key string gathers airline code, segment number, origin
     * and destination, cabin and booking class. It corresponds to the
     * output generated by the toString() methods of the XxxKey
     * structures.
     *
     * @param const FlightDate& The root of the BOM tree.
     * @param const std::string& The full key string.
     * @return SegmentDate* The just retrieved SegmentDate object.
     */
    static SegmentDate*
    retrieveSegmentDateFromLongKey (const FlightDate&,
                                    const std::string& iFullKeyStr);

    /**
     * Retrieve an SegmentDate object from a (short) key string.
     *
     * The short key string is the airline code. It corresponds to the
     * output generated by the toString() methods of the SegmentDateKey
     * structure.
     *
     * @param const FlightDate& The root of the BOM tree.
     * @param const std::string& The full key string.
     * @return SegmentDate* The just retrieved SegmentDate object.
     */
    static SegmentDate*
    retrieveSegmentDateFromShortKey (const FlightDate&,
                                     const std::string& iShortKeyStr);

    /**
     * Retrieve an SegmentDate object from an SegmentDateKey structure.
     *
     * @param const FlightDate& The root of the BOM tree.
     * @param const SegmentDateKey& The key.
     * @return SegmentDate* The just retrieved SegmentDate object.
     */
    static SegmentDate* retrieveSegmentDateFromKey (const FlightDate&,
                                                    const SegmentDateKey&);

    /**
     * Retrieve an SegmentDate object from an SegmentDateKey structure.
     *
     * @param const FlightDate& The root of the BOM tree.
     * @param const AirportCode_T& Origin, part of the key.
     * @param const AirportCode_T& Destination, part of the key.
     * @return SegmentDate* The just retrieved SegmentDate object.
     */
    static SegmentDate*
    retrieveSegmentDateFromKey (const FlightDate&,
                                const AirportCode_T& iOrigin,
                                const AirportCode_T& iDestination);

    /**
     * Retrieve a BookingClass object from a (full) key string.
     *
     * The full key string gathers airline code, segment number, origin
     * and destination, cabin and booking class. It corresponds to the
     * output generated by the toString() methods of the XxxKey
     * structures.
     *
     * @param const BomRoot& The root of the BOM tree.
     * @param const std::string& The full key string.
     * @return BookingClass* The just retrieved BookingClass object.
     */
    static BookingClass*
    retrieveBookingClassFromLongKey (const BomRoot&,
                                     const std::string& iFullKeyStr);

    /**
     * Retrieve a BookingClass object from a (full) key string.
     *
     * The full key string gathers airline code, segment number, origin
     * and destination, cabin and booking class. It corresponds to the
     * output generated by the toString() methods of the XxxKey
     * structures.
     *
     * @param const Inventory& The root of the BOM tree.
     * @param const std::string& The full key string.
     * @return BookingClass* The just retrieved BookingClass object.
     */
    static BookingClass*
    retrieveBookingClassFromLongKey (const Inventory&,
                                     const std::string& iFullKeyStr);

    /**
     * Retrieve a BookingClass object from a (full) key string.
     *
     * The full key string gathers airline code, segment number, origin
     * and destination, cabin and booking class. It corresponds to the
     * output generated by the toString() methods of the XxxKey
     * structures.
     *
     * @param const Inventory& The root of the BOM tree.
     * @param const std::string& Part of the full key string.
     * @param const ClassCode_T& Part of the full key string.
     * @return BookingClass* The just retrieved BookingClass object.
     */
    static BookingClass*
    retrieveBookingClassFromLongKey (const Inventory&,
                                     const std::string& iFullKeyStr,
                                     const ClassCode_T&);
  };
  
}
#endif // __STDAIR_BOM_BOMRETRIEVER_HPP
